### ISSUE TITLE
Detect screen DPI automatically

### ISSUE THREAD

**Issue by ryanbooker** [cirruslabs/tart#104]
If I compare to my real machine, or to another implementation of Apple's virtualisation framework, the display is very blurry/fuzzy in tart VMs.

<img width="255" alt="Real (top), Tart (centre), Other (bottom)" src="https://user-images.githubusercontent.com/7423/170159517-765b706c-0774-482d-9bc6-a864f83c6642.png">

_Real (top), Tart (centre), Other (bottom)_

**Comment by fkorotkov** [comment]
Yeah, Tart doesn't yet automatically detect DPI of the screen to properly initialize the window. Ideally Tart should detect that and also automatically switch DPI if Tart window is moved to another physical screen.

For now the only workaround is to check your screens DPI manually and set it via `tart set --display` command.

**Comment by ryanbooker** [comment]
Thanks for that, I'd missed the xDPI portion of the --display option. However, I doesn't seem to make any difference if I set it to match my monitor.
