### ISSUE TITLE
Vagrant support

### ISSUE THREAD

**Issue by ringods** [cirruslabs/tart#108]
Next to a Packer plugin, it would be nice to have a [Vagrant](https://www.vagrantup.com/) plugin as well.

Hashicorp is converting the Ruby based Vagrant to Go, so please work along this Go transition rather than the Ruby based version.

https://www.hashicorp.com/blog/toward-vagrant-3-0

**Comment by geerlingguy** [comment]
Is this issue the one to follow for integration, or should we follow the one over in the Vagrant repo? https://github.com/hashicorp/vagrant/issues/12760

**Comment by fkorotkov** [comment]
Good point. Let's consolidate in the Vagrant repo.
