### ISSUE TITLE
tart icon is larger than other icons

### ISSUE THREAD

**Issue by damonbreeden** [cirruslabs/tart#112]
it's basic, but... the tart icon is larger in the dock than other icons

<img width="234" alt="image" src="https://user-images.githubusercontent.com/49255023/171952763-7d63e3d2-d344-4cfe-baa4-a55dcbb4f117.png">

**Comment by fkorotkov** [comment]
We tried to follow the [official guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/). I think we can just switch white to transparent and only leave the tart pie itself on the icon. 🤔
