### ISSUE TITLE
Create new VM fails

### ISSUE THREAD

**Issue by nycnewman** [cirruslabs/tart#113]
Trying to follow instructions show on repo home page and get following error:

tart clone ghcr.io/cirruslabs/macos-monterey-base:latest monterey-base

Error Domain=NSCocoaErrorDomain Code=4 "The file “monterey-base” doesn’t exist." UserInfo={NSFileOriginalItemLocationKey=file:///Users/edwardnewman/.tart/vms/monterey-base/, NSURL=file:///Users/edwardnewman/.tart/vms/monterey-base/, NSFileNewItemLocationKey=file:///var/folders/tz/4n8rgr6n6wj5cgqzjx1dh0_80000gq/T/6783566C-FA68-4C41-B53B-D3B32095B77E, NSUnderlyingError=0x600001e70570 {Error Domain=NSCocoaErrorDomain Code=4 "The file “6783566C-FA68-4C41-B53B-D3B32095B77E” doesn’t exist." UserInfo={NSURL=file:///var/folders/tz/4n8rgr6n6wj5cgqzjx1dh0_80000gq/T/6783566C-FA68-4C41-B53B-D3B32095B77E, NSFilePath=/var/folders/tz/4n8rgr6n6wj5cgqzjx1dh0_80000gq/T/6783566C-FA68-4C41-B53B-D3B32095B77E, NSUnderlyingError=0x600001e70690 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}

This is on MacOS 12.4 M1 machine

**Comment by fkorotkov** [comment]
Could you please check that you are using 0.7.1. Just fixed it in #111

**Comment by nycnewman** [comment]
That fixed the error but I see it hang on download if local file system runs out of space. With enough disk I was able to start a new instance
