### ISSUE TITLE
Tart appears to hide file errors

### ISSUE THREAD

**Issue by nycnewman** [cirruslabs/tart#114]
Specifically if the underlying machine disk is full the VM continues to run and no errors thrown.

**Comment by edigaryev** [comment]
By default disk files created by tart are sparsely allocated:

<img width="377" alt="Screenshot 2022-06-16 at 14 56 05" src="https://user-images.githubusercontent.com/85709/174064552-7832ea47-521d-486e-af19-7630227cb929.png">

This indeed poses a problem with storage over-subscription, however, I'm not sure if solving it by the means of monitoring the disk space is a good approach for a somewhat stateless virtualuzation solution like Tart.

Would adding an option to pre-allocate the disk space solve the problem for you? This way lack of storage errors will be caught before a VM is even started, but the drawback is that the creation will be slower.
