### ISSUE TITLE
Unable to install macOS 13 beta

### ISSUE THREAD

**Issue by vitorgalvao** [cirruslabs/tart#118]
```console
$ tart create --from-ipsw ~/macos13.ipsw ventura
Installing OS...
0%
Error Domain=VZErrorDomain Code=1 "Installation failed." UserInfo={NSLocalizedFailure=Internal Virtualization error., NSLocalizedFailureReason=Installation failed., NSUnderlyingError=0x600001249e90 {Error Domain=VZErrorDomain Code=1 "(null)"}}
```

[UTM is also failing](https://github.com/utmapp/UTM/issues/4099). Looks like @fkorotkov has [gotten it to work with modifications](https://twitter.com/fedor/status/1533922152201834500) but those aren’t live yet. Seems worth it to at least open an issue to track the situation.

* tart `0.8.1`
* macOS `12.4 (21F79)`
* MacBook Air (2020, M1)

**Comment by dan-snelson** [comment]
+1

@vitorgalvao Are you able to confirm your .IPSW works as expected via Apple Configurator 2?

**Comment by fkorotkov** [comment]
Interesting. The only thing I've done is recompiled Tart with Xcode 14 Beta and it worked for me. I'm on M1 Max though. Let me try to do the same on a M1 Mac Mini.

**Comment by vitorgalvao** [comment]
@dan-snelson I only have the one Mac so can’t check. Unless there’s something I’m not aware of. If you give specific steps, I’ll try to answer the question.

@fkorotkov Forgot to mention—In case that’s relevant—that I didn’t compile tart but instead installed with Homebrew as per the README. I inspected the formula and see it doesn’t build from source but just downloads the binary.

**Comment by fkorotkov** [comment]
Yeah. 0.8.1 is compiled with the Xcode 14 Beta and I'm testing with it. 

@vitorgalvao, do you have rosetta installed or any versions of Xcode? Just to have a full picture of your machine's setup.

**Comment by vitorgalvao** [comment]
> rosetta installed

Yes.

> any versions of Xcode

Also yes. `13.4.1 (13F100)`.

**Comment by fkorotkov** [comment]
It seems you all [might need Xcode 14 Beta installed](https://github.com/utmapp/UTM/issues/4099#issuecomment-1149050748).

**Comment by vitorgalvao** [comment]
Confirmed installing Xcode 14 Beta and its components fixes it. Thank you for the fast investigation @fkorotkov!
