### ISSUE TITLE
Private registry authentication doesn't work with AWS ECR

### ISSUE THREAD

**Issue by victor-yousician** [cirruslabs/tart#144]
Command
`aws ecr get-login-password | tart login --username AWS --password-stdin $host`
throws error
`invalid credentials: AuthFailed(why: "WWW-Authenticate header\'s authentication scheme \"Basic\" is unsupported, expected \"Bearer\" scheme", details: "")`

**Comment by fkorotkov** [comment]
@victor-yousician please try `0.13.0` version. BTW are you using the AWS EC2 M1 instances by any chance?

**Comment by victor-yousician** [comment]
> @victor-yousician please try `0.13.0` version. 

Will do, thank you!
> BTW are you using the AWS EC2 M1 instances by any chance?

No, we are not.
