### ISSUE TITLE
multi-disk attachment CLI args

### ISSUE THREAD

**Issue by jerrymarino** [cirruslabs/tart#150]
I'm looking to improve deployment and iteration cycles with massive build system baked macOS VMs: a montery VM + Xcode 13.3.1 clocking in at 30GB of disk space - running `brew install` with a few packages further exasturbates the slowdown. Also, pulling and pushing a contiguous VM of 40gb quickly gets expensive with a larger number of VMs!

I'd like to come up with an ideal CLI and integration of this inside of tart. To remediate this I will likely do the following:
- build a base macOS VM 
- pack some binaries into a disk image, or Bazel build a disk image with the software
- pull the images from S3
- mount the disk images into the VM

I might propose a CLI interface similar to dockers `-v` argument:

```
tart run some -v /path/to/img # default is rw
```

A readonly volume:
```
tart run some -v /path/to/img:ro
```

Multiple volumes:
```
tart run some -v /path/to/img:ro -v /pat/to/other:rw
```

The other alternative would be to clone a VM and install it into the properties:
```
tart set some volumes /path/to/img:ro
```

Maybe these aren't mutually exclusive, but would like to start with one.

**Comment by jerrymarino** [comment]
The other distinct alternative I have been kicking the tires of is to start consuming tart as a custom library and expose APIs to feed it custom VM configs. This might be a better approach overall for a more complex integration like the Bazel rule: https://github.com/bazel-ios/rules_ios/pull/509 . Then maybe I would rewrite the program into Swift and call tart in that program instead of bash!

**Comment by fkorotkov** [comment]
@jerrymarino, first of all, wow! 👏 My hat is down, sir. Great to see Tart is getting used in more and more ways. Tart itself is a Swift package and it's license compatible with `bazel-ios/rules_ios`'s license. On a side note, we chose AGPL license so modifications to the Tart sources itself should be disclosed, but it can be used as a library. We can definitely think of higher level APIs that we can expose so you can manage VMs easier.

Now regarding the original question about disk attachements. `Virtualization.Framework` provides only [`VZDiskImageStorageDeviceAttachment`](https://developer.apple.com/documentation/virtualization/vzdiskimagestoragedeviceattachment) which we already use just for the main disk with the OS. With Ventura though , we'll be able to share directories from the host (see #13) in a pretty much docker-like `-v` way. Will that work for you? Or you'd prefer bundle raw disks, store them in S3 and attache them?

**Comment by jerrymarino** [comment]
@fkorotkov you got it! Also, thanks again for making such an amazing tool and sharing all of your wins and tribulations with Virtualization.framework. This is in-valuable and saved me a ton of time: I would have never gotten this far already without all of the code and blog posts ya'll have written: e.g. about softnet, DHCP issues.

Of course, I'll definitely send over any improvements I come up with for it: the ones in-mind already are raised or proposed as github issues 😉 ! Actually making this bazel integration open source is key to easily share use cases and reference. The VM runner I came up with is a [simple bash program](https://github.com/bazel-ios/rules_ios/pull/509/files#diff-1791fbd8d65ebc0426882af14a9977865e87af5ebe582a15fb79ceaae2ed6bbaR36) - perhaps we can work to get all of these features into tart: port forwarding, ephemeral, etc. 

> With Ventura though , we'll be able to share directories from the host (see https://github.com/cirruslabs/tart/issues/13) in a pretty much docker-like -v way. Will that work for you


I'm going to give it a try to see how it plays out! Ultimately for rules_ios I would pick the solution I get the performance out of. But, maybe one is more secure or reliable than another. The nice thing about using a disk image is that it will be the same on each host / launch where sharing a directory necessitates managing directories and is harder to run a `sha256` against

**Comment by fkorotkov** [comment]
Good point on `sha256` and simplified distribution of such disks. I think it's reasonable to add something like `--disk $PWD/disk1.img:ro --disk $PWD/disk2.img:rm` which will even work on Monterey as well. #13 is more about having `--mount $PWD:/Users/admin/workspace` type of use I think. @edigaryev what do you think?

**Comment by fkorotkov** [comment]
I think @jerrymarino wants an ad-hoc solution to mount different disks with different sets/versions of tools/other stuff.

**Comment by rikur** [comment]
Can this be used on Cirrus persistent workers using Tart isolation?

**Comment by fkorotkov** [comment]
Not at the moment. What's your use case?

**Comment by fkorotkov** [comment]
@rikur are you planning to attache the same save disk over and over? A disk with a static path on the disk?

**Comment by rikur** [comment]
I'm hoping to share a volume/folder across multiple tasks for caching (and possibly to archive artifacts); Caching on Persistent Workers seems really slow and the cache upload often times out.

With faster caching on Persistent Workers, I think I could cut down the build time by 50%.

I've seen mentions of volumes and shared folders, but couldn't find documentation on how to use them.
