### ISSUE TITLE
--vnc and Screen Sharing clipboard

### ISSUE THREAD

**Issue by craighurley** [cirruslabs/tart#152]
The Screen Sharing clipboard is disabled with the `--vnc` argument.

```
$ tart run --vnc monterey-base
# Screen Sharing opens automatically and clipboard is disabled
```

```
$ tart run --no-graphics --vnc monterey-base
VNC server is running at vnc://:fury-hamster-then-gift@127.0.0.1:56316
# Manually open Screen Sharing at vnc://:fury-hamster-then-gift@127.0.0.1:56316 and clipboard is disabled
```

```
$ tart run --no-graphics monterey-base
$ tart ip monterey-base
192.168.64.2
# Manually open Screen Sharing at vnc://admin@192.168.64.2 and clipboard is enabled.
```

Have I misunderstood the help ("Useful since VNC supports copy/paste") or is this an issue?

**Comment by fkorotkov** [comment]
We switched to private APIs in order to have VNC support for recovery mode and for OS installation for future automation. Seems it introduced this regression. @edigaryev do you think `_VZVNCServer` has options to enable clipboard?

**Comment by edigaryev** [comment]
> do you think `_VZVNCServer` has options to enable clipboard?

I don't think so, [`VZSpiceAgentPortAttachment`](https://developer.apple.com/documentation/virtualization/vzspiceagentportattachment) is the most likely option, but it will only be available on macOS Ventura.

@craighurley would adding a separate `--screen-sharing` option that has the old behavior work for you?

**Comment by craighurley** [comment]
Great tool so far.  I'm glad to know that it's something you are considering whatever the approach 👍
