### ISSUE TITLE
Support for Apple Installer Packages for tart installations

### ISSUE THREAD

**Issue by uurazzle** [cirruslabs/tart#153]
Hi:

Thanks for making tart available to the community.

Would request you make apple installer packages available for installations & updates for Tart, which would make it easier and a more standard method used by MacAdmins to test, update and distribute to client systems.

**Comment by wegotoeleven** [comment]
Great idea! The ability for me to provide this app to my users using a tool like Jamf Pro Self Service would go a long way!

**Comment by fkorotkov** [comment]
Will a signed `*.dmg` work for you use case of automatic installation? We can add it as part of #184.

**Comment by wegotoeleven** [comment]
Personally, a DMG won’t work with the management solutions we use to deploy software out to our managed Macs. Ideally, a signed `*.pkg` would work better! If that’s possible.

**Comment by uurazzle** [comment]
Hi @fkorotkov:

Yes, I  agree. Installer Packages would be an easier and more standard method of installing and updating. PKG files are macOS installation packages containing installer scripts and compressed installation files used to install Mac software applications on a user's hard drive. The issue with DMG files is that it needs to be mounted as a virtual disk to push apps, whereas PKG files can be directly installed. There are methods for handling disk images used by MacAdmins, but it adds additional burden and friction to the management and distribution of software.

**Comment by fkorotkov** [comment]
I've spent quite some time trying to figure out how to create a `*.pkg` for a CLI tool like Tart and I'm kind of stuck. It seems `pkgbuild` tool is the one to look at but all the examples I found were around packing `*.App` bundles. Plus we use Swift Package Manager and all the example were using Xcode to build packages.

It seems we'll need help from someone knowledgable about `*.pkg` creation. I've figured out the signing part in #207 so once we'll figure the `*.pkg` part the it will be easy to sign and notarize it as well.

**Comment by dan-snelson** [comment]
[Packaging for Apple Administrators](https://scriptingosx.com/packaging-for-apple-administrators/)

**Comment by uurazzle** [comment]
Or this might be helpfull too: https://github.com/KosalaHerath/macos-installer-builder

**Comment by fkorotkov** [comment]
Just release `0.24.1` which [contains a signed `*.pkg`](https://github.com/cirruslabs/tart/releases/tag/0.24.1).

**Comment by uurazzle** [comment]
Hi @fkorotkov:

Thanks for the creation of the installer packages, it will make it easier to distribute & upgrade across Mac fleets.

**Comment by dan-snelson** [comment]
Thanks, @fkorotkov.

It'd be nice if the name of the `.PKG` included the version number:
`Tart-0.24.1.pkg`

**Comment by fkorotkov** [comment]
SGTM. See https://github.com/cirruslabs/tart/pull/218

**Comment by fkorotkov** [comment]
In order to support Bridged Network for `1.0.0` we had to repack `tart` executable in a `tart.app` structure and for some reason notarization of the `*.pkg` started failing with a weird `Invalid` error. We had to disable bulding `*.pkg` for now so I'm reopening the issue.

On this note. If there will be a `Tart.app` packaged in a `zip` or `dmg` will that work with your installers?

**Comment by wegotoeleven** [comment]
> Personally, a DMG won’t work with the management solutions we use to deploy software out to our managed Macs. Ideally, a signed `*.pkg` would work better! If that’s possible.

While some deployment mechanisms will be able to deploy apps straight from dmg and zip files, the preferred method _will always be_ a vendor signed package. Happy to help out with notarisation is needed though.

**Comment by fkorotkov** [comment]
Reintroduced the installer in `1.0.1`. Binary inside the archive is notarized now as well.
