### ISSUE TITLE
image push speed

### ISSUE THREAD

**Issue by victor-yousician** [cirruslabs/tart#158]
I'm testing pushing an image (monterey-base from your documentation) to AWS ECR. I'm pushing from a Mac mini (M1, 2020) hosted in a data centre with a gigabit connection but only averaging 1MB/s. tart keeps one core at 100%. This seems pretty slow.

**Comment by Nezz** [comment]
After 3 hours and 34 minutes we got to a whopping 44% of the image getting pushed:
```
time tart push monterey-base <redacted>.dkr.ecr.eu-west-1.amazonaws.com/ci/tart:20220728
pushing monterey-base to <redacted>.dkr.ecr.eu-west-1.amazonaws.com/ci/tart:20220728...
pushing disk... this will take a while...
44%
^CHTTPClientError.cancelled
tart push monterey-base   3756.16s user 9077.07s system 99% cpu 3:34:24.27 total
```

**Comment by fkorotkov** [comment]
In our case we push to GitHub's Container Registry and we've seen speed of 30-40MB/s from three different locations in US all with a symmetric gigabit connection: two datacenters and my home. We attributed it to just how uploads work e.g. registries are optimized for pulls. 

But a 1 MB/s speed seems like unreasonably slow. How far your DC with the Mac Mini and AWS region?

**Comment by edigaryev** [comment]
The 100% core usage seems weird.

Does it happen straight away after initiating the pull, or after some time?

Does it occur with other registries (e.g. when using GitHub Packages or Docker Hub) too?

**Comment by victor-yousician** [comment]
> Does it happen straight away after initiating the pull, or after some time?
> Does it occur with other registries (e.g. when using GitHub Packages or Docker Hub) too?

This issue is with push speed, not pull. CPU goes to 100% (one core) immediately. The only other test I have is a Docker Registry container running locally. I don't think it's a meaningful data point, but CPU stays around 20-25% and speeds are around 35-45MB/s.
