### ISSUE TITLE
tart gets locked out of its own passwords after a version upgrade

### ISSUE THREAD

**Issue by victor-yousician** [cirruslabs/tart#184]
To reproduce run `tart login ...` before tart upgrade and `tart pull ...` after the upgrade. You will get prompted for the "login" keychain password. And if you are connected via ssh it will fail with
`Failed(message: "Keychain returned unsuccessful status -25308")`
<img width="502" alt="image" src="https://user-images.githubusercontent.com/86827532/185346179-1036ba2b-1a53-4461-85de-90459c4068d9.png">

**Comment by Nezz** [comment]
We believe this happens because homebrew installs tart in a versioned folder. When we upgrade, the `tart` executable will be located at a different path. Since the keychain credential was added by a different program, macOS prompts the user if access should be allowed.

**Comment by victor-yousician** [comment]
It also might have something to do with the way the keys are added.
ACL for tart:
```
        applications (1):
            0: /opt/homebrew/Cellar/tart/0.17.0/bin/tart (status -67068)
                requirement: cdhash H"855cd4f4c2a149fb3fa8161e558eaf430977b3f1"
...
        authorizations (1): partition_id
        don't-require-password
        description: cdhash:855cd4f4c2a149fb3fa8161e558eaf430977b3f1
```
And ACL for VSCode, for example:
```
        applications (1):
            0: /Applications/Visual Studio Code.app (OK)
                requirement: identifier "com.microsoft.VSCode" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = UBF8T346G9
...
        authorizations (1): partition_id
        don't-require-password
        description: teamid:UBF8T346G9
```
CDHash would change between versions, but OU should stay the same.

**Comment by fkorotkov** [comment]
We'll probably will need to properly sign the binaries using something like https://github.com/mitchellh/gon in order to make Apple happy. I've requested some certificates and will try to work on it next week.
