### ISSUE TITLE
Unable to push container image to public GitLab repo

### ISSUE THREAD

**Issue by phao5814** [cirruslabs/tart#188]
First of all, thanks for this super nifty tool!

Honestly, not quite sure if this is a "me problem" or if there's a genuine bug here so I thought I'd just outline what steps I'm taking to find out:

1. I've created a public GitLab repo that I wish to push images to (without the need for credentials).
2. When I try pushing to this public repo with the following command:
```
tart push monterey-personal registry.gitlab.com/<my-public-repo>/monterey:12.15.1
```
I get the following output with nothing outputted and no progress made after this point (just hangs indefinitely):
```
tart push monterey-personal registry.gitlab.com/<my-public-repo>/monterey:12.15.1
pushing monterey-personal to registry.gitlab.com/<my-public-repo>/monterey:12.15.1...
pushing config...
```
Is pushing to GitLab supposed to be working? Additionally, should I be able to push an image to a public GitLab repo without the need to use any credentials?

**Comment by edigaryev** [comment]
>Is pushing to GitLab supposed to be working?

I've just checked against [gitlab.com/edigaryev/playground](https://gitlab.com/edigaryev/playground/container_registry) and it's working just fine.

The `pushing config...` might be related to the poor networking. Is it reproducible each time you invoke `tart push`?

Also, does the `docker push` work?

>Additionally, should I be able to push an image to a public GitLab repo without the need to use any credentials?

I don't think so. Here's what happens when I try to push an image without running `tart login` first:

```
% tart push macos-light registry.gitlab.com/edigaryev/playground:12.15.1
pushing macos-light to registry.gitlab.com/edigaryev/playground:12.15.1...
pushing config...
UnexpectedHTTPStatusCode(when: "pushing blob (POST)", code: 401, details: "{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"authentication required\",\"detail\":[{\"Type\":\"repository\",\"Class\":\"\",\"Name\":\"edigaryev/playground\",\"Action\":\"pull\"},{\"Type\":\"repository\",\"Class\":\"\",\"Name\":\"edigaryev/playground\",\"Action\":\"push\"}]}]}\n"
```

**Comment by phao5814** [comment]
Yep, you're most likely right about the poor networking at the time of trying. I can't seem to reproduce it anymore. Thanks for verifying that it works! Will close the issue sine I can't reproduce it.
