### ISSUE TITLE
Where do the macOS images get downloaded from when using IPSW?

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [cirruslabs/tart#197]
When running

```
$ tart create --from-ipsw=latest monterey-base
Looking up the latest supported IPSW...
Fetching 21G83.ipsw...
100%
Installing OS...
100%
```

on a Monterey, it correctly determines the latest Monterey (21G83 build corresponds to macOS 12.5.1).

I'm curious where do the images are coming from? I see that there is https://mesu.apple.com/assets/macos/com_apple_macOSIPSW/com_apple_macOSIPSW.xml and under `21G83` key there is a download link https://updates.cdn-apple.com/2022SummerFCS/fullrestores/012-51674/A7019DDB-3355-470F-A355-4162A187AB6C/UniversalMac_12.5.1_21G83_Restore.ipsw. So it's possible to determine the needed URL and download manually and then use `--from-ipsw` providing the manually downloaded file.

However, if using `latest`, where do the images are downloaded from? Searching through the source code I wasn't able to understand how the URL for the ipsw file is constructed: https://github.com/cirruslabs/tart/blob/main/Sources/tart/VM.swift#L114. Or is this functionality embedded into the macOS itself, i.e. you ask the OS itself to download the file?

Thanks!

**Comment by fkorotkov** [comment]
Tart is using [`VZMacOSRestoreImage#fetchLatestSupported `](https://developer.apple.com/documentation/virtualization/vzmacosrestoreimage/3858094-fetchlatestsupported) method [here](https://github.com/cirruslabs/tart/blob/553b36349b681d0dffd3913865cbf2c79b2fb172/Sources/tart/VM.swift#L63) to get an URL to download the file. Not sure about the internals of `fetchLatestSupported` but it seems it's doing pretty much the same and looking for `VirtualMac2,1` key in the XML to downloads from [https://updates.cdn-apple.com](https://updates.cdn-apple.com/2022SummerFCS/fullrestores/012-51674/A7019DDB-3355-470F-A355-4162A187AB6C/UniversalMac_12.5.1_21G83_Restore.ipsw)

**Comment by alexey-tereshenkov-oxb** [comment]
Oh perfect, then we know that we rely on macOS internal code to download the images, this is perfect. We can trust those images, in other words, as they come straight from Apple.
