### ISSUE TITLE
Nomad Plugin / Driver

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#201]
Tart itself is just a virtualization solution with some nifty features like ability to store images remotely in OCI registries.

But there is a need for some companies to be able to create a cluster of Mac hosts similar to what Anka is doing with their [Controller](https://veertu.com/anka-build/). For this use cases one can implement a [driver for Nomad](https://www.nomadproject.io/docs/drivers) to support isolation via Tart.

**Comment by naikrovek** [comment]
oh, this would be wonderful.  I am looking forward to this.  Currently I am writing my own tool which _sorta_ does what this would do, except my solution is bad and Nomad support would be very good.

**Comment by fkorotkov** [comment]
@naikrovek BTW what's your use case if I may ask? Are you planning to run long living VMs?

**Comment by naikrovek** [comment]
no, just CI/CD stuff.  I want a fresh VM each time and I want the VM destroyed when it is done doing its work.  I have a shell script & Go program which accomplish this today and having something that can scale up and down as need comes & goes would be very nice.   Maybe Nomad isn't the proper solution for this, I don't know.  I'm pretty new to all of this.

**Comment by naikrovek** [comment]
[here's the basics of what I'm doing](https://github.com/naikrovek/macos-vm-controller).  This is very new code and is still untested.

**Comment by fkorotkov** [comment]
We've looked into Nomad plugin and it seems too low level. We have couple of concerns:

1.  It's not trivial to configure a cluster securely
2. Operation of a cluster is also not trivial and require some
3. Nomad abstractions are limiting. For example, it won't be possible to build functionality like proxying SSH and VNC into VMs.

So we were thinking of creating a separate Tart Cluster piece that will be specifically targeting use case to cluster bunch of Apple Silicon Hardware to run Tart VMs on them...

**And we'd like to hear about your requirements!** Specifically around usage. Are you planning to use it only via API from your existing system? Do you want in addition a web UI where you can not only see the current state but also click things to create VMs? In case of web UI, do you need SSO/login functionality with different permissions for users?

**Comment by dniHze** [comment]
I think all the things you've listed are nice to have. I'm particularly insterested in GH Actions Autoscaling. We are big fans of GH Actions, and we thought about building our small cluster of mac minis/mac studios for our iOS team requirements. While having multiple virtual machines running simultaneously is a solution, I prefer scaling on demand on a particular VM image. Having cluster software to determine available resources, start and shutdown machines, and, execute commands on them (like scheduling GH Actions) are the most crucial for us.

**Comment by fkorotkov** [comment]
@dniHze we did pretty much the same for [Cirrus Runners](https://github.com/apps/cirrus-runners) and we'll try to incorporate these knowledge into Orchard (we started calling this project like that during our internal discussions).

Working on Cirrus Runners uncovered a few caveats about GitHub API for auto-scaling runners. We had to even implement some health checking so Cirrus Runners actively calls GitHub API to see if an agent became idle or hanged.

Hopefully we'll have something you can try in early February. In the meantime feel free to try out Cirrus Runners. 😉

**Comment by dniHze** [comment]
That sounds great, will be happy to give it a go if you need some actual dogfooding later. 

In regard to your suggestions, I have a few concerns about Cirrus Runners. They are not really related to the ticket, but I think they might be useful:
1. Lack of on-demand scaling and sizing. [BuildJet](https://buildjet.com/for-github-actions) would be a perfect example of something we would love to see implemented for Cirrus Runners. They give you up to 64 concurrent runners, but they charge you per execution time. It might be not as cost-effective, but that gives you more freedom towards parallelising your checks. For most, feedback time is most important in a workflow.
2. Lack of pre-setup simulators and platforms. Downloading and setting up simulators on fresh images will increase setup time. GH images are almost perfect, but they are also heavy.

Hope that helps!

**Comment by fkorotkov** [comment]
@dniHze thank you for the feedback!

For the 1st point we have Cirrus CI's [`macos_insance`s](https://cirrus-ci.org/guide/macOS/) where we have per-second billing with unlimited parallelism. With Cirrus Runners we are experimenting with a different pricing model since it's more familiar for mobile teams and it's easier to project your spending for management. 

I would also like to hear about the 2nd point and things you are missing from the standard image? We deliberately tried to start lean and slowly grow the images. The GitHub provided images seemed too overloaded for us and it seemed unreasonable to try to replicate it.

**Comment by fkorotkov** [comment]
We are not proceeding with the Nomad option since we found some blockers and in general setup was too complex and not future proof  for things like USB device passthrough and similar. Closing this issue in favor of https://github.com/cirruslabs/tart/issues/372
