### ISSUE TITLE
support listing running VMs and stopping VMs from the command line

### ISSUE THREAD

**Issue by naikrovek** [cirruslabs/tart#203]
Hi,

Currently I can `delete` a VM while it's running which is probably going to result in some "we don't know what will happen, there" behavior, so I'd like to know that a VM isn't running before I delete it.

can you add a `tart running` or `tart list running` command, if that's possible?

Alternately, or _perhaps additionally_, have an option to force stop a VM so I can make sure a VM is stopped before I delete it.

I can handle all of this myself in this script that I'm working on, and I imagine that I'm not the only person who would like these things, so I am asking here.  If I knew anything about Swift I would contribute this code myself.

And just so I'm being clear:  You don't have to do any of this, I'm not demanding anything, and I am extremely thankful for what I already have in this tool, these are suggestions and things I hope to see, not demands of any kind.  Thank you.

**Comment by fkorotkov** [comment]
We are specifically trying not to store any information or share state between `tart` invocations and therefore it will be hard to have an accurate state of a VM.

But I'm wondering if something like reusing `tart ip` will work for your use case:

```shell
ping -c 1 $(tart ip ventura-base)
```

In this case if a VM is pingable than it's definitely running but if it's not there might be a small chance that it's booting or shutting down.

**Comment by naikrovek** [comment]
yeah i was using `ps | grep -v grep | grep tart` to get an idea of what was running.  that’ll continue to work just fine.

thank you.

**Comment by barkingfoodog** [comment]
Listing instances and controlling shutdown is something Vagrant could do for you if/when hashicorp/vagrant#12760 is completed.
