### ISSUE TITLE
Move location of VM's to external drive?

### ISSUE THREAD

**Issue by magnusviri** [cirruslabs/tart#221]
Is it possible to move the VM images to an external drive? I just tried symlinking ~/.tart to an external drive and it gives me an error when I try to create a VM.

**Comment by edigaryev** [comment]
> I just tried symlinking ~/.tart to an external drive and it gives me an error when I try to create a VM.

You can use `TART_HOME` environment variable to define a new home for Tart VMs and cache.

**Comment by magnusviri** [comment]
Thanks!
