### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by magnusviri** [cirruslabs/tart#222]
I just made an issue regarding moving the images to an external drive. I guess tart is using the system cache, which is on the drive still. It filled my hard drive (250 GB).

```
Error Domain=NSCocoaErrorDomain Code=640 "“disk.img” couldn’t be copied to “DA30BDDE-FD5B-4469-ADD8-9E5454BDFEC8” because there isn’t enough space." UserInfo={NSSourceFilePathErrorKey=/Volumes/autopkg/tart/vms/monterey-base/disk.img, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/m9/pqzn80q548z2419lljbgydh40000gp/T/DA30BDDE-FD5B-4469-ADD8-9E5454BDFEC8/disk.img, NSFilePath=/Volumes/autopkg/tart/vms/monterey-base/disk.img, NSUnderlyingError=0x60000236ed90 {Error Domain=NSPOSIXErrorDomain Code=28 "No space left on device"}}
```

**Comment by edigaryev** [comment]
It seems that this is due to temporary directory's usage, which is used to guarantee atomicity for some operations.

Can you list some steps to reproduce your situation? I.e. which tart commands are you running (I assume `tart clone`?) and on which images (mostly interested in their sizes on disk).

**Comment by magnusviri** [comment]
This is a condensed history.

```
brew install cirruslabs/cli/tart
tart clone ghcr.io/cirruslabs/macos-monterey-base:latest monterey-base
```

Here I notice I don't have enough hard drive space

```
mv .tart /Volumes/autopkg/tart
```

I tried symlinking and cloning again but it failed. I set the env var

```
tart clone ghcr.io/cirruslabs/macos-monterey-base:latest autopkg
tart list
```

And this is my VM list

```
local	monterey-base
oci	ghcr.io/cirruslabs/macos-monterey-base@sha256:309b7466f23049e4594c4e9a6370e4e5906796a9a3c210ce1b8ad448d8da27ff
```

Here's the condensed output of ls -lRh.

```
/Volumes/autopkg/tart/cache/OCIs/ghcr.io/cirruslabs/macos-monterey-base/sha256:309b7466f23049e4594c4e9a6370e4e5906796a9a3c210ce1b8ad448d8da27ff:
total 58659328
-rw-r--r--  1 james  staff    28G Sep  1 10:28 disk.img

/Volumes/autopkg/tart/vms/monterey-base:
total 58659328
-rw-r--r--  1 james  staff    28G Sep  1 10:28 disk.img
```

**Comment by edigaryev** [comment]
1. Do I understand correctly that you have less than 28 GB of space on your main disk?
2. At the point where you show the "And this is my VM list" excerpt, which Tart CLI action results in the `No space left on device` error?

**Comment by magnusviri** [comment]
Yes. I'm trying to figure out what happened to this computer. I'm pretty sure it had at least 50 GB free before I started playing with tart. Just looking at the usage says I've only used 130 GB, so something is using 120 GB and it isn't in any of the usual spots (all the places visible in the Finder). I'm guessing it's in /var/folders.

**Comment by magnusviri** [comment]
`tart clone ghcr.io/cirruslabs/macos-monterey-base:latest autopkg` resulted in no space.

**Comment by magnusviri** [comment]
Indeed, there are 2 x 28GB disk.img files in /var/folders/ in my users' temp directories. I just removed them and now I've got 84 GB available. I'm still missing some space but I think this is certainly a bug.
