### ISSUE TITLE
add option to specify which NAT subnet VMs should use.

### ISSUE THREAD

**Issue by naikrovek** [cirruslabs/tart#235]
My employer uses the 192.168.0.0/16 subnet for a very small amount of their own stuff, which breaks IP routing to tart VMs because there is a default route for that network while on the corporate LAN or VPN.  Being able to specify a subnet and network mask to use for NAT would help a lot in situations like this.

In addition, an option to use bridged networking instead of NAT would also be useful, though probably not for me.  This would be a thing to do while you're working around in the networking configuration stuff, I imagine.  I don't need to use bridged networks while at work, but at home this would be useful.

Thank you.

**Comment by raven** [comment]
Just noting that bridging using `VZBridgedNetworkDeviceAttachment` [requires](https://developer.apple.com/documentation/virtualization/vzbridgednetworkdeviceattachment) the `com.apple.vm.networking` entitlement, which is only available [upon request](https://developer.apple.com/forums/thread/656411).

**Comment by naikrovek** [comment]
ok well skip the bridged networking thing, then.  that seems nuts, but I am new to Apple-land.

**Comment by raven** [comment]
I'm in the same boat with our work VPN modifying routes making 192.168.0.0/16 not usable. Keen to see what can be done in that area of specifying custom subnets. Does the `tart run --with-softnet` work for your use case?

**Comment by magnusviri** [comment]
Requesting the entitlement shouldn't be hard. I wanted bridged networking bad enough that I'd volunteer to do it if I was in a position. I'm pretty sure it has to come from people in Cirrus labs though.

**Comment by naikrovek** [comment]
> I'm in the same boat with our work VPN modifying routes making 192.168.0.0/16 not usable. Keen to see what can be done in that area of specifying custom subnets. Does the `tart run --with-softnet` work for your use case?

I've not tried this, because it did not seem to have a name relating to what I needed.  I also don't know what "softnet" is in general, being new to Apple stuff.

I see the associated PR and I had no idea it was this simple.  Thank you.
