### ISSUE TITLE
Log important events

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/tart#239]
[Like this one](https://github.com/cirruslabs/tart/blob/f38b1aed9d7436dbc0d5721f5eed344d9f7a64aa/Sources/tart/VMStorageOCI.swift#L157-L167), to `$TART_HOME/tart.log`, for example.

Logging libraries:

* https://github.com/apple/swift-log
* https://github.com/sushichop/Puppy

**Comment by fkorotkov** [comment]
Will help to deal with suspicious like #240. We should log things like why a prunning or gc process started.
