### ISSUE TITLE
tart ip command excessive CPU

### ISSUE THREAD

**Issue by saracen** [cirruslabs/tart#249]
For CI, where a host will run many unique VMs, the DHCP leases file can get to be quite large.

When polling for an ip with `--wait 300`, this command can use a lot of CPU as the sleep (https://github.com/cirruslabs/tart/blob/0.28.2/Sources/tart/Commands/IP.swift#L51) is currently 1ms.

I haven't yet tested this, but I'm guessing this could be changed to 0.5s - 1s and reduce the cost of polling.

**Comment by fkorotkov** [comment]
My bad! Human error of conversion. 😅
