### ISSUE TITLE
Cannot push to Sonatype

### ISSUE THREAD

**Issue by iamszabo** [cirruslabs/tart#252]
First of all, thanks for the amazing tool.

I'm having an issue to upload the blobs to a private Sonatype registry which also supports OCI.
- Chunk size is set to 0.
- Config upload is successful
- When it tries to upload the first blob on the PUT request, the upload itself goes through but the response is the following:

```
UnexpectedHTTPStatusCode(when: "pushing blob (PUT) to https://private.repo.com/v2/monterey-xcode/blobs/uploads/yyyyyyy", code: 400, details: "{\"errors\":[{\"code\":\"BLOB_UPLOAD_INVALID\",\"message\":\"blob upload invalid\",\"detail\":\"Invalid docker content v2/-/blobs/sha256:xxxxxxxx\"}]}")
```

I tried to use chunk size 5, the issue is the same.

Any idea what can can be the issue or how to investigate it further?

**Comment by fkorotkov** [comment]
Interesting. I did some quick googling around "Invalid docker content" and people seems having issues with so called "content type validation". We don't have hands on experience with Sonatype but it seems there is a way to turn this validation off. Could you please take a look and try to disable it to see if that helps?

**Comment by iamszabo** [comment]
@fkorotkov I've found that issue previously and tried to play with the settings but didn't resolve the issue.
Probably it will be an issue on the Sonatype end, so I've raised a ticket on their system.

**Comment by fkorotkov** [comment]
If it's a public issue please add a link here! 😉 And in any case please keep us updated.

**Comment by letiemble** [comment]
Hello,

I am facing the same issue with a private Nexus OSS repository. The error message is much more explicit:

```
Error: UnexpectedHTTPStatusCode(when: "streaming blob to https://XXXX/v2/macos-vanilla-ventura/blobs/uploads/d66efc8c-ff8b-4b48-824b-b2944a741347", code: 400, details: "{\"errors\":[{\"code\":\"BLOB_UPLOAD_INVALID\",\"message\":\"blob upload invalid\",\"detail\":\"Content type could not be determined: v2/-/blobs/sha256:c33d6eb6f98eeb47077a0eaafad805a05ff7a23c20080fb90d3ea629f3dd6b94\"}]}")
```

Turning the content type validation on the repository would do the trick, but I would prefer a solution where the blobs are pushed with a valid content type (cf. https://github.com/opencontainers/image-spec/blob/main/media-types.md).

After looking at the source code (https://github.com/cirruslabs/tart/blob/f68297097e5f043191b52302fed17f7ff87ce972/Sources/tart/OCI/Registry.swift#L187), it seems that no `Content-Type` header is sent when uploading a blob:
- Is this a reason for that?
- What would be the appropriate content type to use for blobs?

**Comment by edigaryev** [comment]
> In `Registry.swift`, the `Content-Type` header sent is `application/octet-stream`

>Is this a reason for that?

This is what [specification requires us to use](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#single-post).

Are you using the latest version of Nexus OSS? It seems pretty weird that they try to validate blob content-types (as opposed to manifest content types).

**Comment by letiemble** [comment]
I am not using the latest version.

AFAIK, nothing in the recent release notes indicates that the issue has been fixed.
After checking the specification, it seems that Nexus OSS is too strict regarding the content type of blobs.

Thanks for taking some time to look at it.
