### ISSUE TITLE
Abnormally slow uploads to S3?

### ISSUE THREAD

**Issue by remarkov** [cirruslabs/tart#258]
Hey,

Not 100% sure but it seems we are observing a really weird bug and all tests we've done narrows it down specifically to Tart.
For some reason if we do an upload to an S3 bucket from a VM running under Tart we get significantly slower upload speeds rather than if we do the same without Tart, be it another virtualization framework or just a bare metal host in the same network environment. It is very easy to reproduce the issue with the following commands and observing the transfer speed:

```
$ aws s3api create-bucket --bucket tart-test
$ dd if=/dev/urandom of=sample.txt bs=8M count=100
$ aws s3 cp sample.txt s3://tart-test
```

For some strange reason the issue occurs only with S3 uploads, all other data transfer tools we tried like `scp`, `rsync` and `gcloud storage` were not affected and showed proper transfer speeds.

To make sure we don't have any bandwidth limitations on Tart VMs I ran `networkQuality -v` on a fresh created VM in Tart:

```
Upload capacity: 233.447 Mbps
Download capacity: 879.506 Mbps
Upload flows: 20
Download flows: 12
Responsiveness: High (1835 RPM)
Base RTT: 14
Start: 9/28/22, 5:12:05 PM
End: 9/28/22, 5:12:21 PM
OS Version: Version 12.6 (Build 21G115)
```
 ... and on a random ESXi VM:

```
Upload capacity: 191.802 Mbps
Download capacity: 842.574 Mbps
Upload flows: 20
Download flows: 12
Responsiveness: Medium (824 RPM)
Base RTT: 14
Start: 9/28/22, 17:10:41
End: 9/28/22, 17:10:57
OS Version: Version 12.6 (Build 21G115)
```

But the test above showed completely different upload speeds.
On ESXi:

```
$ aws s3 cp sample.txt s3://m1-test
Completed 634.2 MiB/800.0 MiB (63.1 MiB/s) with 1 file(s) remaining
```

and on Tart:

```
aws s3 cp sample.txt s3://m1-test
Completed 24.8 MiB/800.0 MiB (1.3 MiB/s) with 1 file(s) remaining
```

At first I thought that it can be related to Apple Virtualization Framework so I made the same test on an Anka VM but it showed the same speeds as on ESXi machine. I really have no idea what can cause that but I hope together we can find the truth. If you need any further details or any tests I'm happy to assist.

Btw, I'm on latest Tart version 0.29.0 and macOS 12.6 if that matters.

**Comment by edigaryev** [comment]
> For some reason if we do an upload to an S3 bucket from a VM running under Tart we get significantly slower upload speeds rather than if we do the same without Tart

Does this occur to you using other `Virtualization.Framework`-based solutions like the UTM?

Currently in Tart, by default, the networking is fully provided and handled by the `Virtualization.Framework`. And in `Virtualization.Framework`, there's literally no knobs to play with to influence the networking, you just ask for a NAT (shared) interface and that's it.

**Comment by remarkov** [comment]
> Currently in Tart, by default, the networking is fully provided and handled by the Virtualization.Framework

This is exactly what I was thinking and that's why I tested with Anka VM which as I understand also uses `Virtualization.Framework`. Surprisingly in Anka VM I've got good upload speed. I simply don't understand how it is possible but Anka VM was running even on the same host as the Tart VM I've been using for tests. Do you have any ideas what other debugging steps we can take? Can you maybe perform similar tests on your side? Please note it has to be specifically AWS CLI.

**Comment by fkorotkov** [comment]
It's pretty weird and interesting that it's specifically AWS CLI. Anka folks might have brought their network stack as well and maybe don't use `VZNATNetworkDeviceAttachment` but I'm not sure. It will be interesting to see if `tart run --with-softnet` changes the picture. @edigaryev fine tuned Softnet :chefs-kiss:. Also it would be interesting to see if Ventura VMs perform the same since during WWDC Apple folks claimed to fine tune the OS for virtualization (I guess for their Xcode Cloud).

**Comment by remarkov** [comment]
> It's pretty weird and interesting that it's specifically AWS CLI.
True! I couldn't believe myself before I made 10+ tests in various conditions. I will now go ahead and try both things you mentioned, will post back the results later today.

**Comment by fkorotkov** [comment]
Quick Googling showed that people do have issue with S3 uploads and it's ability to fully saturate the network. I wonder if you can also add config like this one https://github.com/aws/aws-cli/issues/6736#issuecomment-1049231638. Maybe the new `crt` client is faster. In our experience with AWS Java SDK the CRT clients did make a difference.

**Comment by remarkov** [comment]
I tried to experiment with various aws options to no avail, didn't try the `crt` one though. But it remains totally weird that it works perfectly fine without any tuning on Anka, ESXi and bare metal hosts. But I'll try that anyway, just curious.

**Comment by remarkov** [comment]
Oh, I just tried to remove the crt client from the config but left all the rest

```
[default]
s3 =
    max_concurrent_requests = 3000
    target_bandwidth = 100Gb/s
```

and finally got the full upload speed! But only on a bigger size file, e.g. 800 MB. That somewhat makes sense as when I test on a small 8 MB file without any config changes I get the speed ~150 KiB/s and if I do the same on a bigger, 80+ MB file I get the speed of 1.5 MiB/s. The default chunk size for AWS CLI is 8 MB so it makes total sense that 10 threads in parallel give 10x speed. And now with increased number of concurrent requests it was able to reach the full bandwidth capacity of about 65 MiB/s.
But unfortunately the smaller files are still critically slow at speeds ~150 KiB/s because they go in single thread. As far as I recall, the minimum chunk size is 5 MB so at best we will get ~300 KiB/s which is still very far from what we get on ESXi/Anka VMs. The main mystery for now is why single thread in Tart VMs get limited to ~150 KB/s while it is not the case, let's say in Anka.

**Comment by remarkov** [comment]
Just FYI: I also tried to do the same test locally on my M1 laptop and a VM created in [VirtualBuddy](https://github.com/insidegui/VirtualBuddy) and the transfer in AWS CLI was also really slow. It turns out there is indeed something in the Apple Virtualization Framework and you were right that Anka does not seem to use the native networking. They also have two different options for network controller: `anet` and `virtio-net`. Out of curiosity I tried both and none of them have any issues with transfer speed.

**Comment by edigaryev** [comment]
@remarkov could you please try reproducing the issue by running the Tart [with the software networking](https://github.com/cirruslabs/softnet) enabled?

**Comment by remarkov** [comment]
@edigaryev that's it, it works! The Softnet itself seems to be a great thing and the only reason we didn't use it before is that we didn't know it exists. Better VM isolation and DHCP exhaustion are another two issues I had concerns about thus this simple change will fix **three** issues at once, that's definitely a win! Thanks a lot for the hint!

I guess it is ok to close this issue for now as we definitely proven that it is not related to Tart itself but to the virtualization platform but nonetheless you guys still got a working solution for that. Bravo!

**Comment by fkorotkov** [comment]
@remarkov glad it finally worked out for you! We are also switching to only running with softnet so it's great to hear that it actually faster. 

BTW please consider becoming a GitHub sponsor from all the savings on the Anka license. 😉

**Comment by mikhail-tokarev** [comment]
> BTW please consider becoming a GitHub sponsor from all the savings on the Anka license. 😉

we will discuss it internally 😀👍however thank you and all team for assistance
