### ISSUE TITLE
Running an Intel macOS VM on a macOS device equipped with Apple silicon?

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [cirruslabs/tart#259]
Hey folks, is it possible to create a VM with a macOS Intel on a macOS with e.g. M1? I saw https://github.com/cirruslabs/tart/issues/67, however, I am not sure if anyone asked about having an "Intel macOS VM" on an M1 device? So Tart would be run on a M1 host, but the VM produced would be an Intel VM (so that you can build things inside as if you are running a macOS Intel machine). Hope this makes sense. Thanks!

**Comment by fkorotkov** [comment]
Unfortunately this is not supported by `Virtualization.Framework` and therefore we won't be able to support it in Tart.

**Comment by alexey-tereshenkov-oxb** [comment]
I see, thanks @fkorotkov! So I guess our only option is to run things in emulation with Rosetta (i.e. `arch -x86_64`) inside a VM.

**Comment by fkorotkov** [comment]
Yeah, unfortunately. 😪
