### ISSUE TITLE
Running Tart on Scaleway M1s

### ISSUE THREAD

**Issue by sanieldalib** [cirruslabs/tart#261]
Hey there! Thanks for the continued work on Tart, it's been a joy to use and adopt into my dev workflow.

I've been attempting to run Tart on Scaleway's Apple Silicon service which provides a bare metal Mac Mini (https://www.scaleway.com/en/hello-m1/). However, I haven't been able to get the network to work from inside the VMs, despite ensuring both Internet Sharing and Airplay Reciever is disabled as suggested here: https://github.com/cirruslabs/tart/issues/255.

I've been able to run VMs just fine on AWS M1s so I must be missing something in the Scaleway configuration. Any clues as to where to look? 

Additionally, I tried the VirtualBuddy app (https://github.com/insidegui/VirtualBuddy) in both NAT and Bridged modes with no luck for either network configuration.

**Comment by fkorotkov** [comment]
We have no idea what's going on there. @edigaryev tried to investigate it a while back but with no luck. If you have an account with them maybe it's worth asking what they might be doing differently from everyone else.

**Comment by fkorotkov** [comment]
@edigaryev [found a workaround](https://twitter.com/edigaryev/status/1578086688957530112):

```bash
launchctl remove org.macports.fail2ban
```

We've contacted Scaleway support about the issue with [fail2ban](https://github.com/fail2ban/fail2ban).

**Comment by edigaryev** [comment]
>`launchctl remove org.macports.fail2ban`

It also seems that after reboot this workaround gets reverted.

To make it permanent, you can move `org.macports.fail2ban.plist` file somewhere else out of `/Library/LaunchDaemons` directory.

**Comment by sanieldalib** [comment]
Thank you for taking a look! I haven't been able to get the workaround to work despite trying the following:
- `launchctl remove org.macports.fail2ban`
- Deleting the `org.macports.fail2ban.plist` file
- Uninstalling ` fail2ban` using `/opt/local/bin/port`

Anything else it might be? I've tried restarting a number of times as well as creating a fresh clone of the base image 😢

**Comment by edigaryev** [comment]
> Anything else it might be?

Actually, I've just found another PF breaker service:

```
% cat /Library/LaunchDaemons/scw-pf.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>scw-pf</string>
    <key>StartInterval</key>
    <integer>60</integer>
    <key>ProgramArguments</key>
    <array>
        <string>pfctl</string>
        <string>-ef</string>
        <string>/etc/pf.conf</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```

It reloads all PF rules every 60 seconds, and this results in wiping out all of the `com.apple.internet-sharing` anchors that are needed for NAT networking to function properly.

Consider removing it (`launchctl remove scw-pf`) and moving the `scw-pf.plist` file somewhere else out of `/Library/LaunchDaemons` directory.

**Comment by sywesk** [comment]
@edigaryev That might be the true issue, removing fail2ban won't do anything as it's only reading logs and managing a pf table.

**Comment by edigaryev** [comment]
> @edigaryev That might be the true issue, removing fail2ban won't do anything as it's only reading logs and managing a pf table.

Yeah, I guess it was just a somewhat large time window (60 seconds) that gave an impression of resolving this by removing fail2ban.
