### ISSUE TITLE
Delay for first VM created getting an IP when softnet enabled

### ISSUE THREAD

**Issue by saracen** [cirruslabs/tart#263]
I opened https://github.com/cirruslabs/tart/issues/253 not too long ago describing an issue where a VM was taking a long time to get an IP.

Whilst the dhcp lease file not existing fix is a large improvement, there's still a significant delay in an IP being given to a VM. This only appears to be the case for the very first VM created on a fresh AWS instance, and might only be when `softnet` is enabled. 

At some point, it all begins working. This might be influenced by first creating a VM without softnet? In either case, maybe 20-40 minutes later, all subsequent VMs get an IP address immediately from that point forward.

Any idea what I might try to fix this delay?

Thank you

**Comment by fkorotkov** [comment]
Do you mean that you wait for 20-40 minutes for the dhcp lease file to be created? 

What are the steps for reproduce? You create an instance and immediately trying to to run a VM? Do you use a custom AMI or a public one?

**Comment by saracen** [comment]
I built my own image based off of AWS's Monterey 12.5.1, this included tart, pre-pulled the base image and I have custom application that abstracts calls out to tart.

To rule out a problem with my software, I just started an instance and only used tart commands:

```
tart clone monterey-base nesting-vh616uqe
tart run nesting-vh616uqe --no-graphics --with-softnet &
tart ip nesting-vh616uqe --wait 3600
```

The VM got an IP address after about 8 minutes this time. After that, VMs get an IP in about 20s.

I started a brand new AWS instance using an image without any modifications (`ami-055fd9d08b7b16165`), but in this case, I had to pull an image which took about 40 minutes... after which, running the same tart commands as above gave me an IP instantly.

Unfortunately, I have to wait a really long time between tests (AWS MacOS provisioning time is long). I don't know whether there's something wrong with my modified image, or that the unmodified one only worked because it was up 40 minutes cloning from the package registry...

I'll continue to test and report back. I take it you've not experienced this with CirrusCI? Do you use AWS?

**Comment by fkorotkov** [comment]
We don't use AWS for Macs since it's quite expensive and it's cheaper for us to over provision instances with another provider than try to auto-scale instances that way. Plus we don't integrate with any other AWS service except S3.

I'm not quite sure what's going on there and it's hard for us to debug. If you have a sizable contract with AWS and using their M1 Minis you might know Suvi. Say "Hi" to her in that case! They might help to debug the issue. 😅

I wonder if to workaround the issue you could try to do the first cold run of a Tart VM upon creation of your AMI... That way it seems the lease file will be pre-created. Maybe what ever shenanigans is happening there won't affect such pre-warmed instances. 🤔

**Comment by saracen** [comment]
It's still bit of a guess at this point, but I think that first VM always just takes a little bit longer, and if you cancel it, as my software was doing (3m timeout), nothing progresses and after a retry you're no better off. At this point I'd usually SSH to the machine and wait long enough for a VM to come up and then everything would be working.

I'll try starting a VM in the creation of the AMI and that might help. Otherwise, if it is just this initial delay and I need more patience, I can live with that 👍 

There's a few other issues I'm encountering at the moment:

- Getting `failed to do I/O on VM socket: No buffer space available (os error 55)` if I don't immediately SSH to the VM. If I get this error, networking seems to just stop working.
- If I start two VMs at pretty much the same time, they both get IPs fast enough, but I can only then SSH to one of them immediately, the other takes some time.

Unless anything immediately springs to your mind about these, I'll collect more data and then open issues if need be.

**Comment by saracen** [comment]
Running a VM in the creation of my AWS AMI appears to have helped with this delay in my current tests. 👍 

I'll open separate issues for the other problems I've experienced.

**Comment by edigaryev** [comment]
> Running a VM in the creation of my AWS AMI appears to have helped with this delay in my current tests. 👍

I wonder if https://github.com/cirruslabs/softnet/pull/10 fixed this problem also 🤔
