### ISSUE TITLE
Unexpected 201 when uploading to ECR with --chunk-size

### ISSUE THREAD

**Issue by adrienkohlbecker** [cirruslabs/tart#273]
Hi!

It looks like setting a `--chunk-size` is throwing errors when uploading to ECR. If I understood correctly, this should be set to more than 5 due to S3's multipart upload API limitations. Is there a value you recommend for best performance? 
In any case, it looks like the upload starts, some data is pushed, and then it receives an unexpected HTTP 201 and bails out. 

```
$ tart push --chunk-size 10 repo ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/macos/repo:tag
pushing repo to ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/macos/repo:tag...
pushing config...
pushing disk... this will take a while...
2%
UnexpectedHTTPStatusCode(when: "streaming blob to https://ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/v2/macos/repo/blobs/uploads/b49173cd-0760-4e3b-9905-ba3cd0e42cca", code: 201, details: "")
```

**Comment by edigaryev** [comment]
Hello Adrien!

Unfortunately it seems that the Amazon Elastic Container Registry is violating both of the container specifications, which only allow returning `HTTP 202` for `PATCH` requests:

* https://github.com/opencontainers/distribution-spec/blob/main/spec.md#endpoints
* https://docs.docker.com/registry/spec/api/#patch-blob-upload

Is there a reason why are you using a chunked upload (and not a default method) in the first place?

**Comment by adrienkohlbecker** [comment]
Mostly trying to increase performance when pushing and pulling. Those concerns are not directly related to this issue though so I opened #279 to discuss them separately.

Is ECR's breach of the spec something that can be worked around? If not maybe adding a warning that this argument is not supported on ECR to the `--help` output could be a quick improvement to tart.
