### ISSUE TITLE
Password-stdin does not work

### ISSUE THREAD

**Issue by mortidlo** [cirruslabs/tart#289]
Hi, 

I wanted to connect to our internal OCI registry (Harbor) from our GitLab CI/CD and push image there. For that I wanted to use `echo "$PASSWORD" | tart login registry.host.com --username user --password-stdin` but it does not work. I was getting this error `invalid credentials: AuthFailed(why: "received unexpected HTTP status code 401 while retrieving an authentication token", details: "")` 

On the other hand when I provided my credentials interactively using stdin it works. So I start to debug this issue and find out that there is a newline at the end of the string. I tried to fix the code as showed bellow (I am comming from Python world so this change may look silly). When I compile it it immediately fixed the issue.

<img width="1275" alt="Snímek obrazovky 2022-10-27 v 16 08 15" src="https://user-images.githubusercontent.com/112080712/198309685-ba077922-2dfe-466d-825f-837c95a9fbc6.png">

Thanks for looking at this.

**Comment by edigaryev** [comment]
Does adding `-n` to `echo` invocation:

```
echo -n "$PASSWORD" | tart login registry.host.com --username user --password-stdin
```

...fixes the issue?
