### ISSUE TITLE
tart ip linuxvm : UninitializedVMDirectoryError()

### ISSUE THREAD

**Issue by cattyhouse** [cirruslabs/tart#290]
```sh
tart create linuxvm --linux --disk-size 20
tart run linuxvm --disk ~/vm/arch/archlinuxarm-2022.10.16-aarch64.iso
# doing installation
tart run linuxvm --no-graphics
```
after the linuxvm running for **a while**
````
tart ip linuxvm
````

shows: 

````
UninitializedVMDirectoryError()
````
**however, ssh/ping still works**, it's just `tart ip` return error code 1 with above message, shutdown/start, or reboot same error.

but `tart clone linuxvm linuxvmnew`, then shutdown `linuxvm`, start it, `tart ip` works, after that `tart delete linuxvmnew`, this works only for a while, then, that error shows again.

**Comment by edigaryev** [comment]
Hello Justin!

Unfortunately, I fail to reproduce the same issue in a time window of half an hour.

Moreover, the `UninitializedVMDirectoryError()` only appears when VM is missing one or more of its 3 files:

```
% ls -l ~/.tart/vms/linuxvm 
total 8957616
-rw-r--r--  1 edi  staff          255 Oct 28 08:59 config.json
-rw-r--r--  1 edi  staff  20000000000 Oct 28 09:32 disk.img
-rw-------  1 edi  staff       131072 Oct 28 08:59 nvram.bin
```

Can you check that this is the case?

**Comment by cattyhouse** [comment]
@edigaryev 

aha, i am sorry, i used the name from my ssh_config `Host linuxvm` to `tart ip`, i should be using the name from `tart list`, stupid. So sorry for your time.
