### ISSUE TITLE
Filter tart list

### ISSUE THREAD

**Issue by tomjn** [cirruslabs/tart#299]
Tart list currently displays both local and OCI:

```swift
      displayTable("local", try VMStorageLocal().list())
      displayTable("oci", try VMStorageOCI().list().map { (name, vmDir, _) in (name, vmDir) })
```

It should be possible to filter to show one or the other if desired

**Comment by edigaryev** [comment]
Resolved by https://github.com/cirruslabs/tart/pull/349.
