### ISSUE TITLE
Linux Examples

### ISSUE THREAD

**Issue by tomjn** [cirruslabs/tart#301]
It would be helpful to have more Linux examples in the readme, _in particular_ examples of mounting folders into specific locations, as well as Linux VMs that aren't created from scratch

**Comment by edigaryev** [comment]
> as well as Linux VMs that aren't created from scratch

Can you clarify which examples you'd like to see? Currently, the process for Linux VMs is the same as with macOS VMs.

**Comment by tomjn** [comment]
Examples that include mounted folders specifically, but also to ensure that every MacOS example has a linux equivalent, even if it's just to demonstrate that they're the same

**Comment by tomjn** [comment]
Also, arbitrary mounts. For example by default Vagrant mounts the folder with the vagrantfile to `/vagrant`, I'm unsure how I would achieve something similar with this on Linux without resorting to hardlinks/symlinks to `/mnt/shared/vagrant`. It's likely manual rather than auto-mounting will be needed for that

**Comment by edigaryev** [comment]
> Examples that include mounted folders specifically

This will be addressed by #338.

>but also to ensure that every MacOS example has a linux equivalent, even if it's just to demonstrate that they're the same

Seems very redundant. It would probably would be better to stick with the common sense notion that unless documented, the instructions are the same for both macOS and Linux. What do you think?

>Also, arbitrary mounts. For example by default Vagrant mounts the folder with the vagrantfile to `/vagrant`, I'm unsure how I would achieve something similar with this on Linux without resorting to hardlinks/symlinks to `/mnt/shared/vagrant`. It's likely manual rather than auto-mounting will be needed for that

Most likely using the hard/soft links, yes. Otherwise this seems like an out of scope piece for the documentation, because it does not involve the Tart directly.

**Comment by tomjn** [comment]
> Seems very redundant. It would probably would be better to stick with the common sense notion that unless documented, the instructions are the same for both macOS and Linux. What do you think?

Unless someone actually says they are the same this introduces ambiguity, e.g. are they the same, or is it that those parameters aren't supported on Linux, or is it that they're different but undocumented? Not everybody will interpret things the same, and if something is only mentioned under a MacOS heading it's heavily implied it's a MacOS only feature.

If instead it's a generic section that talks about adding folders to a guest, rather than separate duplicates that are MacOS and Linux specific, then that also does the job without being unnecessarily verbose

> Most likely using the hard/soft links, yes. Otherwise this seems like an out of scope piece for the documentation, because it does not involve the Tart directly.

Not really, this is a common thing to do and not mentioning it implies it's impossible and hides a lot of the semantics. Reduction of ambiguity and assumptions is ideal.

Also keep in mind that if someone is looking at the readme there's a good chance they haven't installed Tart yet and can't see anything that CLI prints in help text. You can't rely on runtime output.
