### ISSUE TITLE
Background Tart Process

### ISSUE THREAD

**Issue by tomjn** [cirruslabs/tart#303]
It would be helpful to add a parameter specifying that the VM should run in a background process. Ideally it could then close either itself or via a `tart stop` command from #298

**Comment by fkorotkov** [comment]
The CLI usage is designed to be daemon-less so consumers are responsible for cleaning VMs. Let's cover that in #305.

**Comment by tomjn** [comment]
@fkorotkov without this `vagrant` providers would likely need to resort to spawning child processes such as `nohup` or `screen` to work around this which complicates things. I'd expect a vagrant provider to handle shutting down the Tart VM via another command. Perhaps by SSH'ing in and shutting down the VM internally, or using something cruder such as `pkill`.

If you're thinking that I mean to ask for a daemon or service, that's not what I was intending at all. Just the existing behaviour, except instead of Tart running and blocking the shell, it instead yields control back.

**Comment by tomjn** [comment]
A note from another issue:

 - how do we tell the difference between a VM that is running, and a VM that is being created? E.g. if Tart hasn't finished starting up the VM yet
 - what's the difference between a VM that's shutdown, and a VM that failed due to an error?

At the moment we only have 2 states assuming we can run the `tart` command async in a child process:

 - the PID we saved references an active process so the VM is probably ok and running
 - the PID no longer references a process so it must have shutdown/stopped, or maybe there was a problem?

We could look at the return value of the `tart` process or its output, but if we want to replicate `vagrant` semantics then this is impossible short of building out some wrapper program that encapsulates `tart` entirely just so we can note down if it failed somewhere

**Comment by fkorotkov** [comment]
Since we introduced `tart stop` in #316 which works by storing a PID... @edigaryev, do you think having `tart run --detach` like asked in https://github.com/cirruslabs/tart/discussions/449 will make sense?
