### ISSUE TITLE
Desktop Application

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#305]
Right now Tart is specifically a CLI tool that is meant to be integrated into some other system or run from a terminal. And Tart is daemon-less, meaning that to stop a VM one need to kill `tart` process.

For more user friendly experience, let's consider creating `Tart.App` with some UI similar to what Parallels has:

<img width="394" alt="Screenshot 2022-11-05 at 8 18 47 PM" src="https://user-images.githubusercontent.com/989066/200148296-a0d5a136-32a6-4a50-a129-d698252b3299.png">

So a user can view a list of VMs, can change config, start and stop them, etc.

**Comment by fkorotkov** [comment]
Just a quick shout out to @vitorgalvao for creating a [Alfredo workflow](https://alfred.app/workflows/vitor/virtual-machines/):

![image](https://user-images.githubusercontent.com/989066/208701011-7a215dd9-34b4-46a4-a5c8-f641dce3e571.png)

**Comment by mafreud** [comment]
Great suggestion! If you use Flutter, I can contribute since I have some experiences of it.
