### ISSUE TITLE
Implement "tart stop" via advisory file locking's PID retrieval mechanism

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/tart#315]
We will need to switch `FileLock.swift` from [`flock(2)`](https://man.openbsd.org/flock) to [`fcntl(2)`-based locking](https://man.openbsd.org/fcntl) and add a method to pick up the `l_pid` member of the `struct flock`.

This will simplify Vagrant plugin development since you won't have to maintain a PID-file anymore, see [Vagrant's QEMU provider](https://github.com/ppggff/vagrant-qemu/blob/ee41622b4bf16e0ac5823d51ccebbc59075a7d02/lib/vagrant-qemu/driver.rb#L166-L176) for example.

Related issues:

* https://github.com/cirruslabs/tart/issues/298
* https://github.com/cirruslabs/tart/issues/300

**Comment by fkorotkov** [comment]
Should we close the other issue and consolidate on this path for the implementation. /cc @tomjn

**Comment by tomjn** [comment]
If we're speaking from an agile POV, this would be a technical ticket and the other would be a story. This looks promising for a number of issues, lets close the other ticket #298
