### ISSUE TITLE
Cache Pruning

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#33]
Right now Tart is saving `*.ipsw` files and remote images pulled via `tart pull` in the cache directory and never deletes anything.

Tart should have a command to prune the caches and remove unused files including remote images that there are no symlinks to.

**Comment by edigaryev** [comment]
Discussed this with @fkorotkov a decided to:

* implement a `tart prune` command that allows to reduce the cache to a specific size or based on a cut-off date
* automatically invoke `tart prune` internally when the result of running `tart pull` will result in lack of free disk space
