### ISSUE TITLE
Linux Arbitrary folder mapping from host to guest

### ISSUE THREAD

**Issue by tomjn** [cirruslabs/tart#340]
To produce a usable vagrant provider there needs to be away to map arbitrary host paths to arbitrary guest paths in Linux.

For example Vagrant maps the project folder on the host to `/vagrant` by default, and lots of projects map a project subfolder to some variation of `/var/www` or `/srv/www` etc. Vagrant can hand a provider a list of host -> guest mappings that could be empty or contain many mappings. This involves a mounting step during the starting of a VM via vagrant where a provider can SSH into a VM to run necessary mounting commands.

**Comment by fkorotkov** [comment]
Closing since it seems the functionality should be implemented in a system that invokes Tart.
