### ISSUE TITLE
`tldr` support

### ISSUE THREAD

**Issue by marc-48k** [cirruslabs/tart#357]
With your blessing I'd like to create an entry for tart over @ https://github.com/tldr-pages/tldr - it's an awesome tool.

**Comment by fkorotkov** [comment]
That sounds awesome! Seems like a very useful addition. 💪

**Comment by marc-48k** [comment]
This was merged into the tldr database yesterday 🎉

**Comment by fkorotkov** [comment]
Sweet! Thank you so much for the help and other contributions! 🙌
