### ISSUE TITLE
Automatically elevate privileges for Softnet

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#358]
The builtin NAT networking in `Virtualization.Framework` is working great in most of the cases but it's a black box and there are a few reported quirks like https://github.com/aws/aws-sdk-ruby/issues/2803 and https://github.com/aws/aws-sdk/issues/469.

[Softnet](https://github.com/cirruslabs/softnet) on the other hand doesn't seem have the same problems. But `softnet` requires `sudo` and after the default `brew intall cirrus/cli/tart` you need to manually change things to make `--net-softnet` working:

```console
$: tart run --net-softnet ventura-base
root privileges are required to run and passwordless sudo was not available
RuntimeFailed(why: "Softnet process terminated prematurely")
```

It will be nice to detect it on the Tart side and prompt for access.

**Comment by tosbaha** [comment]
What are the changes for softnet to work? I can only make it work like below

- `sudo tart run  vm01 --net-softnet` I get an error saying that it can't find VM(obvious)
- I then run the tart without sudo `tart run  vm01 --net-softnet` and it works.

**Comment by olejnjak** [comment]
There is an option to work around this issue which can be considered non-standard and potentially unsafe, but works for CI usage, I'd rather won't do that when used on personal machine.

You can change ownership of softnet binary to root and set SUID bit which will make softnet run always under root.
```
sudo chown roo `which softnet`
sudo chmod +s `which softnet`
```

From now on running tart with `--net-softnet` will work without sudo.
