### ISSUE TITLE
ArgumentParser errors for --... arguments

### ISSUE THREAD

**Issue by remarkov** [cirruslabs/tart#360]
Sorry if I missed some update/announcement, but running v0.36.1 after a fresh install on a new host gives `ArgumentParser` errors for some basic arguments like `help` or `version`:
```
$ tart --version
CommandError(commandStack: [tart.Root], parserError: ArgumentParser.ParserError.versionRequested)

$ tart --help
CommandError(commandStack: [tart.Root], parserError: ArgumentParser.ParserError.helpRequested(visibility: ArgumentParser.ArgumentVisibility(base: ArgumentParser.ArgumentVisibility.Representation.default)))
```

And running tart without arguments returns only `--help`.

Other arguments like `list` or `prune` work fine but again, no help available.
```
$ tart help prune
CommandError(commandStack: [tart.Root, tart.Prune], parserError: ArgumentParser.ParserError.helpRequested(visibility: ArgumentParser.ArgumentVisibility(base: ArgumentParser.ArgumentVisibility.Representation.default)))
```

**Comment by remarkov** [comment]
That was quick! Thanks!

**Comment by remarkov** [comment]
@fkorotkov 
Could be also related to this. `--help` works properly in latest version, but `--version` still has incorrect output:

```
$ tart --version
SNAPSHOT
```

**Comment by edigaryev** [comment]
> @fkorotkov Could be also related to this. `--help` works properly in latest version, but `--version` still has incorrect output:
> 
> ```
> $ tart --version
> SNAPSHOT
> ```

Where have you obtained the Tart binary?

It works for me when installed from Homebrew:

```
% tart --version
0.36.2
```

**Comment by remarkov** [comment]
Indeed, I accidentally used just `brew install tart` instead of `brew install cirruslabs/cli/tart`. This is reproducible (on a clean host) so maybe you will be interested to have a look at this.

```
$ brew install tart
==> Fetching tart
==> Downloading https://ghcr.io/v2/homebrew/core/tart/manifests/0.36.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/tart/blobs/sha256:c62fbcbdd94c15a9ed978f538781ca349f1c66226f669005fda6e2b719256009
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:c62fbcbdd94c15a9ed978f538781ca349f1c66226f669005fda6e2b719256009?se=2022-12-20T10%3A50%3A00Z&sig=Qn1nYx9
######################################################################## 100.0%
==> Pouring tart--0.36.2.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/tart/0.36.2: 8 files, 20.4MB
==> Running `brew cleanup tart`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
$ tart --version
SNAPSHOT
```

Works fine if installed from `cirruslabs/cli/tart` though.

**Comment by fkorotkov** [comment]
Another point to remove the "official" formula #317

**Comment by fkorotkov** [comment]
Created https://github.com/Homebrew/homebrew-core/pull/118595
