### ISSUE TITLE
Using ventura host and monterey guest run option --dir does not work 

### ISSUE THREAD

**Issue by bldrvnlw** [cirruslabs/tart#362]
Tried the run with --dir option from a ventura host to mount a directory in the monterey guest but there was no My Shared Files directory.

To reproduce used ventura-base image (from ghcr.io) this works and "My Shared Files/mounted_dir>" is there. Using the monterey-base as guest doesn't give an error but the "My Shared Files" directory does not exist.

The README https://github.com/cirruslabs/tart#mounting-directories indicates that this should work with a ventura host. There is no mention that the guest must be ventura.  I assumed that this meant that it would work with the monterey guest but that doesn't seem to be the case. Or is there a trick to getting it working?

**Comment by fkorotkov** [comment]
No, unfortunately guest also needs to be Ventura or newer.

There is a mention that `the guest VM needs to run macOS 13.0 (Ventura) or newer` in the end of the [macOS section](https://github.com/cirruslabs/tart#accessing-mounted-directories-in-macos-guests).
