### ISSUE TITLE
Info: Alfred Workflow for tart

### ISSUE THREAD

**Issue by vitorgalvao** [cirruslabs/tart#365]
This issue is informational, so close at will. I thought you might be interested in it following https://github.com/cirruslabs/tart/issues/208.

I’ve built an [Alfred Workflow for controlling `tart` virtual machines](https://alfred.app/workflows/vitor/virtual-machines/). Creating VMs is still done via the command-line, but after setting up I exclusively interact with `tart` via Alfred.

**Comment by fkorotkov** [comment]
Very nice! Thank you for mentioning it! It's a great alternative until we have some fancy UI via #305
