### ISSUE TITLE
tart list doesn't handle unknown parameters and crashes

### ISSUE THREAD

**Issue by tomjn** [cirruslabs/tart#371]
If you pass in `tart list --q` by accident, rather than displaying the help text, it crashes:

```sh
❯ tart list --q           
CommandError(commandStack: [tart.Root, tart.List], parserError: ArgumentParser.ParserError.unknownOption(ArgumentParser.InputOrigin.Element.argumentIndex(1), ArgumentParser.Name.long("q")))
```

**Comment by edigaryev** [comment]
This was already addressed in https://github.com/cirruslabs/tart/pull/367, the fix will be available in the [Tart `0.36.3` version](https://github.com/cirruslabs/tart/releases/tag/0.36.3).
