### ISSUE TITLE
Tart Clustering

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#372]
Right now Tart runs on a single machine where you can only run at most two virtual machine at a time. It will be great to provide a solution that can cluster bunch of Apple Silicon hardware together and allow to manage VMs onto them with ease. 

We’ve tried to experiment with the [Nomad plugin](https://github.com/cirruslabs/tart/issues/201) as well as a [virtual kubelet for k8s](https://virtual-kubelet.io/) for Kubernetes. In both cases we found some blockers and in general very high complexity of a setup.

We decided on building our own solution with a simple setup and tailored for running macOS VMs. We call it internally Orchard. For the initial release of Orchard we'll focus on API-only use cases with the following endpoints:

1. Schedule a VM to start (provide priority, optional startup/shutdown script with a restart policy and an optional TTL).
2. Status for a VM with logs
3. Stopping a VM

This is a tracking issue for the initial release we'll move conversation/feature requests and feedback into a separate repository and will work from there.

**Comment by barkingfoodog** [comment]
Very interested to watch this progress. And fantastic name, BTW!

**Comment by dinvlad** [comment]
> Right now Tart runs on a single machine where you can only run at most two virtual machine at a time
Could you clarify, does it mean an Apple silicon Macbook can only run at most 2 macOS VMs at a time? And is this a limitation of the Apple Virtualization framework?

**Comment by nholloh** [comment]
As far as I know this limit was introduced by Apple through recent EULA changes. I'm not aware of any technical limitations.

**Comment by lanycrost** [comment]
At [Krisp](krisp.ai) we already using tart for our build/test automation system, and we have very simple API for scheduling VM's across machines.

Thanks for great job. I would like to take part on Orchard development, if you need any help there.

Do you have any estimations about the release of first version of Orchard?

**Comment by lanycrost** [comment]
Regarding the jenkins plugin issue: #388 

I guess we can have such plugin ([something like this one](https://plugins.jenkins.io/kubernetes/)), after having this system.
