### ISSUE TITLE
Feature Request: Detach mode for "tart run"

### ISSUE THREAD

**Issue by leomao10** [cirruslabs/tart#374]
Currently "Tart Run" command is continue running until VM get terminated. And would be a bit hard for us if we want to write a script to run it as service. Would be great if `tart run` can provide `--detach` mode or provide `tart up` command(like that vagrant up`) which will return once VM start successfully.

**Comment by cosmoshepcat** [comment]
have you looked at daemonize?  can be installed via brew and it is currently how the custom gitlab runner works with tart

**Comment by leomao10** [comment]
> currently I'm using nohup tart run <vm_name> --no-graphics" >/dev/null 2>&1 &
@Esysc Yeah, that is roughly what we are doing at the moment, but we still need to have extra script to check if VM is started successfully and able to ssh before we do any further action. 

Would love to have something build in in tart.

> have you looked at daemonize? can be installed via brew and it is currently how the custom gitlab runner works with tart
Thanks @cosmoshepcat That is an interesting one, will definitely give that a try.

**Comment by damonbreeden** [comment]
you can just run it as a `launchd` daemon
```
cat /Library/LaunchDaemons/com.ahrefs.macvm300.plist

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.ahrefs.macvm300</string>
  <key>ProgramArguments</key>
  <array>
    <string>sh</string>
    <string>-c</string>
    <string>/opt/homebrew/bin/tart run --no-graphics macvm300</string>
  </array>
  <key>StandardErrorPath</key>
  <string>/var/log/tart/macvm300.log</string>
  <key>StandardOutPath</key>
  <string>/var/log/tart/macvm300.log</string>
  <key>UserName</key>
  <string>user</string>
  <key>GroupName</key>
  <string>user</string>
  <key>WorkingDirectory</key>
  <string>/Users/user</string>
  <key>KeepAlive</key>
  <true/>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
```

run it with `sudo lauchctl load /Library/LaunchDaemons/com.ahrefs.macvm300.plist`, stop it with `sudo lauchctl unload /Library/LaunchDaemons/com.ahrefs.macvm300.plist`

you can learn about `launchd` to find out how to run it as a user daemon, user agent, system agent, etc

**Comment by fmoc** [comment]
I know about `launchd`. But just like there is a `stop` command, there should be a `--detach`.

**Comment by grigorye** [comment]
It does not exactly address the request, but I'd recommend taking a look at [orchard](https://github.com/cirruslabs/orchard) from the very same folks, if you want to run tart as a service. I believe that it may be suitable in the very same context/does quite a lot more useful things besides running tart "detached".

**Comment by fkorotkov** [comment]
Closing since we are not panning to implement a separate flag for the purpose. There are a few option to achieve a daemon like behaviour including just adding `&`:

```bash
set -e

tart run sonoma-base &

# check everything booted
tart ip --wait 60 sonoma-base

# do some work inside the VM like
brew install sshpass
sshpass -p admin ssh -o "StrictHostKeyChecking no" admin@$(tart ip sonoma-base) "uname -a"
sshpass -p admin ssh -o "StrictHostKeyChecking no" admin@$(tart ip sonoma-base) < script.sh

# stop the VM
tart stop sonoma-base
```
