### ISSUE TITLE
Tart Jenkins plugin

### ISSUE THREAD

**Issue by hokadiri** [cirruslabs/tart#388]
Could we have a jenkins plugin for tart. 

This would allow for a first class integration with jenkins CI. 

Thanks

**Comment by fkorotkov** [comment]
What you'd like to see from such a plugin? Do you want agents running inside of Tart VMs? Or you'd like for an agent running on some Linux box to launch a Tart VM remotely and execute scripts there? Or something else?

**Comment by fkorotkov** [comment]
Closing for now since it's not what kind of requirements users want.

**Comment by gitperr** [comment]
Hey, could be nice to do something like what is already happening on GitLab for example.

Tart+jenkins processes run on the host, and when a job comes Tart boots up the VM and runs the tasks in there.

Or if possible, Tart VMs are always running with jenkins agent in them and completing jobs, maybe this one would be already do-able though.
