### ISSUE TITLE
Pushing of an image should populate local cache

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#39]
Once one successfully pushes an image via:

```shell
tart push my-local some-cr.io/acme/remote:latest
```

Tart should copy over `my-local` into `oci` cache.

**Comment by erikng** [comment]
What about a symlink?

**Comment by edigaryev** [comment]
> What about a symlink?

Both symbolic link and the hard link won't ensure that the local VM's disk and configuration will stay immutable. Locking a pushed local VM from running and making changes to it is probably not an option.

**Comment by fkorotkov** [comment]
@edigaryev what do you think of a flag like `--populate-cache`  which will be `false` by default?
