### ISSUE TITLE
Add is-running/state command to tart CLI

### ISSUE THREAD

**Issue by fmoc** [cirruslabs/tart#393]
I'm using ansible to deploy tart VMs for CI purposes. I use packer to clone the upstream VM image and provision the resulting VM with the required packages and credentials. This works quite well. I can use `tart list` to check whether the VM exists, and if not, I can have ansible set it up for me again.

One problem I have is the lack of a way to check whether a VM is running. This is really important, as for instance after reboots the VMs typically don't run and re-running ansible won't fix the issue (the VM exists, after all, it's just not running). The only way I could come up with so far is to try and ping the VM's IP address, but that is more or less a hack. A way better solution would be to just ask `tart` directly.

Related to https://github.com/cirruslabs/tart/issues/300, but ideally there would be a separate command. The simplest way I could imagine is a `tart is-running <vm name>` command that just exits with a non-zero return code if the VM is just not running. A more sophisticated version would be to have a `tart state <vm name>` command that, e.g., prints some meaningful string and/or returns different exit codes depending on the current state of the VM. Both are machine readable solutions that don't require grepping in a list of VM names.

**Comment by fmoc** [comment]
I was indeed looking into using `tart ip` for this purpose and noticed that when `stop`ped, the command would return a value nevertheless. I don't really mind this behavior, as my understanding is that this IP doesn't change once assigned. It makes sense to provide the value then, even if the machine is stopped.

Also, a special `state` command gives the user an idea of what it should be used for. Overloading single commands with too many use cases is not a good idea.

**Comment by fkorotkov** [comment]
You can probably just always try to `tart run` a VM which will [return exit code 2 if the VM is already running](https://github.com/cirruslabs/tart/blob/ecc5de18bed8a9d95f5715975d2f070d71ac3f83/Sources/tart/VMStorageHelper.swift#L104-L105).

We were thinking of introducing a `info` or `describe` command as a replacement to `get` which will support a human readable output as well as a JSON output format that can be piped to something like `jq` or easily parsed by an integration.

**Comment by fmoc** [comment]
> You can probably just always try to tart run a VM which will [return exit code 2 if the VM is already running](https://github.com/cirruslabs/tart/blob/ecc5de18bed8a9d95f5715975d2f070d71ac3f83/Sources/tart/VMStorageHelper.swift#L104-L105).

I'm using `nohup` to detach the VM process, as I don't want ansible to block, so I can't really evaluate the exit code. That might change once a `--detach` flag is there, see #374.

A machine readable output of any kind would be highly appreciated.

**Comment by tomjn** [comment]
@fkorotkov I'm in a similar position for @fmoc, I can't wait for an exit code because if everything goes well no exit code will arrive and I'll be waiting minutes/hours/days for the user to close the process before the script can continue to the next step.

I think the fundamental problem is that `tart run` uses a single process for both starting the VM and the VM itself, whereas other VM providers have separate processes for managing the VM and the VM itself, e.g. `vboxmanage.exe` or the parallels control command.
