### ISSUE TITLE
Q: Intel support

### ISSUE THREAD

**Issue by tomjn** [cirruslabs/tart#399]
I don't expect a large number of Intel Mac users to appear, and I don't see anything that prevents Intel support at the moment other than the hardware in front of me, but out of curiosity what's the official line on this?

**Comment by tomjn** [comment]
My understanding at the moment is that the necessary frameworks are present in the Intel builds of Ventura, so if you had the relevant IPSW/ISO and an older Mac you could use Tart on non-Arm Macs running Ventura

**Comment by fkorotkov** [comment]
Duplication of #67
