### ISSUE TITLE
More robust uploads/downloads

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#41]
Add retries, chunked uploads, more granular progress, etc.

**Comment by kxxoling** [comment]
This would be helpful for me. I am downloading a more than 18GB image from ghcr.io in China which only have a poor connection, and have fallen several times at 10+ percent.

It would also be great if have breakpoint continuation support.

**Comment by fkorotkov** [comment]
Seems we can use something like https://github.com/radianttap/Alley to add automatic retries. It seems there is no built retries that is easy to use.

**Comment by fkorotkov** [comment]
@kxxoling could you please try `tart` binary from #95? The new HTTP client should be much more resilient and performant for pushing/pulling. Here is a direct link to the binary 

https://api.cirrus-ci.com/v1/artifact/task/6656749775093760/binary/.build/debug/tart

**Comment by fkorotkov** [comment]
The improvement was released as part of 0.5.0 version. In my testing the downloads were 20% faster and using far less memory due to streaming nature of the new http client.
