### ISSUE TITLE
Keeps crashing/freezing

### ISSUE THREAD

**Issue by fmnxl** [cirruslabs/tart#412]
Trying to use tart to run NixOS on my mac (M1 2020, Ventura 13.1, 8GB RAM), but it keeps crashing randomly before I get to partition and format the disk.

Running tart 0.37.2. My instance is set at 4 CPU, 50GB disk size.

**Comment by fkorotkov** [comment]
Could you please provide steps to reproduce?

**Comment by tomjn** [comment]
I'm having similar issues with the Ubuntu 20 and Ubuntu 22 installers, at one point the window printed a big crashdump which then got overwritten by text as the installer re-rendered the page. I couldn't use the screenshot key combinations though as they were being intercepted by the guest OS, and most of it was cut off above the screen. Then while installing packages the screen would freeze and no longer update.

Some linux guests have had a similar crash dump then become unresponsive forcing me to kill the VM.

I had moderately more success using the experimental VNC flag which has the benefit of giving me screenshots, and doesn't spit out a crashdump all over the screen, but Ubuntu 20 LTS installation has been on this screen with no visual updates for a while now with 200-300% CPU from the virtualisation service:

![Screen Sharing Picture 11 February 2023 at 18 30 26 GMT](https://user-images.githubusercontent.com/58855/218275090-485fabb0-6526-4787-b907-b6484a9a99da.png)

**Comment by tomjn** [comment]
Managed to get a screenshot of the kernel panic, it appears to be virtio related:

<img width="1051" alt="Screenshot 2023-02-11 at 18 51 20" src="https://user-images.githubusercontent.com/58855/218275869-6d366c83-2557-4d5e-9f5f-906bb8b7b6bb.png">

**Comment by tomjn** [comment]
I tried again but with the HWE kernel and recorded what happened:

https://youtu.be/m8apEaSkrFY

**Comment by tomjn** [comment]
I re-ran with a new VM and the normal kernel and recorded the resulting kernel panic: https://youtu.be/cSyyBdjeAr0

**Comment by tomjn** [comment]
Noting Ubuntu 22 minimal server install did not encounter the above issue, will keep an eye out but I suspect this may be kernel related rather than Tart. Specifically I suspect a change made in 2021 in the linux kernel related the anonymous VMA's may have fixed this but I cannot be sure.

@fmnxl do you know which version of the linux kernel your copy of NixOS is using?

**Comment by tomjn** [comment]
specifically this is what lead me to that conclusion: https://lore.kernel.org/linux-mm/20210224200449.hkU5GTEiH%25akpm@linux-foundation.org/

**Comment by fmnxl** [comment]
> do you know which version of the linux kernel your copy of NixOS is using?

<img width="228" alt="image" src="https://user-images.githubusercontent.com/4031216/218394246-f4f36f70-2c7f-44df-a207-dc3bdd62be33.png">

Is this it? I'm not so knowledgeable with the OS.

I'm installing the minimal ISO of NixOS, without GUI. Here is where it consistently freezes:

On host:
`tart run --disk nixos.iso nixos`

On VM:
```
# doesn't hang if i don't do anything
sudo -i
parted
# I haven't started doing anything here, just opened `parted`
# after a few seconds, the VM freezes
```

<img width="563" alt="image" src="https://user-images.githubusercontent.com/4031216/218395133-f3b973c5-a8b2-4ea7-bfd0-845936332247.png">

**Comment by tomjn** [comment]
hmm maybe not the same then, this is the ubuntu 22 box I was using:

<img width="542" alt="Screenshot 2023-02-13 at 11 07 29" src="https://user-images.githubusercontent.com/58855/218441949-f0dd28e5-ed26-4bcc-9286-23850222ee3b.png">

When you say it freezes, is it the VM that freezes in its entirety, or is it the GUI window? Can you SSH into it or ping the machine from MacOS? What about the `--vnc` and `--vnc-experimental` flags?

**Comment by fkorotkov** [comment]
Sorry for ghosting the issue. I don't recall why it was the case.

Seems it's a bug between Virtualization.Framework and the particular Linux distribution you have.

**Comment by nferch** [comment]
@tomjn have you had any more issues? What kernel version are you using? I'm getting pretty consistent crashes and hangs trying to install Ubuntu Focal and Jammy, like 

```[    9.122644] Unable to handle kernel paging request at virtual address ffff00010838b000
[    9.122698] Mem abort info:
[    9.122720]   ESR = 0x96000047
[    9.122745]   EC = 0x25: DABT (current EL), IL = 32 bits
[    9.122782]   SET = 0, FnV = 0
[    9.122807]   EA = 0, S1PTW = 0
[    9.122833] Data abort info:
[    9.122863]   ISV = 0, ISS = 0x00000047
[    9.122886]   CM = 0, WnR = 1
[    9.122909] swapper pgtable: 4k pages, 48-bit VAs, pgdp=0000000071978000
[    9.122955] [ffff00010838b000] pgd=000000016fff7003, pud=000000016f89b003, pmd=000000016f859003, pte=0103800101000000
[    9.123028] Internal error: Oops: 96000047 [#3] SMP
[    9.123056] Modules linked in: dm_multipath scsi_dh_rdac scsi_dh_emc scsi_dh_alua joydev input_leds sch_fq_codel ipmi_devintf ipr
[    9.123530] CPU: 1 PID: 1279 Comm: snapd Tainted: G      D W         5.4.0-125-generic #141-Ubuntu
[    9.123623] Hardware name: Apple Inc. Apple Virtualization Generic Platform, BIOS 1968.100.17.0.0 03/04/2023
[    9.123719] pstate: 20400005 (nzCv daif +PAN -UAO)
[    9.123783] pc : clear_page+0x10/0x24
[    9.123851] lr : prep_new_page+0x148/0x188
[    9.123893] sp : ffff800012d5bb10
[    9.123930] x29: ffff800012d5bb10 x28: ffff00012f717680
[    9.123992] x27: ffff000000000000 x26: 000000000420e300
[    9.124032] x25: 0000000000100cca x24: 0000000000000000
[    9.124073] x23: ffff0001267e5b80 x22: 0000000000000001
[    9.124137] x21: 000000000420e2c0 x20: 0000000000000381
[    9.124215] x19: fffffe000400e2c0 x18: 0000000000000000
[    9.124256] x17: 0000000000000000 x16: 0000000000000000
[    9.124308] x15: 0000000000000000 x14: 0000000000000000
[    9.124351] x13: 0000000000000000 x12: 0000000000000000
[    9.124383] x11: 0000000000000000 x10: 0000000000000000
[    9.124415] x9 : 000000000000173b x8 : 0000000000000000
[    9.124475] x7 : ffff800011b66f38 x6 : ffff0001267e5b80
[    9.124511] x5 : 0000000000000001 x4 : 0000000000000004
[    9.124553] x3 : 0000000000000381 x2 : 0000000000000004
[    9.124603] x1 : 0000000000000040 x0 : ffff00010838b000
[    9.124651] Call trace:
[    9.124667]  clear_page+0x10/0x24
[    9.124723]  get_page_from_freelist+0x2a0/0x460
[    9.124773]  __alloc_pages_nodemask+0x168/0x338
[    9.124828]  alloc_pages_vma+0x94/0x220
[    9.124880]  do_fault+0x78/0x5a0
[    9.124914]  __handle_mm_fault+0x270/0x7f0
[    9.124955]  handle_mm_fault+0xc0/0x180
[    9.124986]  do_page_fault+0x158/0x4b8
[    9.125022]  do_translation_fault+0xb4/0xc8
[    9.125075]  do_mem_abort+0x54/0xb0
[    9.125121]  el0_da+0x1c/0x20
[    9.125148] Code: d53b00e1 12000c21 d2800082 9ac12041 (d50b7420)
[    9.125191] ---[ end trace 8ca2cf5d104ddb12 ]---
```

**Comment by tomjn** [comment]
I haven’t encountered this since my last comment
