### ISSUE TITLE
Adding feed to blog

### ISSUE THREAD

**Issue by vitorgalvao** [cirruslabs/tart#435]
As per conversation in https://github.com/cirruslabs/tart/pull/415 it would be useful to have a feed on [the blog](https://tart.run/blog/) so we can follow it with an RSS reeder.

[RSS](https://en.wikipedia.org/wiki/RSS) is the obvious choice but [JSON feeds](https://en.wikipedia.org/wiki/JSON_Feed) are easier to create and supported by most feed readers. The feeds would contain the link to the post and ideally the full text. These are typically auto-generated by whatever blogging platform/service/generator one uses.

**Comment by vitorgalvao** [comment]
Can confirm it works, even if not with the full text. Thank you. Pinging @barkingfoodog.

**Comment by barkingfoodog** [comment]
Ditto here—feed works great! Thank you!
