### ISSUE TITLE
App notarization broken 1.0.2

### ISSUE THREAD

**Issue by ollytonks** [cirruslabs/tart#441]
Hi, I've just tried to install the latest version via

`brew install cirruslabs/cli/tart` which works but the packaged app signing seems to be broken

running `tart --version` produces

![Screenshot 2023-03-07 at 3 26 41 pm](https://user-images.githubusercontent.com/44695994/223320833-7df8cf1d-e61d-4405-9c34-bfa390cd78d0.png)

The signing seems to be broken as it's not recognising this app as coming from a known developer
![Screenshot 2023-03-07 at 3 33 51 pm](https://user-images.githubusercontent.com/44695994/223321485-df846c6c-aab7-4a63-a303-f88f79bfa9df.png)

```zsh
brew info tart
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> tart: stable 0.38.0 (bottled)
macOS and Linux VMs on Apple Silicon to use in CI and other automations
https://github.com/cirruslabs/tart
/opt/homebrew/Cellar/tart/1.0.2 (5 files, 18.7MB) *
  Built from source on 2023-03-07 at 03:52:16
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/tart.rb
License: AGPL-3.0-or-later
==> Dependencies
Build: rust ✘
==> Requirements
Build: Xcode >= 14.1 ✘
Required: arm64 architecture ✔, macOS >= 12 ✔, macOS ✔
==> Analytics
install: 146 (30 days), 314 (90 days), 411 (365 days)
install-on-request: 146 (30 days), 314 (90 days), 411 (365 days)
build-error: 0 (30 days)
```

The tool still works after overriding the security settings

**Comment by fkorotkov** [comment]
Sorry for the inconvenience. Should be fixed by #440

**Comment by ollytonks** [comment]
Phew! That was quick. Thank you! Loving tart so far 👏

**Comment by patricks** [comment]
I have updated to `1.0.3` but I still get this dialog.

**Comment by ollytonks** [comment]
yep still no luck unfortunately for me too

**Comment by fkorotkov** [comment]
It seems notarization of a `*.pkg` was breaking validation of the binary used for homebrew. We've disable building `.pkg` for now in https://github.com/cirruslabs/tart/commit/94e9425db7f62b9fa893a79e469645f3b843d45b. Seems we'll need to use different bundle ids or at least versions. 🤔

**Comment by fkorotkov** [comment]
`1.0.5` should work.

**Comment by patricks** [comment]
`1.0.5` works again, thx! 🥳
