### ISSUE TITLE
macOS Virtual Machine Scaling is Very Small

### ISSUE THREAD

**Issue by nick-botticelli** [cirruslabs/tart#447]
<img width="1568" alt="Screenshot 2023-03-15 at 2 33 27 PM" src="https://user-images.githubusercontent.com/25168557/225448726-13e1496a-a71f-439a-b305-4310c002af69.png">

Not sure if this could be due to the old version of the VM. It is using 12.0.1 guest on 13.2.1 host (MacBook Air Late 2020). Manually modifying the DPI in the source code led to more acceptable scaling, but made the entire window blurry as well.

**Comment by fkorotkov** [comment]
Do you happen to have multiple monitors attached? [Tart configures DPI based on the "main" screen](https://github.com/cirruslabs/tart/blob/94e9425db7f62b9fa893a79e469645f3b843d45b/Sources/tart/Platform/Darwin.swift#L69) so if you have your terminal where you run `tart run` open on the MacBook but you move Tart VM window to an external monitor than there will be DPI mismatch.

**Comment by nick-botticelli** [comment]
> Do you happen to have multiple monitors attached? [Tart configures DPI based on the "main" screen](https://github.com/cirruslabs/tart/blob/94e9425db7f62b9fa893a79e469645f3b843d45b/Sources/tart/Platform/Darwin.swift#L69) so if you have your terminal where you run `tart run` open on the MacBook but you move Tart VM window to an external monitor than there will be DPI mismatch.

Unfortunately I am not using any other monitors with my MacBook. I thought the problem may have been caused by running this commands in a terminal inside a fullscreen Visual Studio Code window, so I tried recreating it and running it in Terminal on the main non-fullcreen window, and it still results in the same issue.

**Comment by fkorotkov** [comment]
It seems that you host display is `2560 x 1600`. Have you configured the VM to have `3000 x 1800`? Given you have a Retina display could you please try running `tart set --display "1280x800" VM-NAME`?

**Comment by nick-botticelli** [comment]
In my screenshot above, you can see it is in fact running at 3000x1800 with scaling. Setting the tart display setting to 1280x800 did not fix the issue. Setting the tart display setting 3000x1800 results in the scaling perfectly matching my system, except for the fact that the window is now way too large for my screen.

Does this sound like an issue that a 12.0.1 guest may have? Unfortunately I don't have much storage space to fit another IPSW + VM (even if I delete this one), so I might be limited on testing capability.

**Comment by fkorotkov** [comment]
I just now noticed that you have choose `Scaled` resolution in display preferences inside the VM. If you choose the default one, everything should be scaled similar to the host diplay.

**Comment by nick-botticelli** [comment]
I didn't catch it in the screenshot, but that is actually the only resolution available even when selecting "Show all resolutions". I noticed that this screenshot shows the display being detected as a 22-inch; on an other occasion (default resolution?), the display size is shown as a 16.3-inch. This is on my MacBook Air (Late 2020), which is a 13.3-inch display.

Could this be the problem? Again, this may just be an issue with a 12.0.1 guest.
