### ISSUE TITLE
invalid virtual machine configuration. Unsupported “hardwareModel”.

### ISSUE THREAD

**Issue by sanny1** [cirruslabs/tart#469]
I am currently running M2 apple silicon, does it not support this? following is the error I get when attempt to run a vm:
`Error: Invalid virtual machine configuration. Unsupported “hardwareModel”.`

**Comment by fkorotkov** [comment]
Hey @sanny1, could you please tell a bit more about your VM and your host? For example, to run Ventrura VMs 13.3+ you need a Ventura 13.0+ host.

**Comment by sanny1** [comment]
Hi @fkorotkov, oh okay makes sense my host is still at Monterey 12.4, do you have the command line code for installing Monterey image using tart?

**Comment by sanny1** [comment]
> Hi @fkorotkov, oh okay makes sense my host is still at Monterey 12.4 and its trying to run the Ventura VM 13, do you know the registry and image name for pulling the monterey one?

pulling the monterey image and running it solved it

**Comment by fkorotkov** [comment]
Just wanted to note that you can run Ventura 13.2 VMs. 👌 You can try `ghcr.io/cirruslabs/macos-ventura-vanilla:13.2.1`, for example.

**Comment by sanny1** [comment]
Ya thanks that works as well :)
