### ISSUE TITLE
Network connection lost pushing to ECR

### ISSUE THREAD

**Issue by josephburnett** [cirruslabs/tart#474]
Whenever I try to push from `tart` to ECR, I immediately get this error:
```
Error: The network connection was lost.
```
I'm able to pull just fine. And I'm on a pretty reliable Internet connection. So it seems like there's something wrong between Tart and ECR.

I've setup auth via the `TART_REGISTRY_*` environment variables since this is on a remote machine without Keychain access.
```
bash-3.2$ export AWS_ACCESS_KEY_ID=[REDACTED]
bash-3.2$ export AWS_SECRET_ACCESS_KEY=[REDACTED]
bash-3.2$ export TART_REGISTRY_PASSWORD=`aws ecr get-login-password --region eu-west-1`
bash-3.2$ export TART_REGISTRY_USERNAME=AWS
bash-3.2$ tart push macos-12-xcode-13-update [REDACTED].dkr.ecr.eu-west-1.amazonaws.com/macos/release:macos-12-xcode-13-202304181625
pushing macos-12-xcode-13-update to [REDACTED].dkr.ecr.eu-west-1.amazonaws.com/macos/release:macos-12-xcode-13-202304181625...
pushing config...
Error: The network connection was lost.
```
Is there a way I can get more verbose logs? Or a way to debug the connection between Tart and ECR?

**Comment by josephburnett** [comment]
Also, I get the exact same error when pushing directly from my laptop, using Keychain. So it doesn't seem like an auth thing.

**Comment by fkorotkov** [comment]
Just tried with Tart 1.4.1 and registry in us-east-2 which worked. Registry in eu-west-1 also worked.

Please let me know which version of Tart you have and your macOS version on the host? And if you have VPN/some other custom network configuration?

**Comment by josephburnett** [comment]
This was just IAM misconfiguration. I was missing a few actions in the policy. User error :stuck_out_tongue:.

This is the policy that worked ([push-pull](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policy-examples.html) + `"ecr:GetAuthorizationToken"` for getting the login password): 
```
{
    "Version": "2012-10-17",
    "Statement": {
        "Action": [
            "ecr:BatchGetImage",
            "ecr:BatchCheckLayerAvailability",
            "ecr:CompleteLayerUpload",
            "ecr:GetDownloadUrlForLayer",
            "ecr:InitiateLayerUpload",
            "ecr:PutImage",
            "ecr:UploadLayerPart",
            "ecr:GetAuthorizationToken"
        ],
        "Effect": "Allow",
        "Resource": [
            "*"
        ]
    }
}
```

AWS was probably dropping the connection on auth failure without so much as a goodbye (or `403`)!

------

For the record, I was using tart `1.1.0` and then upgraded to `1.4.2` but it made no difference.

Instance mac version:
```
ProductName:    macOS
ProductVersion: 12.6.3
BuildVersion:   21G419
```

Laptop mac version:
```
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
```

Mac version made no difference.
