### ISSUE TITLE
Tart login authentication issues

### ISSUE THREAD

**Issue by rigellin73** [cirruslabs/tart#483]
Hello!
We're using custom VM images for our CI and we'd like to store them in our own registry (docker registry). I was trying to use tart push/ tart pull commands, but I'm having several problems:

1. I tried to use tart login command:
```
echo $PASSWORD | tart login $REGISTRY --username $USERNAME --password-stdin
invalid credentials: AuthFailed(why: "received unexpected HTTP status code 401 while retrieving an authentication token", details: "{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"HTTP Basic: Access denied\\\\nYou must use a personal access token with \'api\' scope for Git over HTTP.\\\\nYou can generate one at https://gitlab.lvl77.com/-/profile/personal_access_tokens\"}]}")
```

2. I tried to use enviromnent variables 
```
TART_REGISTRY_USERNAME=$USERNAME 
TART_REGISTRY_PASSWORD=$PASSWORD
$ tart login $REGISTRY
User: Password: invalid credentials: AuthFailed(why: "received unexpected HTTP status code 401 while retrieving an authentication token", details: "{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"HTTP Basic: Access denied\\\\nYou must use a personal access token with \'api\' scope for Git over HTTP.\\\\nYou can generate one at https://gitlab.lvl77.com/-/profile/personal_access_tokens\"}]}")
```

3. I tried to use `docker login` instead of `tart login`. It worked and I managed to push image to registry, but when I tried to pull it, I had a new error:
`Error: AuthFailed(why: "received unexpected HTTP status code 403 while retrieving an authentication token", details: "{\"errors\":[{\"code\":\"DENIED\",\"message\":\"access forbidden\"}],\"http_status\":403}")`
I looked at issue
https://github.com/cirruslabs/tart/issues/277
but I don't have `tart login` in Keychain

Сould you help me figure out how to push/pull images, please?

**Comment by edigaryev** [comment]
>You must use a personal access token with 'api' scope for Git over HTTP.

>You can generate one at https://gitlab.lvl77.com/-/profile/personal_access_tokens.

Have you tried this?

**Comment by rigellin73** [comment]
Yep, PASSWORD contains personal access token. It works for `docker login`, but doesn't work for `tart login` for some reasons

**Comment by rigellin73** [comment]
Yes

**Comment by edigaryev** [comment]
> Have you tried this?

Actually, I've just re-read the error message mentioned:

>You must use a personal access token with 'api' scope for Git over HTTP.

It seems to me that either (1) you're supplying a wrong registry name (it normally should be just the domain name, without `/...`) or (2) your GitLab server is misconfigured.

I've tried deploying a local GitLab instance (version 15.11) and the authentication from Tart seems to work just fine.

**Comment by jlsalmon** [comment]
I've also come across `--password-stdin` seeming to not work as expected. I can perform an interactive login (typing the username and password at the prompts) and it works just fine. But if I try to pipe the password via stdin to `tart login`, it throws an error. I'm also using a GitLab registry, but I don't think this is related to GitLab itself:

```
echo $MY_PASSWORD | tart login my.registry.com --username my-user --password-stdin
invalid credentials: AuthFailed(why: "received unexpected HTTP status code 401 while retrieving an authentication token", details: "{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"HTTP Basic: Access denied\\\\nYou must use a personal access token with \'api\' scope for Git over HTTP.\\\\nYou can generate one at https://gitlab.lvl77.com/-/profile/personal_access_tokens\"}]}")
```

Using the same credentials with `tart login my.registry.com` without arguments works just fine. So I suspect this is an issue with the way that `--password-stdin` is handling the input.

**Comment by rigellin73** [comment]
Yep, I'm having the same as @jlsalmon. And also I wanted to mention some things

- Using TART_REGISTRY_USERNAME / TART_REGISTRY_PASSWORD does actually work for me now, but it wasn't clear for me that I shouldn't use `tart login` if I have this variables. May I suggest to add some clarification about it in documentation? I used this page for information:
https://tart.run/integrations/vm-management/

- I found out that my original problems with login was caused by keychain. If I use wrong credentials for tart login, tart still add it in the keychain. I think, it might be a wrong behavior

**Comment by edigaryev** [comment]
@jlsalmon thanks for reporting the issue with `echo` without `-n`, this will be addressed in https://github.com/cirruslabs/tart/pull/486.

@rigellin73 "If I use wrong credentials for tart login, tart still add it in the keychain." — `tart login` only stores the credentials in the Keychain if it's able to [query registry's /v2 endpoint without 401 Unauthorized error](https://github.com/cirruslabs/tart/blob/37ae7888e663c776a6f5a70edd8fc96d269f8add/Sources/tart/Commands/Login.swift#L45-L53).

`https://gitlab.com/v2` seems to return `HTTP 401` by default, so I don't think this is the case.

**Comment by rigellin73** [comment]
Ok, I get it. Now I can login using 
`$ echo -n $GITLAB_TOKEN tart login registry --username user --password-stdin`
or using TART_REGISTRY_USERNAME / TART_REGISTRY_PASSWORD without `tart login`
It looks like I don't have any issues with gitlab, I just tried to log in the wrong way. Thank you for your time!
