### ISSUE TITLE
Is there full screen support?

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#495]
### Discussed in https://github.com/cirruslabs/tart/discussions/487

<div type='discussions-op-text'>

<sup>Originally posted by **GuyDev1** May  4, 2023</sup>
Hey,

The performance is great, but I can't manage to view the VM window as full screen (even when I do select full screen, I still see it at around 50%). Is this a known issue? or something I can fix?

Thank you!</div>

Converter the discussion by @GuyDev1 to an issue to support `--fullscreen` flag for `tart run` command.

**Comment by edigaryev** [comment]
Should be at least partially addressed by the recently merged https://github.com/cirruslabs/tart/pull/521.
