### ISSUE TITLE
`tart` binary will not run on macOS 13.3.1 when downloaded from the release page

### ISSUE THREAD

**Issue by natewalck** [cirruslabs/tart#498]
Repro: 

1. Download 1.4.2 from the releases page: https://github.com/cirruslabs/tart/releases/download/1.4.2/tart.tar.gz
2. Extract the tar.gz
3. Attempt to run `tart --version`
4. Get the following message:
```
zsh: killed     ./tart --version
```

Upon further inspection, the binary is not notarized, so macOS is bailing on it. See the screenshot below:

<img width="648" alt="Screenshot 2023-05-11 at 12 13 52" src="https://github.com/cirruslabs/tart/assets/867868/4c23db68-f7a4-4f29-b166-ef8c1ca5a2b4">

Additionally, the tart.app is also in a bad state and I cannot even load it in Apparency (which looks at all the details of the .app, including signing, notarization and entitlements.

<img width="372" alt="Screenshot 2023-05-11 at 12 14 37" src="https://github.com/cirruslabs/tart/assets/867868/32d16477-6da3-45bc-b522-a9aa64bfabd3">

**Comment by fkorotkov** [comment]
What of you'll try to run `./tart.app/Contents/MacOS/tart --version`? This is a trick to put a binary in an App-like structure so `embedded.provisionprofile` is picked by MacOS. `embedded.provisionprofile` is needed for bridged network to work because it requires elevated privileges.

**Comment by natewalck** [comment]
I tried it both ways. Executing the one inside the .app bundle gives you:

<img width="372" alt="Screenshot 2023-05-11 at 1 09 26 PM" src="https://github.com/cirruslabs/tart/assets/867868/4545f556-a6ad-49a7-a756-a43611f59874">

I also removed the quarantine bit to ensure that wasn't causing any issues.

tart.app is not a valid app bundle, it is missing a ton of stuff. See the screenshot below:

<img width="273" alt="Screenshot 2023-05-11 at 1 36 43 PM" src="https://github.com/cirruslabs/tart/assets/867868/5bf1fe92-2a20-416c-b85d-42ebb8102df0">

The .app bundle should have a `.plist` with the bundle identifier and a bunch of other metadata If you build the target with xcode.

It is not sufficient to place the files in the directory structure for the entitlement to work, it needs to be a proper .app. (I'd also suggest putting it in `/Applications` whenever the package build is fixed.)

**Comment by headmin** [comment]
Same experience as @natewalck here. tried `xattr -rc` to remove attributes.  also `./tart.app/Contents/MacOS/tart --version`no luck.

**Comment by fkorotkov** [comment]
According to [Apple docs](https://developer.apple.com/documentation/Xcode/signing-a-daemon-with-a-restricted-entitlement) having such fake app structure is the only way to get restricted entitlements for binaries and not apps.

Does installing from brew via `brew install cirruslabs/cli/tart` works for you? It uses the same `.tar.gz` as you are trying.

**Comment by natewalck** [comment]
I tested the download from the release page on second machine and got the same results as above. 

However, using `brew install cirruslabs/cli/tart` worked as expected. 

This smells like a macOS bug to me given a downloaded file from a web browser is handled differently from a command line download/install.

That said, would it be possible to notarize the binary? That would instantly fix this issue and it would never pop up again (in theory).

**Comment by fkorotkov** [comment]
Interesting. The binary should be notarized. How do you download the archive and unarchive it? Do you use `curl` or just Safari and double click?

**Comment by natewalck** [comment]
I'm on Chrome. Go to releases, download it and then open it in [Apparency](https://mothersruin.com/software/Apparency/) . It shows un-notarized and macOS's behavior reflects that as well (In addition to the Quarantine xattr, meaning it was manually downloaded from a browser).

**Comment by fkorotkov** [comment]
I think the issue there is that archive in the releases is a bit weirdly structured because we are using Goreleaser that is not intended to used that way. I've created #503 to fix this at some point. For now, installing via Homebrew is the recommended way.
