### ISSUE TITLE
semi-frequent crashes of host system

### ISSUE THREAD

**Issue by stanogn** [cirruslabs/tart#502]
### System
I am using tart VMs on a mac studio with M1 ultra and 64gb of ram.
It was happening with macos 12.x and keeps happening with 13.3.1.
I am using 2 macos VMs most of the time, constantly stopping and starting new ones (using for CI).

### Crash log
I get a 'Your computer was restarted because of a problem' message after the restart. This is the first line of the crash log when i press report: `panic(cpu 10 caller 0xfffffe0014226bec): Kernel data abort.`
There is more info after which i can supply but im not sure would be of much use.

I know this wont be easy to troubleshoot, but i am creating an issue anyways in case anyone else encounters the same issue.
Any ideas what could be wrong?

**Comment by edigaryev** [comment]
>Any ideas what could be wrong?

This might be due to the specific workloads that you run. Are they HW/GPU-related? Do you use some extra `tart run` arguments like `--net-bridged`, `--dir`, `--vnc`, etc?

**Comment by fkorotkov** [comment]
How did you conclude that Tart causing the panics/restarts? Anything in the logs/crash report suggested it?

**Comment by stanogn** [comment]
> > Any ideas what could be wrong?
> 
> This might be due to the specific workloads that you run. Are they HW/GPU-related? Do you use some extra `tart run` arguments like `--net-bridged`, `--dir`, `--vnc`, etc?

I am building ios/android apps through github self-hosted runners, nothing particularly HW or GPU related. I am running them using `tart run --no-graphics`.
The most recent crash happened when i tried to start a VM using `cirrus run --dirty` (no particular workload) and it crashed around the time the VM should be starting iirc.

I can try to find out the exact points where the crashes happen (startup, during a workload, ...) though i dont have time for that this week.

**Comment by stanogn** [comment]
Could rosetta or something arch related be the issue?

**Comment by stanogn** [comment]
> How did you conclude that Tart causing the panics/restarts? Anything in the logs/crash report suggested it?

Its my guess because of the most recent crash and because there is nothing else running except a ruby gem which manages the VMs.
But good question, i will try to not use VMs during the weekend and add some crash stats.

**Comment by stanogn** [comment]
> How did you conclude that Tart causing the panics/restarts? Anything in the logs/crash report suggested it?

Btw. is there a way to pinpoint that tart caused the crash?

**Comment by fkorotkov** [comment]
It will be helpful if you can provide some panic logs beside only the first line. Panics can happen for many reasons and all available information might be usefull.

Also what is your Mac Studio setup? Is it in a datacenter? Does it have a monitor or any other devices attached? What are the CPU/memory settings for your VM? Which version of macOS your VMs use?

**Comment by fkorotkov** [comment]
@nathreed thank you for the panics! Did couple of observations: both panics happened on core number 11 and were backtraced to some USB related kernel extensions. I assume there is nothing connected to the Mac Studio?

BTW we highly recommend to have an HDMI dummy display like this [one](https://www.bhphotovideo.com/c/product/1213945-REG/newertech_nwtadp4khead_hdmi_headless_video_accelerator.html/?ap=y&ap=y&smp=y&smp=y&smpm=ba_f2_lar&lsft=BI%3A514&gclid=CjwKCAjw9pGjBhB-EiwAa5jl3AquxzlqT12K95a0DjnrmI-2X2Psk_IteguogyiD6QKOSomaG4apZRoCxA4QAvD_BwE). At least back in the Intel days macOS was disabling some GPU optimization in case no display is connected. Having such dummy display boosted performance.

**Comment by nathreed** [comment]
> I assume there is nothing connected to the Mac Studio?

As far as I know, there was nothing connected. Now there is probably a keyboard and mouse connected, along with the display.

**Comment by stanogn** [comment]
I also got a crash log. There are no devices connected to the mac.
Here is the VM config:
CPU Memory Disk Display
8   16384  45   1024x768
[crashlog.txt](https://github.com/cirruslabs/tart/files/11501670/crashlog.txt)

**Comment by edigaryev** [comment]
Happens on macOS 14.0 (Sonoma) too:

```
panic(cpu 1 caller 0xfffffe001704ad04): Kernel data abort. at pc 0xfffffe0019457110, lr 0x4fd37e0019457224 (saved state: 0xfffffe5fcadef7d0)
	  x0:  0x0000000000000000 x1:  0x0000000000000013  x2:  0x0000000000000000  x3:  0x0000000000000000
	  x4:  0x0000000000000000 x5:  0x0000000000000000  x6:  0x0000000000000000  x7:  0x0000007ab32e9ac9
	  x8:  0xb4f7fe00194570f8 x9:  0xfffffe001671f3a0  x10: 0xfffffe0019e11630  x11: 0xfffffe0019e11600
	  x12: 0xffffffffffffffff x13: 0x0000011173478383  x14: 0xffffff693fe71fb8  x15: 0x0000000000000000
	  x16: 0xfffffe001671f3a0 x17: 0xf46dfe001671f3a0  x18: 0x0000000000000000  x19: 0xfffffe29ba03f4c0
	  x20: 0x0000000000000002 x21: 0x0000000000000001  x22: 0xfffffe0015b78e80  x23: 0xfffffe0015b846bf
	  x24: 0xfffffe0015b7b8ad x25: 0xfffffe20218c5000  x26: 0x0000000000000000  x27: 0xfffffe0019e10c18
	  x28: 0xfffffe0015b7af7a fp:  0xfffffe5fcadefb30  lr:  0x4fd37e0019457224  sp:  0xfffffe5fcadefb20
	  pc:  0xfffffe0019457110 cpsr: 0x60401208         esr: 0x96000005          far: 0x0000000000000000

Debugger message: panic
Memory ID: 0x6
OS release type: User
OS version: 23A5257q
Kernel version: Darwin Kernel Version 23.0.0: Mon May 22 22:52:05 PDT 2023; root:xnu-10002.0.40.505.5~4/RELEASE_ARM64_T6000
Fileset Kernelcache UUID: 136BBB00E80FC6E6D3505A2F8B3DF281
Kernel UUID: E24144EA-85B9-3CC6-A000-80F33FE12FE5
Boot session UUID: F17B38D7-2343-4297-9B1E-E3070C9A2F4C
iBoot version: iBoot-10151.0.82.0.1
secure boot?: YES
roots installed: 0
Paniclog version: 14
KernelCache slide: 0x000000000e2f8000
KernelCache base:  0xfffffe00152fc000
Kernel slide:      0x000000000e300000
Kernel text base:  0xfffffe0015304000
Kernel text exec slide: 0x000000000f7d8000
Kernel text exec base:  0xfffffe00167dc000
mach_absolute_time: 0x7ab33958d5
Epoch Time:        sec       usec
  Boot    : 0x647fb98c 0x0007a7d9
  Sleep   : 0x648073a9 0x00004ad9
  Wake    : 0x648075a4 0x0008fced
  Calendar: 0x648078ab 0x0004ff06

Zone info:
  Zone map: 0xfffffe1020dc0000 - 0xfffffe3020dc0000
  . VM    : 0xfffffe1020dc0000 - 0xfffffe14eda8c000
  . RO    : 0xfffffe14eda8c000 - 0xfffffe1687424000
  . GEN0  : 0xfffffe1687424000 - 0xfffffe1b540f0000
  . GEN1  : 0xfffffe1b540f0000 - 0xfffffe2020dbc000
  . GEN2  : 0xfffffe2020dbc000 - 0xfffffe24eda88000
  . GEN3  : 0xfffffe24eda88000 - 0xfffffe29ba754000
  . DATA  : 0xfffffe29ba754000 - 0xfffffe3020dc0000
  Metadata: 0xfffffe87e6cdc000 - 0xfffffe87eecdc000
  Bitmaps : 0xfffffe87eecdc000 - 0xfffffe87f4aac000
  Extra   : 0 - 0

TPIDRx_ELy = {1: 0xfffffe1b589c88a8  0: 0x0000000000000001  0ro: 0x0000000000000000 }
CORE 0 PVH locks held: None
CORE 1 PVH locks held: None
CORE 2 PVH locks held: None
CORE 3 PVH locks held: None
CORE 4 PVH locks held: None
CORE 5 PVH locks held: None
CORE 6 PVH locks held: None
CORE 7 PVH locks held: None
CORE 8 PVH locks held: None
CORE 9 PVH locks held: None
CORE 0: PC=0xfffffe0016f223bc, LR=0xfffffe0016f2239c, FP=0xfffffe5fcbcbfd20
CORE 1 is the one that panicked. Check the full backtrace for details.
CORE 2: PC=0x00000001942349d4, LR=0x0000000000000f50, FP=0x000000016f919d90
CORE 3: PC=0xfffffe001686f6c0, LR=0xfffffe001686f6c0, FP=0xfffffe5fcc553ef0
CORE 4: PC=0xfffffe001686f6c0, LR=0xfffffe001686f6c0, FP=0xfffffe5fcd1fbef0
CORE 5: PC=0xfffffe0016980ce0, LR=0xfffffe0016980cdc, FP=0xfffffe5fcc4f3e80
CORE 6: PC=0xfffffe00167e1544, LR=0xfffffe00167e1518, FP=0xfffffe5fcc5e3630
CORE 7: PC=0xfffffe001686f6c0, LR=0xfffffe001686f6c0, FP=0xfffffe5fcc863ef0
CORE 8: PC=0xfffffe001686f6c0, LR=0xfffffe001686f6c0, FP=0xfffffe5fcb05fef0
CORE 9: PC=0xfffffe001686f6c0, LR=0xfffffe001686f6c0, FP=0xfffffe5fcca6fef0
Compressor Info: 2% of compressed pages limit (OK) and 2% of segments limit (OK) with 0 swapfiles and OK swap space
Panicked task 0xfffffe1b541cde18: 0 pages, 534 threads: pid 0: kernel_task
Panicked thread: 0xfffffe1b589c88a8, backtrace: 0xfffffe5fcadeeef0, tid: 410774
		  lr: 0xfffffe0016834a98  fp: 0xfffffe5fcadeef70
		  lr: 0xfffffe001698c37c  fp: 0xfffffe5fcadeef90
		  lr: 0xfffffe001697ce84  fp: 0xfffffe5fcadef000
		  lr: 0xfffffe001697b2f8  fp: 0xfffffe5fcadef0f0
		  lr: 0xfffffe00167e3aa4  fp: 0xfffffe5fcadef100
		  lr: 0xfffffe0016834364  fp: 0xfffffe5fcadef4b0
		  lr: 0xfffffe00170402ac  fp: 0xfffffe5fcadef4d0
		  lr: 0xfffffe001704ad04  fp: 0xfffffe5fcadef650
		  lr: 0xfffffe001697ccf8  fp: 0xfffffe5fcadef6c0
		  lr: 0xfffffe001697b788  fp: 0xfffffe5fcadef7b0
		  lr: 0xfffffe00167e3aa4  fp: 0xfffffe5fcadef7c0
		  lr: 0xfffffe0019457224  fp: 0xfffffe5fcadefb30
		  lr: 0xfffffe0019457224  fp: 0xfffffe5fcadefb60
		  lr: 0xfffffe001943ff24  fp: 0xfffffe5fcadefbd0
		  lr: 0xfffffe00192db90c  fp: 0xfffffe5fcadefc60
		  lr: 0xfffffe0016f4251c  fp: 0xfffffe5fcadefcd0
		  lr: 0xfffffe00192db408  fp: 0xfffffe5fcadefd10
		  lr: 0xfffffe00192d7c70  fp: 0xfffffe5fcadefd50
		  lr: 0xfffffe0016f4251c  fp: 0xfffffe5fcadefdc0
		  lr: 0xfffffe00192d7b4c  fp: 0xfffffe5fcadefdf0
		  lr: 0xfffffe0016895098  fp: 0xfffffe5fcadefe30
		  lr: 0xfffffe00168960f8  fp: 0xfffffe5fcadeff20
		  lr: 0xfffffe00167eced8  fp: 0x0000000000000000
      Kernel Extensions in backtrace:
         com.apple.iokit.IOUSBHostFamily(1.2)[F442DB45-9C6C-3F87-9BF6-AF0CA38FD329]@0xfffffe00192b9c90->0xfffffe001936a3af
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[ACBA6BE5-6C90-3B47-8C55-9B87BB507849]@0xfffffe0017cef630->0xfffffe0017d1f3c3
            dependency: com.apple.driver.AppleSMC(3.1.9)[A63BC773-153F-3F78-A801-CF9E187295D8]@0xfffffe0017ef39b0->0xfffffe0017f17e57
            dependency: com.apple.driver.usb.AppleUSBCommon(1.0)[5E7B8D4F-283C-31EA-BBEB-81CE23ED6C24]@0xfffffe00183a8bf0->0xfffffe00183adaab
            dependency: com.apple.driver.AppleUSBHostMergeProperties(1.2)[F265553C-E76A-3BBB-8D85-5DFD77E3CA59]@0xfffffe0019404ed0->0xfffffe00194059fb
         com.apple.driver.usb.AppleUSBUserHCI(1.0)[1B2B37E8-76F0-320B-AFCC-DABD6D3C0BAC]@0xfffffe001943cbf0->0xfffffe001945968b
            dependency: com.apple.driver.usb.AppleUSBCommon(1.0)[5E7B8D4F-283C-31EA-BBEB-81CE23ED6C24]@0xfffffe00183a8bf0->0xfffffe00183adaab
            dependency: com.apple.iokit.IOUSBHostFamily(1.2)[F442DB45-9C6C-3F87-9BF6-AF0CA38FD329]@0xfffffe00192b9c90->0xfffffe001936a3af

last started kext at 415409995515: com.apple.driver.AppleUVDMDriver	1.0.0 (addr 0xfffffe00158d5920, size 5013)
```

**Comment by fkorotkov** [comment]
It doesn't seem like we can do anything on the Tart side so I'll close the issue.
