### ISSUE TITLE
Replace Goreleaser

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#503]
Goreleaser is meant for releasing Go Apps hence the name. Things with `prebuilt` binaries and hooks to sign the binaries look more like a hack and that we tried to workaround issues.

Because of this the release archives contains `tart` binary along `tart.app` because there is no way to not put a binary in the root.

At some point let's investigate migrating to some other tool or maybe even writing our own `omnireleaser` that helps to create/upload binaries/archives and not taking the job of building things like Goreleaser.

**Comment by edigaryev** [comment]
> Because of this the release archives contains `tart` binary along `tart.app` because there is no way to not put a binary in the root.

I wonder if we have other reasons to switch from GoReleaser besides this one?

We can fix this with the following change:

```patch
diff --git a/.goreleaser.yml b/.goreleaser.yml
index c0d7144..5861159 100644
--- a/.goreleaser.yml
+++ b/.goreleaser.yml
@@ -4,6 +4,8 @@ before:
   hooks:
     - .ci/set-version.sh
     - swift build -c release --product tart
+    - mkdir -p tart.app/Contents/MacOS
+    - cp .build/arm64-apple-macosx/release/tart tart.app/Contents/MacOS/
 
 builds:
   - builder: prebuilt
@@ -12,7 +14,7 @@ builds:
     goarch:
       - arm64
     prebuilt:
-      path: .build/arm64-apple-macosx/release/tart
+      path: tart.app/Contents/MacOS/tart
     hooks:
       post:
         - gon gon.hcl
@@ -23,9 +25,6 @@ archives:
       - src: Resources/embedded.provisionprofile
         dst: tart.app/Contents
         strip_parent: true
-      - src: ".build/arm64-apple-macosx/release/tart"
-        dst: tart.app/Contents/MacOS
-        strip_parent: true
       - LICENSE
 
 release:
```

However, currently `prebuilt:` doesn't seem to preserve the full path to the binary, so I've created an issue to address this: https://github.com/goreleaser/goreleaser/issues/4143.

**Comment by fkorotkov** [comment]
One other reason is that we pay for the Pro version to use 'prebuilt' and it seems like an overkill. We use less and less features of Goreleaser itself and use it for Swift, Rust and Go projects of course.

**Comment by edigaryev** [comment]
We've decided to keep it for now, at least until the Pro license will require a renewal.
