### ISSUE TITLE
Import from VM Timed out 

### ISSUE THREAD

**Issue by timbmw** [cirruslabs/tart#505]
Every time I try to import a .tvm file that has already been created, the import is aborted after a while without an error message and times out. I've already tried the whole thing with several .tvm files and also tried it on different VMs, but the same process happens every time.

**Comment by edigaryev** [comment]
1. Which macOS (`sw_vers`) and Tart version (`tart --version`) are you running?
2. How much memory do you have on your system?
3. Are you importing `.tvm` files created on another host? If so, please provide details outlined in 1 w.r.t. the other host.
4. Have you tried exporting and importing an official Cirrus Labs image, e.g. `ghcr.io/cirruslabs/macos-ventura-base:latest`? Does it work?
