### ISSUE TITLE
Pull not working

### ISSUE THREAD

**Issue by car5ten** [cirruslabs/tart#509]
I somehow messed up the pulling. Every time I try to pull the latest image from a private OCI I receive:

`tart command returned non-zero exit code: "Error: The file “latest” couldn’t be saved in the folder “ventura” because a file with the same name already exists."`

Can someone tell me how to fix this?

**Comment by fkorotkov** [comment]
You try to delete all the temporary files Tart uses by running `rm -rf ~/.tart/tmp/`. If that doesn't work you can try manually clean up the image from `~/.tart/cache/OCIs`.

**Comment by car5ten** [comment]
I already deleted `.tart/` completely, but it didn't help. Today I was debugging the gitlab-runner and additionally I found:
`Failed to stop VM: tart command returned non-zero exit code: "the specified VM \"gitlab-1586387\" does not exist"`
and a more descriptive information for the initial error:
`Failed to delete VM: VM errored: failed to delete VM gitlab-1586387: tart command returned non-zero exit code: "Error: “gitlab-1586387” couldn’t be removed."`

As far as I can tell, tart is somehow similar to docker and I was searching SO a lot already. Does tart use some kind of [layer system](https://stackoverflow.com/questions/45497720/docker-for-windows-already-exists-image-does-not-exist-at-all) like docker?

**Comment by edigaryev** [comment]
Does this also happen when pulling `ghcr.io/cirruslabs/macos-ventura-base:latest`, or only when pulling the image from the private registry?

**Comment by car5ten** [comment]
Same errors in debug mode, but the job fails with:
```
2023/06/02 10:12:59 Pulling the latest version of ghcr.io/cirruslabs/macos-ventura-base:latest...
2023/06/02 10:12:59 tart command returned non-zero exit code: "Error: AuthFailed(why: \"received unexpected HTTP status code 403 while retrieving an authentication token\", details: \"{\\\"errors\\\":[{\\\"code\\\":\\\"DENIED\\\",\\\"message\\\":\\\"denied\\\"}]}\\n\")"
```

**Comment by fkorotkov** [comment]
Could you please provide details about your setup? Did you configure Docker Credentials helpers and/or used `tart login`? Also which private registry you were trying to pull from originally and what was the exact `tart pull` command?

**Comment by car5ten** [comment]
My setup is:
A Mac Mini with M1, which is registered as Gitlab-Runner with custom executor (gitlab-tart-executor) using a private Gitlab OCI. I used tart login to push and pull the VMs as needed. 
In `.gitlab-ci.yml` I configured global variables and set the image to use:
```
variables:
    TART_EXECUTOR_SSH_USERNAME: $TART_SSH_USER_NAME
    TART_EXECUTOR_SSH_PASSWORD: $TART_SSH_USER_PASSWORD
    TART_EXECUTOR_ALWAYS_PULL: "true"

image: <private oci>/ventura:latest
```

I didn't figure out what was the Issue. I just restarted from scratch.
