### ISSUE TITLE
Trouble typing Pipe symbol into shell in Tart VMs

### ISSUE THREAD

**Issue by HariSekhon** [cirruslabs/tart#512]
I'm using Packer to launch Tart VMs for builds and when I go to the terminal tty2 to debug installations I am unable to make a pipe symbol to appear in the shell in order pass stdout from one command into stdin in another command as per usual shell semantics.

I'm using a British mac short keyboard, and this works fine to make `|` characters normally, and I'm very used to getting reset to US keyboards as it's only a couple keys transposed, but I've tried every non-alpha key with and without shift and none of them output a pipe symbol which makes working on the command line very difficult in Tart VMs.

Anybody got any suggestions for this issue?

For reference, the stuff I am doing in Tart is all in my public repo here so you can `packer build` one of the tart templates and switch to tty2 using F2 to reproduce this.

https://github.com/HariSekhon/Packer-templates

**Comment by fkorotkov** [comment]
Could you please elaborate what exactly you are doing to reproduce the issue and when you press F2? Are you trying to build a VM that is failing, then you are trying to `tart run` it and run scripts in the terminal? Is that what's happening?

Have you tried to run the same thing using `ghcr.io/cirruslabs/ubuntu:20.04` image? I've tried running:

```bash
tart clone ghcr.io/cirruslabs/ubuntu:20.04 ubuntu
tart run ubuntu
```

And was able to run `printenv | grep PATH` in the Terminal.

**Comment by HariSekhon** [comment]
I've tested pulling your `ghcr.io/cirruslabs/ubuntu:20.04` and on that I can indeed get a pipe symbol in the GUI terminal.

In my case I'm running:

```
make fedora-tart
```

And trying to get the pipe character in the F2 termainl - this works ok on Debian and Ubuntu's installer, but when I run on Fedora I can't get the pipe symbol to appear from any combination of keystrokes.

It's probably a keymap issue specific to RHEL systems, although you can see the keymap in the `installers/anaconda-ks.cfg` kickstart file is set.
