### ISSUE TITLE
tart list exclude hash of images

### ISSUE THREAD

**Issue by sanieldalib** [cirruslabs/tart#513]
Hey there! I'm trying to use `tart list` in my workflow to delete all images, with the exception of a given OCI image. However this is not possible since `tart list` lists out the image name with the tag and again with the hash.

For example, I want to delete all images besides the latest tag. I tried using  
`tart list -q | grep -v image-registry.com/imagename:latest | xargs tart delete` to delete all but the latest image, but this still deletes the hash for the `latest` tag.
```
tart list
Source Name
oci    image-registry.com/imagename:old
oci    image-registry.com/imagename:old1
oci    image-registry.com/imagename:latest
oci    image-registry.com/imagename@sha256:<hash for old tag>
oci    image-registry.com/imagename@sha256:<hash for old1 tag>
oci    image-registry.com/imagename@sha256:<hash for latest tag>
```
Is the solution here an addition to tart list to hide the hashes? Or is there another way of accomplishing this?

**Comment by edigaryev** [comment]
> Or is there another way of accomplishing this?

Does `tart list -q | grep -vE '@sha256:|image-registry.com/imagename:latest' | xargs tart delete` work for you?

**Comment by sanieldalib** [comment]
🤦‍♂️ Right. Thanks for the obvious solution. I clearly was not thinking LOL
