### ISSUE TITLE
To install macOS 14 Sonoma beta, install and open Xcode 15 beta

### ISSUE THREAD

**Issue by vitorgalvao** [cirruslabs/tart#514]
If you try to install the new macOS 14 beta with `tart create`, you’ll get an error:

> Error: A software update is required to complete the installation. Installation requires a software update.

macOS will auto-trigger a GUI which *looks* helpful but fails.
<img width="618" src="https://github.com/cirruslabs/tart/assets/1699443/46e119f1-d998-42a4-8b7e-db633d3df092">
<img width="618" src="https://github.com/cirruslabs/tart/assets/1699443/9d9f4367-d7b6-4afb-a9ea-a9cb4d336272">
<img width="618" src="https://github.com/cirruslabs/tart/assets/1699443/8f033a1d-73f9-4b2d-a1dd-0d50c12601cd">

The solution is to install Xcode beta 15 and open it at least once to finish the setup process. You can download it at https://developer.apple.com/download/all/?q=Xcode (requires logging in with your developer account).

> **Note**
> Close the issue at will, I’m making it so others who bump into the issue can find a solution fast.

**Comment by MushR00m** [comment]
Install it also to support macOS 14, have fun.
`https://developer.apple.com/services-account/download?path=/Developer_Tools/Device_Support_for_macOS_14_beta/DeviceSupport.dmg`

**Comment by pthexton** [comment]
Just to add to this, I've found that you don't need to install Xcode 15 beta to be able to create a Sonoma VM from the downloaded IPSW, you just need to download and install the Device Support dmg mentioned by @MushR00m and then creating VMs using tart (or other software using Virtualization.framework) will then work.

**Comment by KOSURUUDAYSAIKUMAR** [comment]
you can share me a video of install device support DMG file. i tried many ways but not working.

**Comment by hassaanhameed786** [comment]
how can I install on my version Version 14.0 Beta (macOS Sonoma beta)

**Comment by vitorgalvao** [comment]
Sonoma is scheduled to be release in five days, so this is no longer necessary.
