### ISSUE TITLE
Change path for passthrough directories on macOS

### ISSUE THREAD

**Issue by pinkisemils** [cirruslabs/tart#517]
Hiya, would it be possible to change the path where shared directories are mounted? 

Certain XCode projects and their Makefiles have proven to be less than capable to handle whitespace in paths. Currently, there's no way to get a mount path for the shared directory that doesn't contain whitespace since they're all mounted under `/Volumes/My Shared Files/`. 
I presume it might be a technical limitation or something that'd take significant effort to change, but I thought asking wouldn't hurt.

**Comment by fkorotkov** [comment]
Hey @pinkisemils, unfortunately it's not possible at the moment. You can try to symlink a mounted directly into some path that is more suitable for Xcode and Makefiles.

**Comment by sanieldalib** [comment]
This might be helpful @pinkisemils

https://github.com/cirruslabs/tart/blob/main/docs/quick-start.md#accessing-mounted-directories-in-macos-guests

> Tip "Changing mount location" It is possible to remount the directories after a virtual machine is started by running the following commands:
> 
> ```bash
> sudo umount "/Volumes/My Shared Files"
> mkdir ~/workspace
> mount_virtiofs com.apple.virtio-fs.automount ~/workspace
> ```
> 
> After running the above commands the direcory will be available at `~/workspace/project`

**Comment by fkorotkov** [comment]
@sanieldalib thank you for noting it here! Will close this issue then. 👌
