### ISSUE TITLE
Keyboard and mouse appear not connected after upgrade to 1.7.0

### ISSUE THREAD

**Issue by sjchmiela** [cirruslabs/tart#534]
Today I installed `tart` from Homebrew (released yesterday 1.7.2), downloaded a clean Monterey IPSW, ran:
```
tart create test --from-ipsw ~/Downloads/UniversalMac_12.6_21G115_Restore.ipsw
tart run test
```

I was surprised to see this screen. No restarting (host or guest), wiggling the cursor over the window helped.
<img width="1136" alt="Zrzut ekranu 2023-06-30 o 21 24 47" src="https://github.com/cirruslabs/tart/assets/1151041/15d04a91-5ca8-4518-8f02-719e80704f04">

After some digging around source code I found there have been recent changes to [how Tart configures keyboard and mouse on the VM](https://github.com/cirruslabs/tart/pull/524). I downgraded `tart` to 1.6.0 and… it fixed the issue!

<img width="1136" alt="Zrzut ekranu 2023-06-30 o 21 25 18" src="https://github.com/cirruslabs/tart/assets/1151041/647d2c74-fdf1-41c4-8c27-2e7d997dc595">

So it's a regression report. I'm on late 2020 M1 MBP Pro on Ventura 13.4.

Thank you for `tart`, it's awesome!!

**Comment by iby** [comment]
Howdy @fiedukow @edigaryev! I'm seeing this issue with Monterey and often with Sonoma. Mouse (Magic Mouse and touchpad) are not working. The mouse just sits at the top and not responding. The keyboard also doesn't seem do be connected.

![image](https://github.com/user-attachments/assets/3009f612-0c10-4891-97a1-c3a247fabb1e)

With Sonoma the issue happens at random. I can't say for sure, but seems like if I keep and wiggle the mouse in the window during the VM launch, it works in more cases compared to when the window is in the background during the launch.

```
tart clone ghcr.io/cirruslabs/macos-monterey-base:latest mon
tart set --display 2560x1440 mon
tart run mon
```

Happening with Tart 2.15.0 and 2.16.0. Are there any workarounds? 🤔

**Comment by edigaryev** [comment]
> Howdy @fiedukow @edigaryev! I'm seeing this issue with Monterey and often with Sonoma. Mouse (Magic Mouse and touchpad) are not working. The mouse just sits at the top and not responding. The keyboard also doesn't seem do be connected.

Possibly related to https://github.com/cirruslabs/tart/pull/843.
