### ISSUE TITLE
guest has stopped the virtual machine

### ISSUE THREAD

**Issue by jmgilman** [cirruslabs/tart#564]
Attempting to run a Linux VM:

```
❯ tart create --linux ubuntu
❯ tart run --disk ~/Downloads/ubuntu-23.04-desktop-amd64.iso ubuntu
guest has stopped the virtual machine
```

The window pops up for about a second and then disappears with the resulting message left in the terminal. I'm unable to get the installer to start.

```
❯ tart --version
1.9.1
❯ sw_vers
ProductName:		macOS
ProductVersion:		13.4.1
BuildVersion:		22F82
```

**Comment by fkorotkov** [comment]
It seems you need to try an Arm ISO.

**Comment by jmgilman** [comment]
Ah, sorry, I should have clarified I'm trying to run x86 specifically. After reading your comment, though, I realized that rosetta needs to be specified explicitly, so I tried:

```
tart run --rosetta="rosetta" --disk ~/Downloads/ubuntu-22.04.2-desktop-amd64.iso ubuntu
```

But still ran into the same issue. Is this not a supported workflow?

**Comment by fkorotkov** [comment]
You use Rosetta still in Arm guests. Rosetta integration allows to run x86 binaries inside Arm Linux VMs.

With Tart you unfortunately can't run x86 VMs on Arm.
