### ISSUE TITLE
`tart login` with `--password-stdin` doesn't strip terminating newlines

### ISSUE THREAD

**Issue by coffinmatician** [cirruslabs/tart#577]
`tart login` in interactive mode assumes that the end of the password has been reached when a new line is encountered while `tart login` with `--password-stdin` assumes that the end of the password has been reached at the EOF marker. This means that `echo "bar" | tart login --username foo --password-stdin` will not work, but `printf "%s" "bar" | tart login --username foo --password-stdin` will. I kind of (but not really) see the argument for allowing new lines in passwords, but if that is felt to be important then it seems odd to not allow them in the interactive mode.

**Comment by fkorotkov** [comment]
Which version of Tart are you using? This should be fixed in [`1.5.0`](https://github.com/cirruslabs/tart/releases/tag/1.5.0) by #486

**Comment by coffinmatician** [comment]
Oh, yes oops. This was a very old version of tart. I apologize for not being more careful reporting this bug. This does appear to be fixed. Thank you.
