### ISSUE TITLE
Tart stop is not graceful

### ISSUE THREAD

**Issue by Nezz** [cirruslabs/tart#582]
I have an issue where I run a git command on a Tart VM, then I call `tart stop` which completes in less than a second.

This sometimes leaves `.git/index.lock` files around. I'd expect tart stop to perform a graceful shutdown that waits for file operations to complete, but it completes so quickly that I don't think that happens. There is even a timeout parameter that specifies how long it should wait before forcefully terminating which defaults to 30 seconds. Should the shutdown be graceful if I don't provide that parameter?

**Comment by edigaryev** [comment]
If we were to implement the graceful shutdown, you'd have provide additional keyboard and/or mouse input to the VM (see https://github.com/cirruslabs/tart/discussions/574 for more details), which defies the point of automation.

Is running something like `sudo -S shutdown -h now` after you run your Git command is an option?

**Comment by Nezz** [comment]
I used to use `sudo shutdown -h now`, but with that I had the issue that sometimes the VM would keep running and the host machines would be unable to start VMs. I guess I could try having both `sudo shutdown -h now` and `tart stop`?

**Comment by edigaryev** [comment]
>I had the issue that sometimes the VM would keep running

Could there be still some tasks running inside of a VM at the time of running `sudo shutdown -h now` (especially tasks that have a GUI).

>I guess I could try having both sudo shutdown -h now and tart stop?

Normally a shutdown from inside of a VM should be enough (see above), what you can try instead is to run `sync` before `tart stop` to see if it results in a more consistent disk state.

**Comment by Nezz** [comment]
Thanks, I'll try `sync` because those lock files are left there quite rarely, but it's a recurring issue.
