### ISSUE TITLE
Tart packer plugin removing recoverypartition leads to inability to update vm os normally

### ISSUE THREAD

**Issue by cosmoshepcat** [cirruslabs/tart#595]
Asking/Putting this here to confirm this behavior and what we are seeing.  We currently have a workflow where a vanilla vm is created manually with a small disk.  We manually set a few settings in addition to the creation of user through the normal guided install process.

We then have a base stage in packer that expands the disk and installs all core software like xcode etc.   We also have another packer setup that will pull the base image created previously and then apply highly custom things to them.  Idea being we would only be building these highly custom images regularly and every image would come from the same base.

Recently noticed when trying to add cli softwareupdate to the packer pipeline that it would spit out an error about personalization; missing recovery volume etc.   No amount of cli; gui software update; or even downloading the full installer and running that would update this vm.   Just for giggles we did try the vanilla image not touched by packer and softwareupdate works fine.

I see the section in the packer plugin GO code that removes the recoverypartition--> I am assuming this is required in order to be able to do the packer volume resizing?  If so then we just need to document our process and manually create a new vanilla image 4 times a year or whenever to get security/OS updates if this is the case.   Would be nice to be able to do it in packer but do not see how currently.

**Comment by fkorotkov** [comment]
Hey @cosmoshepcat, this is intentional in order to support resizing as you noted. Plus it saves bandwidth when you pull/push images from remote.

Please check out templates where we automated [creation of the vanilla images from IPSW files](https://github.com/cirruslabs/macos-image-templates/blob/master/templates/vanilla-ventura.pkr.hcl).

**Comment by cosmoshepcat** [comment]
Thanks for the clarification.
