### ISSUE TITLE
Problems with tart login authenticating

### ISSUE THREAD

**Issue by ameusel** [cirruslabs/tart#596]
Hi, I am trying to push a tart image to a container registry but I am unable to authenticate with any,

So far I have tried, Nexus, GitLab, and Docker Hub, in each case I can successfully `docker login` but `tart login` always returns an error

```
$ docker login index.docker.io
Username: 845267208947
Password:
Login Succeeded 👍
```

```
$ tart login index.docker.io
User: 845267208947
Password:
Error: Failed(message: "Keychain failed to add item: The authorization was denied.") 👎
```

None of the alternate methods from [Tart login authentication issues #483](https://github.com/cirruslabs/tart/issues/483) are working either;

```
$ echo $PASSWORD | tart login index.docker.io --username 845267208947 --password-stdin
Error: Failed(message: "Keychain failed to add item: The authorization was denied.")
```

```
$ echo -n $PASSWORD | tart login index.docker.io --username 845267208947 --password-stdin
invalid credentials: AuthFailed(why: "received unexpected HTTP status code 401 while retrieving an authentication token", details: "{\"details\":\"incorrect username or password\"}\n")
```

```
export TART_REGISTRY_USERNAME=845267208947 
export TART_REGISTRY_PASSWORD=PASSWORD
$ tart login index.docker.io
Error: Failed(message: "Keychain failed to add item: The authorization was denied.")
```

Is there any debugging/logging I can do locally to try and identify the problem?

I am running **tart version 1.12.0** from a:

```
ProductName: macOS
ProductVersion: 13.5
BuildVersion: 22G74
Model Name: Mac mini
Model Identifier: Macmini9,1
Model Number: MGNR3B/A
Chip: Apple M1
Total Number of Cores: 8 (4 performance and 4 efficiency)
Memory: 8 GB
System Firmware Version: 8422.141.2
OS Loader Version: 8422.141.2
```

**Comment by edigaryev** [comment]
1. Are you running Tart from a SSH connection (or similar, basically in an environment where GUI pop-ups from macOS are not displayed)?
2. Have you done any security/Keychain-related settings on that host?
3. Have you tried running `tart login` on another/clean macOS machine?

Also note that when using `TART_REGISTRY_USERNAME` and `TART_REGISTRY_PASSWORD`, no `tart login` is needed:

```
export TART_REGISTRY_USERNAME=845267208947 
export TART_REGISTRY_PASSWORD=PASSWORD
$ tart login index.docker.io
Error: Failed(message: "Keychain failed to add item: The authorization was denied.")
```

You can go straight to `tart push`/`tart pull`/etc.

It's also strange that in your example the `tart login` doesn't ask for a username/password (were these lines redacted from your code snippet?), which it should, as it ignores `TART_REGISTRY_USERNAME` and `TART_REGISTRY_PASSWORD` completely.

**Comment by griels** [comment]
Hi, I'm working with @ameusel :)

1. we are trying to do this an automated way, so it is being done from a Gitlab shell runner, so via SSH. Once we did this from a graphical terminal, it worked (we just discovered this)
2. No
3. Yes, on the same machine, interactively, this works. We haven't tried the echo method locally.

So, we've got it working manually, but want to do it in an automated way. The stumbling block seems to be the login seems to need to be from a GUI machine so that keychain access is granted. Is there a way to fully automate this process so GUI access isn't required?

Thanks

**Comment by edigaryev** [comment]
>Is there a way to fully automate this process so GUI access isn't required?

You can just set `TART_REGISTRY_USERNAME` and `TART_REGISTRY_PASSWORD` for each invocation of `tart clone`/`tart pull`/`tart push`/etc. and no `tart login` would be necessary.

Also check out the [GitLab Tart Executor](https://github.com/cirruslabs/gitlab-tart-executor) which automates much of these things 🙌

**Comment by ameusel** [comment]
Thanks for the help here @edigaryev, the problem went away after the first time we ran the command from the desktop gui, there wasn't a popup or any interactive prompt, but it did resolve itself
