### ISSUE TITLE
CredentialTooLong password should contain no more than 255 characters

### ISSUE THREAD

**Issue by finestructure** [cirruslabs/tart#617]
I'm trying to push an image to AWS ECR but the tokens they generate (via `aws ecr get-login-password --region us-east-2`) are too long to be used in `tart login ...`:

```
Error: CredentialTooLong(message: "password should contain no more than 255 characters")
```

Is there a way to get this to work with ECR? Is ECR even capable of hosting tart's images?

**Comment by fkorotkov** [comment]
While https://github.com/cirruslabs/tart/pull/618 will fix the issue for `tart login` please take a look at #592 which allows adding the following to `~/.docker/config.json`:

```json
{
  "credHelpers": {
    "(.*).dkr.ecr.(.*).amazonaws.com": "ecr-login"
  }
}
```

This way Tart itself will use https://github.com/awslabs/amazon-ecr-credential-helper (please don't forget to install it via `brew install docker-credential-helper-ecr`) to generate one time token on the fly without persisting in the Keychain.

**Comment by finestructure** [comment]
Ah, that's good to know. Thanks for the quick response, @fkorotkov !

Can I just "abuse" this issue for a slightly related question?

I've tried pushing my image (size 15 GB as per `tart list`) to two different registries (Gitlab and Azure) and both times it stops at 20%:

```
➜  ~ tart push spi-ventura swiftpackageindex.azurecr.io/spi-ventura:0.0.1
pushing spi-ventura to swiftpackageindex.azurecr.io/spi-ventura:0.0.1...
pushing config...
pushing disk... this will take a while...
20%
[1]    70537 killed     tart push spi-ventura swiftpackageindex.azurecr.io/spi-ventura:0.0.1
```

The Azure registry has 500GB quota, so it shouldn't be limited by the registry. Is there something else that might limit pushes?

**Comment by fkorotkov** [comment]
Did you kill the `tart` process? Or it failed?

**Comment by finestructure** [comment]
I've just run it with that setting and it died again at 20%. Hope that helps!

**Comment by edigaryev** [comment]
> I've just run it with that setting and it died again at 20%. Hope that helps!

Unfortunately we didn't the report, the Tart process seems to receive the `SIGKILL` straight away.

One likely option is memory shortage.

Some questions:

1. Which Tart version are you running?

2. How much memory does your system have?

3. Is there anything in the `Console.app` relating to Tart after it gets killed?

**Comment by finestructure** [comment]
> One likely option is memory shortage.

That was it, I believe. The system has 16GB of RAM and was running a tart VM with 16GB assigned while I was running the push.

While I didn't see memory pressure in the Activity Monitor when it failed before it _did_ now succeed when I re-ran the push _without_ the VM running.

Thanks for your help!
