### ISSUE TITLE
feat(volumes): Is there a way to increase the volume size for the vm?

### ISSUE THREAD

**Issue by theonetheycallneo** [cirruslabs/tart#619]
Is there a way to increase the volume size for the vm?

Perhaps an undocumented cli param or steps to increase the default hard drive volume size?

**Comment by fkorotkov** [comment]
You can either use [Packer plugin](https://github.com/cirruslabs/packer-plugin-tart) or use [these manual steps](https://github.com/cirruslabs/tart/issues/17#issuecomment-1439367869).

**Comment by theonetheycallneo** [comment]
Thank you!

**Comment by theonetheycallneo** [comment]
@fkorotkov What about RAM?  Is there a way to increase or set the VM's memory size?

**Comment by theonetheycallneo** [comment]
@fkorotkov Thank you!
