### ISSUE TITLE
running on Moneterey (host)?

### ISSUE THREAD

**Issue by umlaeute** [cirruslabs/tart#633]
i'm currently stuck with a macOS 12.6.7 "Monterey" host, and would like to use Tart on this machine.

Unfortunately, it fails to install:

```sh
$ brew install --verbose --verbose  cirruslabs/cli/tart
tart: This software does not run on macOS versions older than Ventura.
Error: tart: An unsatisfied requirement failed this build.
```

it seems there are no homebrew formulae for older versions of `tart` available which i would be able to install.

I then tried to do a manual installation and download the binaries from the github releases, but those fail as well.

the tart/2.1.0 binary fails with 
> '/usr/lib/libswift_StringProcessing.dylib' (no such file)

which is likely an indication that the binary indeed requires features not yet present on Monterey.
However, older versions i've tried (2.0.0, 1,12.0, 1.11.0) are just killed by zsh (similar to #498)
```sh
% ./Tart_1.11.0.app/Contents/MacOS/tart  
zsh: killed     ./Tart_1.11.0.app/Contents/MacOS/tart
```

ideas, hints?

**Comment by fkorotkov** [comment]
Not sure why your `./Tart_1.11.0.app/Contents/MacOS/tart` is getting killed. I think something like that might work:

```shell
brew tap cirruslabs/cli
cd "$(brew --prefix)/Library/Taps/cirruslabs/homebrew-cli"
git checkout -b tart-1.11.0 8a45ecd4e875da346bd099c30a90a228b913e90f
brew install cirruslabs/cli/tart
brew pin cirruslabs/cli/tart
```

**Comment by fkorotkov** [comment]
The latest version for Ventura and Sonoma supports running all Apple Silicon available versions. We'll add such a table in the future if needed.
