### ISSUE TITLE
Tart v2.1.0 pull killed by ZSH

### ISSUE THREAD

**Issue by sanieldalib** [cirruslabs/tart#634]
When pulling an image (new image format) using Tart v2.1.0,  the pull process gets killed by zsh around 95%+. This does not happen every time, but very frequently and across multiple machines.

```
tart pull tart_bambooagent-macos13:v1836
pulling tart_bambooagent-macos13:v1836...
pulling manifest...
pulling disk (51.7 GB compressed)...
95%
zsh: killed  tart pull 

~ % tart --version
2.1.0
```

Any clues why this is happening?

**Comment by fkorotkov** [comment]
We've seen similar reports when the host doesn't have enough memory for Tart to temporary store layers in memory. Do you have a VM running concurrently or something else that can consume memory?

**Comment by sanieldalib** [comment]
I've seen the error with both a running VM and a stopped one. I'll try deleting it and pulling again. Is it a concern that the image size is greater than the memory available on the machine?

**Comment by fkorotkov** [comment]
It shouldn't be a concern. Tart only needs around a 100Mb memory to uncompress things in memory.

Another option might be that your system doesn't have enough disk space. I think you have Tart's auto pruning disabled via `TART_NO_AUTO_PRUNE` environment variable.

`Console.app` might contain reports of why `tart` was killed by the OS.

**Comment by sanieldalib** [comment]
I couldn't find anything in the `Console.app`, but I will take a closer look if it happens again. We have plenty of disk space as well.

I was able to get it working fairly consistently by first nuking the `~/.tart` directory. This seems a bit heavy handed, but it worked for me across a number of hosts. 

Prior to Tart v2, we never experienced this issue. Is it related to the new image format?

**Comment by edigaryev** [comment]
> When pulling an image (new image format) using Tart v2.1.0, the pull process gets killed by zsh around 95%+. This does not happen every time, but very frequently and across multiple machines.

Which macOS version are you using on these host machines, by the way?

> I couldn't find anything in the `Console.app`, but I will take a closer look if it happens again. We have plenty of disk space as well.

They should be in the `Crash Reports` section and named `tart`.

**Comment by sanieldalib** [comment]
Dug into this some more and found the following log:
```
sudo dmesg | grep tart

[10193422.874707]: Sandbox apply: wifip2pd[67709] <bytes>Sandbox: bluetoothd(91503) deny(1) mach-lookup com.apple.private.corewifi-xpclow swap: killing largest compressed process with pid 67402 (tart) and size 94906 MB
```

**Comment by fkorotkov** [comment]
Closing until there is more info.
