### ISSUE TITLE
Capturing Keyboard in the VM

### ISSUE THREAD

**Issue by unikzforce** [cirruslabs/tart#636]
Can you please add the capability to lock in the keyboard into the vm and the ability to unlock the keyboard.

It would be very useful if one could make the vm fullscreen and then all keyboard shortcuts like ( CMD + Tab ) could be captured by the guest, instead of the host

**Comment by menduz** [comment]
https://developer.apple.com/documentation/coregraphics/cgevent/1455445-tapenable
or
https://developer.apple.com/documentation/coregraphics/cgevent/1456048-tapcreateforpid
should work, I know the former needs elevated accessibility permissions but it can intercept and stop bubbling the events (like Cmd+q) down to the host OS.

See https://gist.github.com/indragiek/4166038 and https://github.com/koekeishiya/skhd/tree/master

**Comment by fkorotkov** [comment]
Thank you all for the feedback! In Tart 2.3.0 you can do `tart run --capture-system-keys` which will force the Tart window to capture most of the system keys.
