### ISSUE TITLE
sshpass is no longer available on brew

### ISSUE THREAD

**Issue by sridhar-vadlamani-ck** [cirruslabs/tart#661]
<img width="712" alt="image" src="https://github.com/cirruslabs/tart/assets/26975170/cd3c60a3-2066-4964-8ce7-f1716ae60ad8">

```
Warning: No available formula with the name "sshpass". Did you mean sshs?
==> Searching for similarly named formulae and casks...
==> Formulae
sshs

To install sshs, run:
  brew install sshs
```

**Comment by fkorotkov** [comment]
That's unfortunate! Seems the only option for us to provide a secure way for sshpass is to replicate the formula under our tap. See https://github.com/cirruslabs/homebrew-cli/pull/2. Will update docs in case we'll go this way.
