### ISSUE TITLE
Question: Is it possible to run Tart Sonoma images on Linux?

### ISSUE THREAD

**Issue by jmandel1027** [cirruslabs/tart#665]
Hi there,

I work at Square and am investigating Tart with the other iOS DX teams here. I had a bit of a noob question, would it be possible to run a Sonoma Tart image (<3 the packer plugin btw), on a linux box? If we could run Tart VMs on Graviton linux boxes that still allow for devs to use XCode & Simulators as they normally would it'd be a huge win on our end. 

I expect this isn't possible but just wanted to double check, we're already investigating Mac support with Tart for our Buildkite Infra and wanted to see if we can leverage the linux env's we've been rolling with. It's not the end of the world if there's mac limitations preventing this, but wanted to double check 

: )

**Comment by fkorotkov** [comment]
Unfortunately Tart only works on macOS running on Apple Silicon. It's a limitation of the underlying virtualization framework. Plus Apple's EULA prohibits from running macOS on non-Apple hardware. 😪

PS feel free to loop us into the conversations. We'd be happy to assist with the evaluation and, in case something is missing, to help and implement missing parts. 

FYI our [AMI images for EC2 Macs](https://aws.amazon.com/marketplace/pp/prodview-qczco34wlkdws) have Tart pre-configured to work with ECR through instance metadata and couple other tweaks for optimal integration within AWS.

**Comment by jmandel1027** [comment]
Thanks for the quick answer @fkorotkov! Yeah that's what I expected re: eula. Absolutely! I've been jamming with Tim on some of this stuff and just starting to think about creating a virtualized "golden path" that keeps security happy like we've done in Linux land with our Buildkite platform.

I deff will be circling back here! : ~ )
