### ISSUE TITLE
Unable to install linux using Ubuntu ISO files

### ISSUE THREAD

**Issue by wegotoeleven** [cirruslabs/tart#672]
Hey folks. I'm not sure that this is a Tart issue specifically as I'm unable to manually mount Ubuntu ISO files on macOS, however when I try to create a Linux VM using the following commands, Tart immediately exists when attempting to run the VM with the Ubuntu disk.
```
user@host ~ (zsh) % tart create --linux --disk-size 100 ubuntu_22.04.3
user@host ~ (zsh) % tart run --disk /Users/stephenwb/Downloads/ubuntu-22.04.3-live-server-amd64.iso ubuntu_22.04.3
guest has stopped the virtual machine 
```
Is anyone else coming across this issue? Am I holding it wrong?

**Comment by fkorotkov** [comment]
Hey @wegotoeleven, it seems you have an `amd64` iso. Couple you please try an `arm64` one?

**Comment by fkorotkov** [comment]
No worries! You are not the first one that used a wrong architecture. Seems by default `amd64` is suggested for downloading. I think we can do better on the Tart side. Improving the UX in #673.
