### ISSUE TITLE
sshpass tap formula is not available

### ISSUE THREAD

**Issue by pythoninthegrass** [cirruslabs/tart#678]
Per #661, tried the following on macOS 12.7.1 (21G920):
```bash
λ brew install cirruslabs/cli/sshpass
Warning: No available formula or cask with the name "cirruslabs/cli/sshpass". Did you mean cirruslabs/cli/tart, cirruslabs/cli/orchard, cirruslabs/cli/cirrus or cirruslabs/cli/softnet?
```
Know that Ventura and up are supported for the current tart version, but okay with a reduced feature set (e.g., no mounts, wonky `ShouldBeAtLeastOneLayer` for *nix images, etc) on Monterey. For now.

This shouldn't be OS-specific based on the [formula](https://github.com/cirruslabs/homebrew-cli/blob/master/sshpass.rb) anyway as it just installs an upstream tar gunzip file.

**Comment by fkorotkov** [comment]
Have you pinned `cirruslabs/cli` tap by any chance? `sshpass` formula was added only recently so you might not have it updated.

**Comment by pythoninthegrass** [comment]
That was it! Thanks @fkorotkov
