### ISSUE TITLE
Document location of VMs on host

### ISSUE THREAD

**Issue by dan-snelson** [cirruslabs/tart#68]
First, thanks for all your hard work; I'm really enjoying testing Tart.

In skimming the ReadMe, I didn't see mention of the ` ~/.tart/` directory and, specifically, of the ` ~/.tart/vms` directory.

Please consider documenting the location of VMs on the host.

**Comment by dan-snelson** [comment]
Superb!

https://snelson.us/2022/05/testing-sideways-jamf-pro-enrollments-with-tart/

**Comment by fkorotkov** [comment]
Thank you, @dan-snelson! Hopefully we'll find out a way to support #59.
