### ISSUE TITLE
Unable to create macOS VM from IPSW file

### ISSUE THREAD

**Issue by hepivax** [cirruslabs/tart#690]
I've recently upgraded to Sonoma 14.2, since then I cannot create VM from IPSW file (I was able to use the very same IPSW file)

```
tart create macos --from-ipsw sonoma-14-1.ipsw
Installing OS...
0%
Error: An error occurred during installation. Installation failed.
```

In `system.log` there is a `Declined to authorize this DFU file on this device for this user.` message:
```
com.apple.Virtualization.Installation[19885]: Entered:_AMDFUDeviceConnected, libusbrestore-device:0x0x127f36640
MobileDeviceUpdater[13484]: Entered:_AMDFUDeviceConnected, libusbrestore-device:0x0x13b75fb00
UARPUpdaterServiceDisplay[780]: Entered:_AMDFUDeviceConnected, libusbrestore-device:0x0x122022330
AMPDeviceDiscoveryAgent[1468]: Entered:_AMDFUDeviceConnected, libusbrestore-device:0x0x14b913810
com.apple.Virtualization.Installation[19885]: Declined to authorize this DFU file on this device for this user.
com.apple.Virtualization.Installation[19885]: Entered:_AMDFUDeviceDisconnected, libusbrestore-device:0x0x127f36640
com.apple.Virtualization.Installation[19885]: Entered:__thr_AMDFUDeviceDisconnected, libusbrestore-device:0x0x127f36640
MobileDeviceUpdater[13484]: Entered:_AMDFUDeviceDisconnected, libusbrestore-device:0x0x13b75fb00
AMPDeviceDiscoveryAgent[1468]: Entered:_AMDFUDeviceDisconnected, libusbrestore-device:0x0x14b913810
MobileDeviceUpdater[13484]: Entered:__thr_AMDFUDeviceDisconnected, libusbrestore-device:0x0x13b75fb00
UARPUpdaterServiceDisplay[780]: Entered:_AMDFUDeviceDisconnected, libusbrestore-device:0x0x122022330
AMPDeviceDiscoveryAgent[1468]: Entered:__thr_AMDFUDeviceDisconnected, libusbrestore-device:0x0x14b913810
UARPUpdaterServiceDisplay[780]: Entered:__thr_AMDFUDeviceDisconnected, libusbrestore-device:0x0x122022330
```

**Comment by edigaryev** [comment]
>Declined to authorize this DFU file on this device for this user.

This doesn't look like a Tart's issue to me.

What is the SHA-256 hash of the `sonoma-14-1.ipsw` (you can get it by installing `coreutils` from Homebrew and running `sha256sum sonoma-14-1.ipsw`)?

What Mac model are you running on? Have you done anything special to the system?

A quick googling shows that this also might be due to [network/DNS blocking](https://support.apple.com/en-ca/HT201442).

**Comment by hepivax** [comment]
- SHA-256 is `9d9195a51fb45733c778764ba14e1d67c43981251ba6a795b79a6026fcee31ca` - the file was downloaded directly from Apple CDN.
- MacBook Pro 14" 2023 (M2 Pro Chip) with Sonoma 14.2
- The article you've referred mention `This device isn't eligible for the requested build` while the error was `Declined to authorize this DFU file on this device for this user` - are you sure it is the same issue?

**Comment by hepivax** [comment]
Thanks @edigaryev - it appears that the image is corrupted, I was able to install other image.
What is the recommended source for official IPSW images?

**Comment by edigaryev** [comment]
>What is the recommended source for official IPSW images?

Tart only knows about `--from-ipsw=latest`, which will get a current macOS version IPSW.

Aside from that, there are other websites like https://ipsw.me/ that collect both current and past IPSWs.

**Comment by fkorotkov** [comment]
Another note for future researches to download files for ["Apple Virtual Machine" device](https://ipsw.me/VirtualMac2,1).
