### ISSUE TITLE
How to uninstall tart?

### ISSUE THREAD

**Issue by Jackakhan** [cirruslabs/tart#699]
I installed tart, but cant figure out how to access it. Attempted to delete it but cant locate its file path.

All i can find is a folder labeled tart that has what looks like an empty app labeled "tart" 12mb, and a text file titled "license" that is 2 mb. The description online says it should take up 25gig.

Any help would be greatly appreciated.

![Screenshot 2024-01-10 at 7 55 31 AM](https://github.com/cirruslabs/tart/assets/156201183/f26685f4-dabc-4526-b87b-17262bfd2e74)

**Comment by edigaryev** [comment]
>I installed tart

How did you installed it in the first place?

For Homebrew, uninstalling is as simple as:

```shell
brew uninstall cirruslabs/cli/tart
```

**Comment by Jackakhan** [comment]
I'm really not sure.. I believe I went to https://tart.run/. Then copied and pasted a code into terminal.

I'm sorry, I'm really unfamiliar with these kinds of things. What is homebrew?

**Comment by edigaryev** [comment]
> I'm really not sure.. I believe I went to https://tart.run/. Then copied and pasted a code into terminal.

If you've followed [these instructions](https://tart.run/quick-start/), then the command I've posted above should work for you.

**Comment by edigaryev** [comment]
> Should i paste the command you sent into terminal?

Yep, check out the [How to Uninstall Packages with Homebrew](https://osxdaily.com/2018/07/29/uninstall-packages-homebrew-mac/) article by OSXDaily for more details.

**Comment by Jackakhan** [comment]
I pasted the command and received this message: "-bash: brew: command not found"

Does that means I didn't instal it correctly?

**Comment by edigaryev** [comment]
It's weird that your default shell is Bash, because the default one on macOS is Zsh.

Is there a chance you've removed Homebrew after installing Tart?

You can also try invoking the Homebrew by an absolute path:

```
/opt/homebrew/bin/brew uninstall cirruslabs/cli/tart
```

**Comment by Jackakhan** [comment]
Its apple m2. 

As i said before, I don't know what home brew is. 

Same result with the new code you sent me

**Comment by edigaryev** [comment]
> As i said before, I don't know what home brew is.

Assuming that you've simply downloaded the archive from [releases page](https://github.com/cirruslabs/tart/releases), you can just remove the directory containing `LICENSE` and `tart` files, that's it.

**Comment by Jackakhan** [comment]
Go it. Thank you.

So If i wanted to use tart correctly, I'd need to instal hombrew, and then run the command "brew install cirruslabs/cli/tart
tart clone ghcr.io/cirruslabs/macos-sonoma-base:latest sonoma-base
tart run sonoma-base".

Is that correct?

**Comment by Jackakhan** [comment]
Got it, ok i'll try to find info on what homebrew is, and how to instal it.

Thank you for all your help!
