### ISSUE TITLE
Cannot start VM with error: "virtual machine's network attachment has been disconnected"

### ISSUE THREAD

**Issue by Lutzifer** [cirruslabs/tart#72]
After creating a VM using

```
tart create --from-ipsw=latest monterey-vanilla
```

starting it using

```
tart run monterey-vanilla  
```

fails with the error

```
"virtual machine's network attachment has been disconnected"
```

Guest: 21E258.ipsw
Host: 12.3.1 (21E258), MacBook Pro (16-inch, 2021), Apple M1 Max

**Comment by Lutzifer** [comment]
It works if I use an USB Dongle to connect to LAN.

**Comment by edigaryev** [comment]
> #77 causes an infinite loop of re-attachments, but I can setup the OS then (without network)

Thanks for checking this! Looks like adding the re-attachment logic would do nothing useful to fix the issue as the error cause doesn't seem to be intermittent.

> I cannot see, what VZNATNetworkDeviceAttachment is using under the hood, but the only available device for VZBridgedNetworkInterface is my wifi.

It's using [vmnet](https://developer.apple.com/documentation/vmnet) under the hood most likely. This API manifests itself in `ifconfig` output as `vmenetX` interfaces connected to `bridge100` normally.

**Comment by edigaryev** [comment]
@Lutzifer could you also check the https://github.com/cirruslabs/tart/pull/80 please? Does the network work with it?

It ignores all errors with the assumption that the `Virtualization.Framework` may re-connect the attachment itself.

**Comment by Lutzifer** [comment]
network does not work with #80 

I can see vmenetX appear when I run tart, but do not see bridge100

Would be interesting to test this against another MacBookPro18,3 to see if it is only a config issue on my side.
Will also try later today when I have upgraded to macOS 12.4 to see if this changes anything.

**Comment by Lutzifer** [comment]
Ok, I found the source of the problem:

I had enabled both internet sharing and air play receiver in the sharing settings.
After disabling both of them, it worked. My guess: Internet Sharing was enabled with a port that was no longer available (USB-Ethernet Dongle) and kept the NAT Service busy.

Thanks for all the help!

**Comment by fkorotkov** [comment]
Wow. Glad you found the issue!
