### ISSUE TITLE
No able to sign in with Apple ID

### ISSUE THREAD

**Issue by samirski** [cirruslabs/tart#722]
Recently I've come across this solution and I'm very excited as it opens up a lot of opportunities which were not available before. However I'm not able to sign in using apple id, getting verification failed message. I've tried using my existing apple id and created a new one (on a separate physical machine) still same result. To be able to download software from apple store logic is required and I'm not sure if this is something on my end or an expected behavior. 

I'm using ghcr.io/cirruslabs/macos-sonoma-base:latest on MacBook Pro M1 Pro

Thanks!

**Comment by fkorotkov** [comment]
Unfortunately it's not supported because of limitation form Apple.

**Comment by samirski** [comment]
@fkorotkov thanks for a quick response. Looks like I'd need to find a workaround for that

**Comment by kingo132** [comment]
> Unfortunately it's not supported because of limitation form Apple.

Could you explain the reason a little bit more? so I can try to find if there is any way workaround

**Comment by fkorotkov** [comment]
@kingo132 this is a limitation of `Virtualization.Framework`. There is some discussion [here](https://developer.apple.com/forums/thread/707682).

**Comment by thermoworker** [comment]
I'm running into this same issue. I understand the limitation is imposed by Apple. But maybe I could explain my use case and see if anyone from the community has experience that might help me.

I think I've got everything set up within the VM to be able to properly build our application in Xcode except, the one thing holding me back is being able to configure the Signing & Capabilities section. These permissions are tied to my Apple ID. So, without this ability, I don't see how I can build/deploy our application to the App Store.

Does anyone know a work around for this problem? I know Apple isn't allowing signing into Apple ID from within the Virtualization Framework, but maybe someone has experience being able to configure the "Signing & Capabilities" section without an Apple ID?

**Comment by fkorotkov** [comment]
@thermoworker not sure if it's the same, but Tart itself uses [elevated entitlements](https://github.com/cirruslabs/tart/blob/3f17884ac2bdba56f5688537aa6da4d14533e3f4/Resources/tart-prod.entitlements#L5-L6) and we had to [manually add our certificate to KeyChain](https://github.com/cirruslabs/tart/blob/3f17884ac2bdba56f5688537aa6da4d14533e3f4/.cirrus.yml#L82-L87).

Building and releasing images should be possible without login in with your Apple ID on macOS level.

**Comment by williamtheaker** [comment]
[Using iCloud with macOS virtual machines](https://developer.apple.com/documentation/virtualization/using_icloud_with_macos_virtual_machines?language=objc)

**Comment by fkorotkov** [comment]
Yes! 👏 It doesn't work for the current seed but will be enabled in the next ones. Once we can verify it's working we'll close the issue as completed.

**Comment by matzuk** [comment]
@fkorotkov hey!
Maybe I did something wrong, but I can't use Apple Login.
Host machine - 15.1 Beta (24B5035e).
Virtual machine - macos-sequoia-vanilla:15.1-beta-3
Running command: `tart run macos-sequoia-vanilla:15.1-beta-3`
Tart version: 2.18.1
<img width="915" alt="Screenshot 2024-09-12 at 11 07 40" src="https://github.com/user-attachments/assets/7e1580e6-dff8-4221-9bff-79bb5bb93126">

**Comment by matzuk** [comment]
@edigaryev hmm..
The host machine is Sequoia, too. The VM starts, and it works. But Apple login fails.

**Comment by edigaryev** [comment]
> The host machine is Sequoia, too. The VM starts, and it works. But Apple login fails.

I think this has to do with the host machine's version on which the VM image was built and not on which it is being ran.

**Comment by matzuk** [comment]
Interesting.
I've built the virtual machine on my host using https://github.com/cirruslabs/tart/issues/883#issuecomment-2273236519 comment. The OS version of the host and the VM are the same.
<img width="886" alt="Screenshot 2024-09-12 at 17 14 49" src="https://github.com/user-attachments/assets/b202967f-a89e-4c2a-86d7-4cb689af9d5c">
The result is the same. I can't Apple Login.

**Comment by lucasfernog-crabnebula** [comment]
Works on my end after updating to macOS sequoia stable and building from a fresh IPSW (the prebuilt image from tart did not work)

**Comment by Destrocamil** [comment]
@lucasfernog-crabnebula fresh IPSW is same version as your host?
I can't login :/

**Comment by samirski** [comment]
I agree with @lucasfernog-crabnebula, building a a VM image from a fresh IPSW does work and I'm also able to sign in using Apple ID. @fkorotkov do you know if sign in to App Store should be supported as well? I'm getting an unknown error while trying to do so. I can download/install Xcode using xcodes with brew where I also need to provide my apple id credentials and that works. Since Xcode if offered through App Store, I'm wondering how xcodes can pull it off while I'm getting an error while trying to install this directly

**Comment by nathreed** [comment]
xcodes is probably logging in to developer.apple.com/download, which is just a web login and not the App Store.
