### ISSUE TITLE
Cloud-Init support?

### ISSUE THREAD

**Issue by praveenperera** [cirruslabs/tart#725]
I'd like to make a feature request to support `cloud-init`. That would let me develop locally and make the transition to production on cloud VMs very smooth.

**Comment by edigaryev** [comment]
Hello Praveen,

You can already use `cloud-init` by mounting a [NoCloud](https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html)-compliant disk image using `tart run --disk`

We [use this method to create Linux images](https://github.com/cirruslabs/linux-image-templates/blob/main/cloud-init.pkr.hcl) for Tart and Vetu.

**Comment by fkorotkov** [comment]
And here is how you generate the disk:

https://github.com/cirruslabs/linux-image-templates/blob/1b488639daa9dbe671add2bca0306e287f99d9a2/.cirrus.yml#L60-L63

**Comment by praveenperera** [comment]
Thank you!
