### ISSUE TITLE
Programmatically obtain bridge interface IP

### ISSUE THREAD

**Issue by bossprocedure** [cirruslabs/tart#726]
I'd be great for scripting purposes to be able to obtain the IP of the bridge interface used by Tart. :)

**Comment by fkorotkov** [comment]
Do you mean getting accurate `tart ip`? You can use `arp` resolver with `--net-bridged`:

```
tart run  --net-bridged="Wi-Fi" sonoma-base
tart ip --resolver=arp sonoma-base
```

**Comment by bossprocedure** [comment]
The bridge interface on the host machine that Tart uses. It's currently named something along the lines of `bridge100`, so it's hard to programmatically determine which one it is.

There is of course a hack-around of launching a VM, getting its IP and figuring it out based on that, but that hinges on the VM having correctly configured networking (not always the case) and it presents a significant overhead in the context of a scripting workflow.

**Comment by fkorotkov** [comment]
I believe a new interface is created upon launching a VM so there is no way to know it in advance. You can see output of `ifconfig` before and after launch of the VM and see a new interface is added. Will that work for you use case?

**Comment by bossprocedure** [comment]
The specific use case I have is binding a web server to the bridge interface on the host, in order to serve resources over HTTP to the VM that are used during the installation process, without exposing the web server to other networks. This happens as part of an automated process and is a pretty common pattern in DevOps. Think cloud-init and similar.

**Comment by fkorotkov** [comment]
If you are using Packer plugin you can look at [HTTP server configuration](https://developer.hashicorp.com/packer/integrations/cirruslabs/tart/latest/components/builder/tart#http-server-configuration) otherwise there is also a way to [connect to service running on the host](https://tart.run/faq/#connecting-to-a-service-running-on-host) via NAT. Does either of the options work for you?
