### ISSUE TITLE
Error: UnsupportedArchitectureError() on Mac M1

### ISSUE THREAD

**Issue by Villafruela** [cirruslabs/tart#729]
Hi,

I've installed tart with brew and it works.

When i try to install any of the linux repo of the Quick Start Guide (debian, ubuntu, or fedora) i got this error message : 
`Error: UnsupportedArchitectureError()`

I'm using a macbook air M1 / 16GO of RAM under Sonoma

Thanks for any help

**Comment by fkorotkov** [comment]
Did you happen to install an Intel version of Tart?

**Comment by Villafruela** [comment]
Nope, all the commands in the terminal works, it's only when i do :
`tart run nameofmydistro` that i get the error message... (wich is quite odd, i understand...)
i cant also do a 
`tart --help `

**Comment by Villafruela** [comment]
yes i followed the tutorial and used Homebrew.
version is 2.5.0

**Comment by Villafruela** [comment]
Oh i see, does that mean that the ones in the quick start guide are not for arm processor (that would be odd as tart is for Mx Apple Silicon) ?

i've tried the 3 linux :
ghcr.io/cirruslabs/ubuntu:latest
ghcr.io/cirruslabs/debian:latest
ghcr.io/cirruslabs/fedora:latest

none of them worked.

**Comment by edigaryev** [comment]
>i've tried the 3 linux

These are for `arm64`, so the only remaining option I see is that you've somehow installed `amd64` version of Tart, as @fkorotkov suggested.

What is the output of:

```
file /opt/homebrew/Cellar/tart/2.5.0/libexec/tart.app/Contents/MacOS/tart
```

...shows?

**Comment by Villafruela** [comment]
Hi thanks for helping me solve that problem. I got this : 
/opt/homebrew/Cellar/tart/2.5.0/libexec/tart.app/Contents/MacOS/tart: cannot open `/opt/homebrew/Cellar/tart/2.5.0/libexec/tart.app/Contents/MacOS/tart' (No such file or directory)
So i located tart wich is there on my computer :
/usr/local/Cellar/tart/2.5.0/libexec/tart.app/Contents/MacOS/tart.
the file command return this : 
/usr/local/Cellar/tart/2.5.0/libexec/tart.app/Contents/MacOS/tart: Mach-O 64-bit executable x86_64

**Comment by edigaryev** [comment]
@Villafruela it's likely that you've installed Tart using an `amd64` version of Homebrew.

`brew config` might reveal some additional details

You might consider [uninstalling Homebrew](https://github.com/homebrew/install?tab=readme-ov-file#uninstall-homebrew) and [installing it again](https://brew.sh/), without using `arch -x86_64` wrapper.

**Comment by Villafruela** [comment]
Ok thanks,

So i've been digging and find out the problem though i could not solve it.

It appears that the terminal on macOS can be used in "intel mode" via roseta 2 or "arm mode". you can check the mode you're in with the command : 
`arch`
It will return i386 if you're in intel mode or arm64 (native) if you're in arm mode.
You can force the use of your shell in native or intel mode with the command : 
`/usr/bin/arch -arm64` for arm
`/usr/bin/arch -x86_64` for intel
to make things easier i added 2 lines in my ".zshrc" config file via the command  (i explain in details so that others can do it as well ) : 
`nano ~/.zshrc`
i added these 2 lines :
alias arm="env /usr/bin/arch -arm64 /bin/zsh --login"
alias intel="env /usr/bin/arch -x86_64 /bin/zsh --login"
then save the .zshrc file and closed it.
so now i in the terminal, if i type 
`arm` i go in native mode (i can verify with `arch` that will return "arm64")
and if i type
`intel` in go in intel mode (`arch` will return "i386")

So i made a full reinstall of brew in native mode and then tried the `brew install cirruslabs/cli/tart`.
And.... it didn't worked
but i noticed that although i'm in native mode (arm), brew still tries to download the amd64 version and not the arm64 version. I get : 
Downloading https://github.com/cirruslabs/tart/releases/download/2.6.0/tart-amd64.tar.gz
while i should have : 
Downloading https://github.com/cirruslabs/tart/releases/download/2.6.0/tart-arm64.tar.gz

**Somehow, the detection of the Arm architecture doesn't work in**
https://github.com/cirruslabs/homebrew-cli/blob/master/tart.rb on line 14

i always end up with the "tart-amd64.tar.gz" installation.

i don't know ruby so i won't be of much help, but Is there a way to run the brew install with the arm archive ? Something like : 
`brew install cirruslabs/cli/tart -arm64` ?

**Comment by Villafruela** [comment]
Ok i nailed it !

I had 2 installations of homebrew one in arm mode in /op/homebrew and one in /usr/local/homebrew for the intell version and the default version is the intel one, so i kept installing/uninstalling the arm one while only using the intel one.

So i uninstalled homebrew twice the first one uninstalled the arm version, the second the intel version. Then reinstalled on native mode and checked with `brew config`.

and on the line Rosetta i have : 
`Rosetta 2: false`

And now it works like a charm...

Thks a lot for your help @edigaryev  and @fkorotkov !

**Comment by Villafruela** [comment]
Thks a lot for your help @edigaryev  and @fkorotkov !
