### ISSUE TITLE
Ability to Store VM images on NAS

### ISSUE THREAD

**Issue by lanycrost** [cirruslabs/tart#737]
Currently, tart utilizes the `fcntl` system call for locking VMs, which limits compatibility with `SMB` or `AFP`. Enabling the ability to run VMs on shared storage would be highly valuable. This enhancement would allow for storing VM images for multiple machines in a centralized location, alleviating concerns about individual device storage limitations.

Pulling machine images from a registry isn't an ideal option due to image sizes ranging from 30 to 50GBs and even 100GBs, resulting in prolonged retrieval times and significant network consumption. I suggest considering the use of files for locking up VMs, with the option to make it configurable.

Thanks!

https://chris.improbable.org/2010/12/16/everything-you-never-wanted-to-know-about-file-locking/

**Comment by lanycrost** [comment]
I'm trying to use `SMB` and `AFP`. You've given me an idea: I'll try using an image file because you're only locking the `config` file. Maybe that will work. After trying it out, I'll give you an update.

Thanks!

**Comment by lanycrost** [comment]
I've tried to use only `disk.img` file from `SMB` and `APF` share (using symbolic links), unfortunately it's not working. The `nvram.bin` and `config.json` is stored on local disk (because you are locking config.json). 

Thanks!

**Comment by fkorotkov** [comment]
@lanycrost how do you envision your workflow? You plan to clone VMs within the NAS and run it from multiple Macs? Do you have a single NAS instance? Are you concerned about network limits in case of running multiple VMs in parallel?

**Comment by lanycrost** [comment]
Yes, as you described. Mac Minis support 10Gbps links so most probably it will work I guess I need more deep research to understand the bottlenecks of this approach, but theoretically running 50Gb image with maximum speed will take about 1 minute to bring up the machine.

**Comment by fkorotkov** [comment]
It seems that `tart stop` functionality relies on `fcntl` since we "store" process id for a given VM.

If you have a folder with your images on a remote NAS then you can symlink it to `~/.tart/cache/OCIs/ghcr.io/foo/bar`. Then Tart will think that you VM name on a NAS is a tag for `ghcr.io/foo/bar` so you'll be able to do:

```
tart clone ghcr.io/foo/bar:nas-vm local-vm`
```

Which will theoretically copt over the VM from the NAS without `fcntl`.

**Comment by lanycrost** [comment]
It's really great idea, guess it will work :D will try to use this approach!
