### ISSUE TITLE
Single mounted directory ignore tag or prefix name

### ISSUE THREAD

**Issue by nd-brown** [cirruslabs/tart#748]
Since v2.6.0 the `--dir` parameter does not mount single directory.  

If you try to mount only one directory using argument `--dir=config:/path/to/config:ro` all content will be mounted directly to `/Volumes/My Shared Files`. 

If you try to mount only one directory using argument `--dir=/path/to/config:ro,tag=config` the folder will not mount at all.

However mounting 2 folders with `--dir` argument works fine.
I suspect that changes made here #733 , is the reason of that issue.

**Comment by fkorotkov** [comment]
@edigaryev noted that I missed that `--dir=config:/path/to/config:ro` mounts to `/Volumes/My Shared Files` and not `/Volumes/My Shared Files/config`.  #750 fixes it.

**Comment by nd-brown** [comment]
@fkorotkov @edigaryev 
Thank you!
