### ISSUE TITLE
 Better shell completions

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/tart#778]
Assumptions:
- I am using a modern Zsh (v5) with shell completions enabled
- `tart list` output:

```
$ tart list
Source Name                                                                                                          Disk Size State
local  example-sonoma-2                                                                                                90   58   stopped
local  example-sonoma-1                                                                                               90   58   stopped
oci    ghcr.io/cirruslabs/macos-sonoma-xcode:15.3                                                                    90   59   stopped
oci    ghcr.io/cirruslabs/macos-sonoma-xcode:latest                                                                  90   59   stopped
oci    ghcr.io/cirruslabs/macos-sonoma-xcode@sha256:03e19261894c588f9d478a7cd948992a025c66518189abeb9df501bcdd5ea568 90   59   stopped
```

### Current behavior

When completion is triggered, nothing is printed.

```
$ tart run [tab]
```

### Expected behavior

Available VMs (the `local` ones) are suggested:

```
$ tart run [tab]
example-sonoma-1    example-sonoma-2
```

### Implementation

Tart's CLI uses Swift [ArgumentParser](https://apple.github.io/swift-argument-parser/documentation/argumentparser), and looks like it has [support for accurate, customized shell completions](https://apple.github.io/swift-argument-parser/documentation/argumentparser/customizingcompletions) and supports the use case I described above.

I'm happy to submit a PR for this when I find some free time, if you agree with this feature suggestion.

**Comment by todd-dsm** [comment]
Here's what I ended up with...

Installed via homebrew on my work laptop. These installs always drop completions in the same directory:

```shell
% brew install tart
==> Fetching cirruslabs/cli/tart
==> Downloading https://github.com/cirruslabs/tart/releases/download/2.10.0/tart-arm64.tar.gz
Already downloaded: /Users/thomas/Library/Caches/Homebrew/downloads/5407e492e27b73c6de2bc751f5233f1d57ff9e4c2c96677e843398931b7b1a47--tart-arm64.tar.gz
==> Reinstalling cirruslabs/cli/tart 
==> Caveats
See the GitHub repository for more information

zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions  <-- completions are here
==> Summary
🍺  /opt/homebrew/Cellar/tart/2.10.0: 12 files, 11.6MB, built in 2 seconds
==> Running `brew cleanup tart`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

I use OMZSH; given the location of the completions, omzsh should just pick it up and run with it. 

---

That said, my work laptop totally fires off completions - just realized my personal laptop does not 😂 

I'll test some more and post if anything reveals itself.

**Comment by todd-dsm** [comment]
I found a quick fix that allows me to get past this but:
* it sucks as a solution, also
* it just works

```shell
% cat ~/.zprofile
# Homebrew Stuff
eval "$(/opt/homebrew/bin/brew shellenv)"
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
```

The first line is necessary; the second like only exists because of a failure somewhere upstream. The failure should be identified and solved.

But this works in a pinch.

**Comment by bartekpacia** [comment]
@todd-dsm I have [this](https://github.com/bartekpacia/dotfiles/blob/8687c48d338d6daa2dd4facc00139aa48ddb00fe/dot/zshrc#L57-L71) in my `~/.zshrc`. It's standard setup as recommended by Homebrew ([link](https://docs.brew.sh/Shell-Completion)).

**Comment by todd-dsm** [comment]
Sorry, just seeing this now. @bartekpacia, as an aside: you'll probably save yourself a ton of time by putting all of this stuff in the `"$ZSH_CUSTOM"` directory; example:

```shell
ll ~/.oh-my-zsh/custom
total 44
-rw-r--r-- 1 user staff 1350 Jun  3 11:03 aliases.zsh
-rw-r--r-- 1 user staff 1323 Nov  1  2023 aws-completions.zsh
-rw-r--r-- 1 user staff  314 Oct 27  2023 brew.zsh
-rw-r--r-- 1 user staff 5586 Sep 16 09:43 environment.zsh
-rw-r--r-- 1 user staff  500 Apr  8 11:11 example.zsh
-rw-r--r-- 1 user staff 1809 Jan 22  2024 functions.zsh
-rw-r--r-- 1 user staff  266 Oct 12  2023 golang.zsh
-rw-r--r-- 1 user staff  625 Mar 26 07:22 nodejs.zsh
-rw-r--r-- 1 user staff 1076 Jun  4 08:37 personal-sec.zsh
drwxr-xr-x 3 user staff   96 Oct 13  2023 plugins
drwxr-xr-x 3 user staff   96 Apr  8 11:11 themes
-rw-r--r-- 1 user staff  531 Oct 12  2023 zshell.zsh
```

Anything you throw in [custom](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization) is:
1. protected (that's _your_ space; will survive upgrades) 
2. brought into the local environment

This makes everything "turn brain off and go"; hope this helps 😊

**Comment by bartekpacia** [comment]
Hey Todd!

> y putting all of this stuff in the `"$ZSH_CUSTOM"` directory; example:

What do you mean by "this"?

**Comment by todd-dsm** [comment]
Here's the docs to explain: [omzsh custom](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization)

**Comment by bartekpacia** [comment]
Oh I know what ZSH_CUSTOM is. I just don't understand what you mean I should put in there?

**Comment by todd-dsm** [comment]
Lots of this stuff: (minus the plugins)

> @todd-dsm I have [this](https://github.com/bartekpacia/dotfiles/blob/8687c48d338d6daa2dd4facc00139aa48ddb00fe/dot/zshrc#L57-L71) in my `~/.zshrc`. It's standard setup as recommended by Homebrew ([link](https://docs.brew.sh/Shell-Completion)).
