### ISSUE TITLE
tart can't create virtual machine

### ISSUE THREAD

**Issue by uxbug** [cirruslabs/tart#781]
System information
- Apple M2
- Sonoma 14.3.1

Current behavior
```
$ tart --version

2.8.1
```
```
$ tart create macOS-CI-13.2 --from-ipsw UniversalMac_13.2_22D49_Restore.ipsw --disk-size 50
50
Installing OS...
0%
Error: An error occurred during installation. The virtual machine failed to start.
```
------------------------

Here's what I created before, and it worked.
```
$ tart list
list
Source Name     Disk Size State
local  macOS-CI 50   18   stopped
```
But it can't run now.
```
$ tart run macOS-CI

Error Domain=VZErrorDomain Code=1 "The virtual machine failed to start." UserInfo={NSLocalizedFailure=Internal Virtualization error., NSLocalizedFailureReason=The virtual machine failed to start.}
```
During this time, I have upgraded the system from macos13 to macos14 && update tart from an older version to 2.8.1.

--------------------------
`tart create macOS-CI-14.1 --from-ipsw UniversalMac_14.1_23B74_Restore.ipsw --disk-size 50`

It's working

Add a little more

When I run tart on multiple monitors, it will cause a white screen in other windows.

such as 

<img width="1005" alt="2024-04-09_17-43-34" src="https://github.com/cirruslabs/tart/assets/38550616/be6ea2d6-4d37-4491-a9b2-c90ca63e9262">

when I close the tart, the display returns to normal.

**Comment by uxbug** [comment]
Update
here's what happened after I completely uninstall tart.
during this period, macOS-CI was successfully Run by Cirrus.
but when I run it through the tart run command, this problem occurs.
```
$ tart --version
2.8.1
```
```
$ tart list
Source Name            Disk Size State
local  macOS-CI        50   18   stopped
local  macOS-CI-14.3.1 50   17   stopped
```

```
$ tart run macOS-CI-14.3.1
Error Domain=VZErrorDomain Code=6 "The maximum supported number of active virtual machines has been reached." UserInfo={NSLocalizedFailure=The number of virtual machines exceeds the limit., NSLocalizedFailureReason=The maximum supported number of active virtual machines has been reached.}
```

```
$ ps aux | grep Virtualization
user             46667   0.0  0.0 408627968   1488 s011  S+    6:46下午   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox Virtualization
```

**Comment by fkorotkov** [comment]
There was a moment at macOS Ventura 13.3 when going forward it was required to have both host and guest be 13.3+. Maybe this caused the issue while upgrading your host from before 13.3.

I don't want to be that person but have you tried to restart you host for the "The maximum supported number of active virtual machines"? We've see this counter getting weird for some users and it seemed restart helped them.

**Comment by uxbug** [comment]
> There was a moment at macOS Ventura 13.3 when going forward it was required to have both host and guest be 13.3+. Maybe this caused the issue while upgrading your host from before 13.3.
> 
> I don't want to be that person but have you tried to restart you host for the "The maximum supported number of active virtual machines"? We've see this counter getting weird for some users and it seemed restart helped them.

Thanks, It was solved after restarting and everything looks normal.
I need to observe further regarding the issue of encountering a white screen when running tart.

**Comment by fkorotkov** [comment]
Great! Glad it worked out for you!
