### ISSUE TITLE
"Egress is over the account limit" error causes download to be restarted

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/tart#783]
I accidentally deleted the `macos-sonoma-xcode:15.3` image and am trying to download it again right now, but it keeps failing:

```
$ tart pull ghcr.io/cirruslabs/macos-sonoma-xcode:15.3
pulling ghcr.io/cirruslabs/macos-sonoma-xcode:15.3...
pulling manifest...
pulling disk (51.9 GB compressed)...
29%
Error: The network connection was lost.
$ tart pull ghcr.io/cirruslabs/macos-sonoma-xcode:15.3
pulling ghcr.io/cirruslabs/macos-sonoma-xcode:15.3...
pulling manifest...
pulling disk (51.9 GB compressed)...
46%
Error: The network connection was lost.
$ tart pull ghcr.io/cirruslabs/macos-sonoma-xcode:15.3
pulling ghcr.io/cirruslabs/macos-sonoma-xcode:15.3...
pulling manifest...
pulling disk (51.9 GB compressed)...
53%
Error: The network connection was lost.
$ tart pull ghcr.io/cirruslabs/macos-sonoma-xcode:15.3
pulling ghcr.io/cirruslabs/macos-sonoma-xcode:15.3...
pulling manifest...
pulling disk (51.9 GB compressed)...
69%
Error: UnexpectedHTTPStatusCode(when: "pulling blob", code: 503, details: "<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ServerBusy</Code><Message>Egress is over the account limit.\nRequestId:7000d8f6-701e-00a7-0a51-8b1af0000000\nTime:2024-04-10T14:14:07.6788914Z</Message></Error>")
```

After I got the `Egress is over the account limit` error, the download starts from 0.

BTW, download also starts from 0 if `tart` is killed with CTRL + C.

**Comment by edigaryev** [comment]
> After I got the `Egress is over the account limit` error, the download starts from 0.

Is there a possibility that you've ran some some Tart command ([other than `pull` and `clone`](https://github.com/cirruslabs/tart/blob/896d03ce0b426298fdb4c71403eeba89e3e2737b/Sources/tart/Root.swift#L89-L96)) after you've got the `UnexpectedHTTPStatusCode`?

If so, that is how garbage collection works in Tart.

We could probably add a retry mechanism with exponential backoff to handle that.

@fkorotkov what do you think?

> BTW, download also starts from 0 if `tart` is killed with CTRL + C.

This one is intended:

https://github.com/cirruslabs/tart/blob/896d03ce0b426298fdb4c71403eeba89e3e2737b/Sources/tart/VMStorageOCI.swift#L194-L197

**Comment by edigaryev** [comment]
> Not sure about exponential backoff but since v2 pulls are resumable we can definitely re-try at least once so it eventually finishes.

The `Error: The network connection was lost.` seems to occur more than 1 time in the first message, though.

What is your concern w.r.t. having the exponential backoff with 3-5 retry attempts?

**Comment by fkorotkov** [comment]
No concerns. Just a finite number of retries will do. :-)

**Comment by bartekpacia** [comment]
For future readers: this is what I use to download a huge image automatically (thanks to Tart's caching):

```sh
until tart pull ghcr.io/cirruslabs/macos-sonoma-xcode:15.3; do
    echo "tart died, will execute it again" >&2
    sleep 1
done
```
