### ISSUE TITLE
documentation: how to mount a virtiofs (--dir) folder  using just /etc/fstab. 

### ISSUE THREAD

**Issue by tschiex** [cirruslabs/tart#791]
`mount -t virtiofs com.apple.virtio-fs.automount /mnt/shared
`
works. 

The documentation could explain, if this is feasible, how I could achieve the same using just `/etc/fstab`,
 assuming eg. I used `--dir=mac:/Users/me/Documents`.

**Comment by edigaryev** [comment]
I don't think that `/etc/fstab` is a thing on newer macOS versions, but perhaps someone more knowledgeable on the topic will chime in.

**Comment by tschiex** [comment]
Oops, I should have mentioned that this is for a Linux VM guest, not a MacOS guest.
For Linux, /etc/fstab is still widely used (even if often managed by systems I think).
