### ISSUE TITLE
tart stuck

### ISSUE THREAD

**Issue by tschiex** [cirruslabs/tart#807]
I'm not sure if it started with 2.9.1, but tart remains stuck when I start a VM. 
My Ubuntu image won't start, and neither would a freshly cloned Fedora image.

```
> tart clone ghcr.io/cirruslabs/fedora:latest fedora
pulling manifest...
pulling disk (0.6 GB compressed)...
100%
pulling NVRAM...
> tart set fedora --disk-size 50
> tart run fedora
```

remains stuck forever. --recovery does not help. 
Is there a way to "debug"/log tart or to use an old version (@2.9.0 did not work)? 
I tried an uninstall then reinstall, with no change.

BTW: installed on a MacBook Pro M3 running Sonoma 14.4.1, with homebrew (using cirruslab repo).

**Comment by adit-s** [comment]
I also had a problem related 2.9.1. I thought it may be related so I'm commenting here instead of opening another ticket. 
I downloaded the arm package and copied it over the 2.9.0 image and ran ./tart.app/Contents/MacOS/tart --version and got the attached error.
![Screenshot 2024-04-28 at 11 09 07 PM](https://github.com/cirruslabs/tart/assets/8761424/41117f70-a90d-4598-8a27-9d5f50958419)

**Comment by tschiex** [comment]
That's it Fedor: no tart window.  The command I use is:

`tart run --disk /dev/disk5s2 --disk /dev/disk5s1 --dir=mac:/Users/tschiex Linux`

/dev/disk5 is an external USB SSD. Both partitions (s1 is EXT4, s2 is NTFS) are owned by user 'tschiex'. No permission issue. The SSD does "blink" for 1 or 2 seconds once the tart command is executed.

```
> tart ip Linux
192.168.64.4
> ssh tschiex@192.168.64.4
```
does work. So the VM is running. The disks are properly mounted, as is the directory. But no tart window.
VM shutdown does lead to tart exiting.

Note: I previously set the VM screen size to 1680 and the VM runs Ubuntu 24.04 LTS.
But everything did work previously. I will try older tart versions.

**Comment by tschiex** [comment]
Well... I tried 2.9.0 and 2.8.1, and the same absence of tart windows.
I then tried a 
`tart set --display 1024x768 Linux`
to no avail.

**Comment by tschiex** [comment]
Updating tart to 2.10.0 solved my issue. The tart window is back! (in 1024 x 768 for now :-)
Kudos!
