### ISSUE TITLE
Investigate incremental pull

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#814]
A common workflow is when a remote image is just getting updated and re-pushed under the same tag. For example, `latest`. Then multiple hosts will try to pull the same image when they have `latest` pointing to the old `sha@...`.

It seems on a pull of a tag that is already presented locally we can try to compare if layers has changed and pull only changed layers.

**Comment by edigaryev** [comment]
Investigation results:

* [Chunking for Tart.ods](https://github.com/cirruslabs/tart/files/15336088/Chunking.for.Tart.ods).

Tart PRs:

* `tart push`-side: https://github.com/cirruslabs/tart/pull/821
* `tart pull`-side: https://github.com/cirruslabs/tart/pull/825
