### ISSUE TITLE
Can't run app, macOS claims: "tart is damaged and can't be opened"

### ISSUE THREAD

**Issue by nre-ableton** [cirruslabs/tart#815]
I tried running the `arm64` version of Tart on an M2 Mac Mini running Ventura 13.6.6 and ran into this error message:

![image](https://github.com/cirruslabs/tart/assets/16208985/81070a0e-d7c1-4ff4-a56b-1edc0f9feedb)

This occurred with Tart 2.10.0, but I tried 2.9.0 and got the same result. Looking at the generic help for this dialog, macOS hints that there could be codesigning issues. Is the asset provided in the release tarball properly signed?

I'd like to use Tart in our CI infrastructure, which uses MacPorts and not Homebrew. I didn't find a Port for Tart; is Homebrew the only way to install this software?

Forgive me if I'm overlooking something obvious; I checked the issue backlog and didn't find any similar issues.

**Comment by fkorotkov** [comment]
Hey @nre-ableton, Tart doesn't support Cmd+Click on `tart.app` nor for some reason double clicking on `.tar.gz` file will corrupt signature.

We do have manual installation instruction that you can find in the [quick start guide](https://tart.run/quick-start/). I also updating them in #816:

```bash
curl -LO https://github.com/cirruslabs/tart/releases/latest/download/tart-arm64.tar.gz
tar -xzvf tart-arm64.tar.gz
./tart.app/Contents/MacOS/tart --help
```

**Comment by nre-ableton** [comment]
Sorry I missed that, and thanks for updating the docs!
