### ISSUE TITLE
Add stats to FAQ about performance

### ISSUE THREAD

**Issue by keith** [cirruslabs/tart#82]
We currently use Mac Minis without any VMs because the VM software we used in the past affected performance too much to be worth it. It would be great if there were some stats, maybe in the FAQ, for large projects. I see there is a mention:

> near-native performance

But putting some numbers on that would be useful!

**Comment by fkorotkov** [comment]
I'm helping Flutter project to migrate to Tart VMs and we see that that half M1 (4 cores 8 GB) is as performant as a full 2018 MacMini with 6 cores with hyper threading.

I can run some syntactic tests with `stress-ng` and compare bare metal VS tart VM. Will that work for you, @keith?

**Comment by keith** [comment]
Interesting! I guess in our case I'd be most interested in what the performance was from a bare metal M1 Mac Mini vs the maximum resources you could give a single VM on the same machine. Which I think would generally emulate using this just for isolated environments as opposed to using it for multiple VMs running simultaneously.

**Comment by fkorotkov** [comment]
I just tried running Geekbench 5 on a bare metal Mac Mini M1 and the same test in a Tart VM with 8 cores and 16GB created like this:

```console
tart clone ghcr.io/cirruslabs/macos-monterey-base:latest testing
tart set --cpu 8 --memory 16384 testing
tart run testing
```

Here is [a report](https://browser.geekbench.com/v5/cpu/compare/14966395?baseline=14966339). Performance implication is only 5%.
