### ISSUE TITLE
ubuntu-minimal-cloud-img

### ISSUE THREAD

**Issue by jhoogeboom** [cirruslabs/tart#824]
Trying 
```
tart create ubuntuminimal
tart set ubuntuminimal --disk-size 20
tart run ubuntuminimal --disk ~/Downloads/ubuntu-24.04-minimal-cloudimg-arm64.img
```
I get `guest has stopped the virtual machine` straight away. Any idea? Or are the minimal cloud images not supported? The live server `ubuntu-24.04-live-server-arm64.iso` does work.

**Comment by fkorotkov** [comment]
Please check out how we build images in [this repository](https://github.com/cirruslabs/linux-image-templates). Particularly this part:

https://github.com/cirruslabs/linux-image-templates/blob/cfa6ad0c727870467018358e0a652de3989037b1/.cirrus.yml#L61-L63
