### ISSUE TITLE
When turned on FileVault, tart run <name> --no-graphics can not run VM

### ISSUE THREAD

**Issue by hologerry** [cirruslabs/tart#831]
After I turned on FileVault, the  `--no-graphics` does not working.
When using `tart run <name>`, everything is fine, I can login and enter the desktop.
When using `tart <name> --no-graphics`, the command produces no issues, while both ssh and vnc can not access VM.
<img width="482" alt="image" src="https://github.com/cirruslabs/tart/assets/11660168/a05019b6-0f6c-4d86-ac8b-0615ce33bf55">

<img width="1141" alt="image" src="https://github.com/cirruslabs/tart/assets/11660168/8c4b2d34-5ce1-4f70-bdb5-d18c38ee0aaf">

**Comment by fkorotkov** [comment]
Does you VM allow Remote Login? This setting should be enabled in Preferences inside the macOS guest.

**Comment by hologerry** [comment]
Yeah, I turned it on:
<img width="493" alt="image" src="https://github.com/cirruslabs/tart/assets/11660168/f797beb3-2bcd-4ad1-a688-f39897bab10c">

**Comment by hologerry** [comment]
When using `tart run <name>`, I can open ssh or vnc with the tart app window open.

**Comment by hologerry** [comment]
<img width="562" alt="image" src="https://github.com/cirruslabs/tart/assets/11660168/84d25130-bfc8-42b9-896c-239de5b7e3a3">

**Comment by hologerry** [comment]
I have figured this issue is caused by FileVault not SIP.
I installed a new VM if the FileVault turned on, the `--no-graphics` not working.

**Comment by hologerry** [comment]
Could tart using the `sudo fdesetup authrestart` for FileVault decryption?
https://www.reddit.com/r/macsysadmin/comments/ha8as7/remote_authenticated_filevault_restart/

**Comment by fkorotkov** [comment]
Seems some quirkiness of the macOS with enabled FileVault. Doesn't seem we can do anything on our side.
