### ISSUE TITLE
VMs always freeze/lock up after a few minutes.

### ISSUE THREAD

**Issue by ryanbooker** [cirruslabs/tart#84]
I'm finding that VMs always freeze/lock up after a few minutes. I'm using a fresh install of 12.4 (was also happening with 12.3.1).

Has anyone else noticed this?

**Comment by fkorotkov** [comment]
I noticed it when the VM is using 2 cores which is default. Try to 'tart set --cpu 4' for your VM.

**Comment by ryanbooker** [comment]
Great, thanks. That works. :)
