### ISSUE TITLE
macOS 15: Enabling VoiceOver crashes VM

### ISSUE THREAD

**Issue by torarnv** [cirruslabs/tart#841]
Likely a Virtualization.framework issue.

``` 
tart run macos:15.0.0-beta+test
guest has stopped the virtual machine due to error: Error Domain=VZErrorDomain Code=1 "The virtual machine stopped unexpectedly." UserInfo={NSLocalizedFailure=Internal Virtualization error., NSLocalizedFailureReason=The virtual machine stopped unexpectedly.}
```

**Comment by fkorotkov** [comment]
Yes, had to manually configure this part of the script.

**Comment by torarnv** [comment]
The issue is related to the USB based input devices, so `--suspendable` can be used to work around the issue. Is there a way for us to determine what the guest OS is when running, and if so only present `VZMacKeyboardConfiguration`/ `VZMacTrackpadConfiguration`?
