### ISSUE TITLE
Is there a way to store and run vm images from an external drive?

### ISSUE THREAD

**Issue by anarchy89** [cirruslabs/tart#845]
I only have a 256gb ssd, I use an external drive to do most of my work. 

Can i store and run vm images to a folder on an external drive?

**Comment by fkorotkov** [comment]
Yes, you can redefine TART_HOME environment variable to point to an external drive. Note that cloning will be slower since lack of APFS.

**Comment by fkorotkov** [comment]
You are right, if the external disk is also on APFS then no performance implication. But I think it's not common to have an APFS on an external drive and we've seen other users not having it setup this way.
