### ISSUE TITLE
Requesting FreeBSD image (or instructions on how to build and submit one)

### ISSUE THREAD

**Issue by clee** [cirruslabs/tart#846]
I'd like to run a FreeBSD guest using Tart since my Debian guest runs so well, but I don't see any documentation on how to build OCI images that will work with Tart (maybe I'm just searching wrong). 

While I'd love to build and use a FreeBSD image for myself, it would be even better if there were a `ghcr.io/cirruslabs/freebsd:14-release` that everyone could use.

**Comment by fkorotkov** [comment]
Last time we tried FreeBSD failed to load under `Virtualization.Framework`. You can experiment with `raw` VM images that you can find [here](https://www.freebsd.org/where/). For example, I donwnload [`FreeBSD-14.1-RELEASE-arm64-aarch64.raw.xz`](https://download.freebsd.org/releases/VM-IMAGES/14.1-RELEASE/aarch64/Latest/FreeBSD-14.1-RELEASE-arm64-aarch64.raw.xz), unatchived it and ran:

```
tart create --linux freebsd
mv ~/Downloads/FreeBSD-14.1-RELEASE-arm64-aarch64.raw ~/.tart/vms/freebsd/disk.img
```

But trying to boot I'm getting `No valid device tree blob found` error:

<img width="1038" alt="Screenshot 2024-06-23 at 3 25 08 PM" src="https://github.com/cirruslabs/tart/assets/989066/22607c15-8134-4b7a-8931-8b6c75e3408c">

**Comment by clee** [comment]
Does tart set up UEFI/ACPI for the guest? I've been experimenting with using UEFI instead of u-boot on various ARM SBCs I have here and that seems like the way forward; no custom device-tree blobs required.

**Comment by edigaryev** [comment]
>Does tart set up UEFI/ACPI for the guest?

Nope, this is done by the [Virtualization.Framework](https://developer.apple.com/documentation/virtualization), see [`VZEFIBootLoader`](https://developer.apple.com/documentation/virtualization/vzefibootloader).

**Comment by fkorotkov** [comment]
Found [the original discussion](https://github.com/cirruslabs/tart/discussions/397) so closing this issue in favor of it.
