### ISSUE TITLE
"Failed to lock auxiliary storage."

### ISSUE THREAD

**Issue by andrewhamon** [cirruslabs/tart#865]
Not sure if I should file this here, or in the packer repo. I'm using packer, and am trying to get builds automated in CI (they are working well locally).

I'm hitting the following error happening after IPSW unpack, shortly after packer invokes `tart run`. If I'm vnc'd in I can catch a flash of the vm window UI immediately opening then quitting.

```
    <snip>
    tart-cli.macos-vanilla: 54%
    tart-cli.macos-vanilla: 61%
    tart-cli.macos-vanilla: 68%
    tart-cli.macos-vanilla: 75%
    tart-cli.macos-vanilla: 82%
    tart-cli.macos-vanilla: 84%
    tart-cli.macos-vanilla: 86%
    tart-cli.macos-vanilla: 90%
    tart-cli.macos-vanilla: 100%
==> tart-cli.macos-vanilla: Updating virtual machine resources...
==> tart-cli.macos-vanilla: Inspecting machine disk image...
==> tart-cli.macos-vanilla: Getting partition table...
==> tart-cli.macos-vanilla: Found a recovery partition at GPT entry 3, let's remove it to save space and allow for resizing the main partition...
==> tart-cli.macos-vanilla: Successfully updated partitions!
==> tart-cli.macos-vanilla: Starting the virtual machine...
==> tart-cli.macos-vanilla: Waiting for the VNC server credentials from Tart...
==> tart-cli.macos-vanilla: Error Domain=VZErrorDomain Code=2 "Failed to lock auxiliary storage." UserInfo={NSLocalizedFailure=Invalid virtual machine configuration., NSLocalizedFailureReason=Failed to lock auxiliary storage., NSUnderlyingError=0x600002bdbed0 {Error Domain=NSPOSIXErrorDomain Code=35 "Resource temporarily unavailable"}}
==> tart-cli.macos-vanilla: Waiting for the tart process to exit...
==> tart-cli.macos-vanilla: Cleaning up virtual machine...
Build 'tart-cli.macos-vanilla' errored after 11 minutes 19 seconds: Build was halted.
```

I've taken care to ensure that `PWD` and `TART_HOME` are on the same filesystem, both on EBS and on the internal SSD, but same error (n=2 though, so not a ton of data).

If I ssh to that same CI box, I am able to `tart create ...` and `tart run` without any errors. I wonder if there is some sort of race condition.

Also, fwiw, these are some crusty (and, tbh, sluggish feeling) aws M1s.

Environment info:
```
# tart --version 
2.13.0
# sw_vers 
ProductName:		macOS
ProductVersion:		14.3
BuildVersion:		23D56
```

**Comment by andrewhamon** [comment]
Yeah, I worked around that by adding a 5 second delay to tart commands by wrapping it.

**Comment by edigaryev** [comment]
Yes, this is a well-known [`Virtualization.Framework` installer bug](https://github.com/cirruslabs/macos-image-templates/blob/127683c285011834db234bea3c2f4da5835513a7/templates/vanilla-sonoma.pkr.hcl#L78-L80).

Unfortunately, there's nothing we can do on Tart's side and our [Packer plugin for Tart](https://github.com/cirruslabs/packer-plugin-tart) has [`create_grace_time` option](https://developer.hashicorp.com/packer/integrations/cirruslabs/tart/latest/components/builder/tart#optional:) to work around this, so closing.

**Comment by andrewhamon** [comment]
Ahh thank you for that info. I originally had `create_grace_time` but somewhere along the line it got lost. Now I understand why it is necessary!
