### ISSUE TITLE
OCI cache doesn't follow the OCI image layout spec

### ISSUE THREAD

**Issue by andrewhamon** [cirruslabs/tart#867]
The OCI cache uses the same layout as the VMs folder. e.g.

```
tree ~/.tart/cache/OCIs/gcr.io/discord-development/discord_ci/macos/images/installer/23F79        
/Users/andyhamon/.tart/cache/OCIs/gcr.io/discord-development/discord_ci/macos/images/installer/23F79
├── config.json
├── disk.img
└── nvram.bin
```

This is, however, quite different from the [OCI spec](https://specs.opencontainers.org/image-spec/image-layout/).

This prevents using tools like [skopeo](https://github.com/containers/skopeo) to sling images around

**Comment by edigaryev** [comment]
Using an OCI image layout would mean saying goodbye to fast `tart clone`'s, which use the APFS copy-on-write mechanism, see https://github.com/cirruslabs/tart/issues/771#issuecomment-2026888806 for more details.

You can sling images using the `tart push` and `tart export`, or is there a specific functionality in Skopeo that you would like to see in Tart?

**Comment by andrewhamon** [comment]
>  would mean saying goodbye to fast tart clone's

Would it, though? The directory _layout_ would change, but wouldn't the blobs be identical?

The impetus for this issue is that I wanted to compare network performance of `tart push` vs another tool. I'm pushing to gcr.io which sadly doesn't support chunked uploads, but even in light of that I am surprised at the slowness.

Being able to use a different OCI-compliant tool would have allowed me to quickly diagnose if this is purely a network issue, or if there is something funny going on in tart.

**Comment by edigaryev** [comment]
> Would it, though? The directory _layout_ would change, but wouldn't the blobs be identical?

Tart VM's disk (when stored in the OCI storage) consists of multiple LZ4-compressed layers that we'd have to (1) decompress and (2) write to disk from scratch on each `tart clone` if we were to use the OCI layout.

> The impetus for this issue is that I wanted to compare network performance of `tart push` vs another tool. I'm pushing to gcr.io which sadly doesn't support chunked uploads, but even in light of that I am surprised at the slowness.

> Being able to use a different OCI-compliant tool would have allowed me to quickly diagnose if this is purely a network issue, or if there is something funny going on in tart.

I think you easily work around this by just pulling an already pushed Tart VM image from the OCI registry (including the local one<sup>1</sup>, to make things snappy) and then re-pushing it with your tool of choice.

<sup>1</sup>:

```
git clone https://github.com/distribution/distribution.git
cd distribution
go run cmd/registry/main.go serve config.yml
```

`config.yml`:

```yaml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /tmp/registry
http:
  addr: :8080
```

**Comment by fkorotkov** [comment]
I guess we can also take a look at adding `--concurrency` flag to `push` to push layers in parallel. 

@edigaryev if I recall correctly disk v2 is order agnostic in terms of layers, right? Or we still care about order of layers in there?

**Comment by andrewhamon** [comment]
> Tart VM's disk, when stored in the OCI storage, consists of multiple LZ4-compressed layers that we'd have to (1) decompress and (2) write to disk from scratch on each tart clone if we were to use the OCI layout.

I see, that makes sense.

Concurrent layer pushing will be huge! Can't wait to give that a try.
