### ISSUE TITLE
Can't resolve guest IP address

### ISSUE THREAD

**Issue by nre-ableton** [cirruslabs/tart#873]
I'm having difficulty resolving IP addresses for guest VMs that use bridged networking.

On older versions of Tart such as 2.10.0, `tart ip --resolver arp <name>` works, but after several hours/days, it stops working and we need to reclone these VMs to get everything back up and working. I'm going to run some longer tests over the weekend with Tart 2.15.0. However, I didn't see anything in the release notes of any recent versions about this, so I suspect the behavior still exists. I'll report back, though.

I'm using macOS Ventura for both the guest and host OS. Is this a known issue?

**Comment by edigaryev** [comment]
Unfortunately that's the reality of using `--net-bridged` and the ARP resolver: we won't know the IP-address of the VM until it sends a broadcast/multicast request that gets accepted by the host and a corresponding IP ↔︎ MAC association added to the ARP table (you can check it with `arp -an`).

This is normally done on startup for macOS guests and almost never on Linux guests, unless [e.g. Samba is installed](https://github.com/cirruslabs/tart/issues/810#issuecomment-2089624865) that generates such requests.

What you can do to work around this is to add a static entry on your local network's DHCP server to always offer a specific IP-address based on the MAC-address of that VM (can be retrieved via `jq -r '.macAddress' ~/.tart/vms/<VM>/config.json`)

**Comment by nre-ableton** [comment]
@edigaryev Thanks for the explanation, that makes a lot of sense. I'll close this issue as "wontfix", since it's not directly a problem in Tart.

**Comment by nirs** [comment]
I could reproduce it:

```
$ tart run --net-bridged en10 server
...
```

(find the ip in the console)

```
% ssh admin@10.100.102.163 ip a   
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether c2:e1:2c:51:62:20 brd ff:ff:ff:ff:ff:ff
    inet 10.100.102.163/24 metric 100 brd 10.100.102.255 scope global dynamic enp0s1
       valid_lft 3305sec preferred_lft 3305sec
    inet6 fe80::c0e1:2cff:fe51:6220/64 scope link 
       valid_lft forever preferred_lft forever
```

```
% tart ip --resolver arp server
no IP address found (not all Linux distributions are compatible with the ARP resolver)
```

```
% arp -anl 
Neighbor                Linklayer Address Expire(O) Expire(I)          Netif Refs Prbs
10.100.102.1            34:49:5b:1f:5b:a7 2m5s      2m5s          en10    1
10.100.102.10           4:42:1a:da:98:b0  expired   expired       en10    1
192.168.105.1           5e:e9:1e:67:7a:64 (none)    (none)    bridge10
224.0.0.251             1:0:5e:0:0:fb     (none)    (none)    bridge10
```

But while writing this comment, tart ip started to work:

```
% tart ip --resolver arp server
10.100.102.163
```

```
% arp -anl                     
Neighbor                Linklayer Address Expire(O) Expire(I)          Netif Refs Prbs
10.100.102.1            34:49:5b:1f:5b:a7 2m5s      1m58s         en10    1
10.100.102.10           4:42:1a:da:98:b0  expired   expired       en10    1
10.100.102.163          c2:e1:2c:51:62:20 expired   expired       en10    1
192.168.105.1           5e:e9:1e:67:7a:64 (none)    (none)    bridge10
224.0.0.251             1:0:5e:0:0:fb     (none)    (none)    bridge10
```

So maybe it should retry the operation with a reasonable timeout instead of failing fast?

Can be:

```
tart ip --resolver arp --timeout 60s
```

**Comment by edigaryev** [comment]
@nirs `tart ip` already supports retries, thanks to `--wait` command-line argument:

```shell
tart ip --resolver arp --wait 60 <VM>
```
