### ISSUE TITLE
Error when cloning

### ISSUE THREAD

**Issue by kennjoma** [cirruslabs/tart#882]
I'm getting an error at the cloning step:

tart clone ghcr.io/cirruslabs/macos-sonoma-base:latest sonoma-base

pulling manifest...
pulling disk (19.3 GB compressed)...
100%
pulling NVRAM...

Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "os", intValue: nil)], debugDescription: "Darwin VMs are only supported on Apple Silicon hosts", underlyingError: nil))

I've reinstalled tart multiple times and am still getting the same error. 

Running this on an M2 Max

**Comment by edigaryev** [comment]
You're most likely running Tart or Homebrew under Rosetta 2, please check out the following issues to diagnose this:

* https://github.com/cirruslabs/tart/issues/266
* https://github.com/cirruslabs/tart/issues/729
