### ISSUE TITLE
Fix VM IP

### ISSUE THREAD

**Issue by cdr-chakotay** [cirruslabs/tart#891]
Not really an issue, but my VM's IP changes time by time.
 This is very uncomfortable.
 Can I somehow fix the IP for an indefinite amount of time without fixing all IPs on the system ?

**Comment by edigaryev** [comment]
I see at least 3 options here:

1. Retrieve the current VM's IP using `tart ip`, e.g. `ssh admin@$(tart ip <VM>)`.

2. Ensure that the VM's MAC address stays the same by cloning it only once and making sure that the DHCP lease time is long enough (can be checked from inside of a VM using `ipconfig getpacket en0 | grep lease_time`).

3.  Use `--net-bridged` and configure your local network's DHCP server to always issue a static IP-address based on the VM's MAC-address.

**Comment by fkorotkov** [comment]
What's your workflow?

Do you clone VMs from a local one? Or if you are running two VMs from the same source simultaneously then they will get new MAC and therefore IP addresses.

**Comment by edigaryev** [comment]
> I think the macOS DHCP server is the issue?: https://tart.run/faq/#changing-the-default-dhcp-lease-time

It is an issue only when there's a churn of VMs on a given host, each VM having a different MAC-address. Typically happens on CI systems and this quickly overfills the DHCP table in `/var/db/dhcpd_leases`.

It seems that in your case it's a reverse issue, where you want to _increase_ the DHCP lease time to avoid the built-in DHCP server on the host from picking up another IP-address.

**Comment by edigaryev** [comment]
You can set a fixed IP-address in the guest's `System Settings → Network` that falls in the IP address range assigned to it (e.g. `192.168.64.2/24`).

But that might result in an IP-address conflict later down the road, when this IP address range changes or the host's DHCP server runs out of addresses and assigns this `192.168.64.2` to some other VM.

So, coordinating this DHCP server is probably the safest choice.
