### ISSUE TITLE
Support of Multiple Resolutions

### ISSUE THREAD

**Issue by jaykam** [cirruslabs/tart#896]
Hi Team,

I wanted to have following resolutions on the VM like - 

- 1024x768
- 1280x960
- 1440x900
- 1600x1200
- 1920x1080
- 2048x1536

I see there is a list of objects we're passing here, is it possible to have multiple support?

`result.displays = [
        VZMacGraphicsDisplayConfiguration(
          widthInPixels: vmConfig.display.width,
          heightInPixels: vmConfig.display.height,
          // A reasonable guess according to Apple's documentation[1]
          // [1]: https://developer.apple.com/documentation/coregraphics/1456599-cgdisplayscreensize
          pixelsPerInch: 72
        )`
         @edigaryev @fkorotkov

**Comment by jaykam** [comment]
@edigaryev @fkorotkov

**Comment by jaykam** [comment]
[](url)

**Comment by fkorotkov** [comment]
Unfortunately, multiple displays are not supported at the moment. Please subscribe to #590 for when it will be supported by `Virtualization.Framework`.
