### ISSUE TITLE
Update "latest" label on ubuntu to 24.04

### ISSUE THREAD

**Issue by icosahedron** [cirruslabs/tart#902]
Currently the tag for latest is set to 22.04 on ghcr.io/cirruslabs/ubuntu. 

There is a bug running Podman on 22.04 where the CNI version is incorrect and prevents a kind kubernetes cluster from starting. There are workarounds, but updating to 24.04 is the cleanest fix for this issue.

**Comment by edigaryev** [comment]
You could use `ghcr.io/cirruslabs/ubuntu:24.04` if you need to pin a specific Ubuntu version.
