### ISSUE TITLE
Is it possible to run multiple Linux vms emulating a typical ethernet network?

### ISSUE THREAD

**Issue by DrGo** [cirruslabs/tart#906]
I would like to emulate a typical small ethernet network in this configuration:

client <--> router <--> ISP

The ISP provides dhcp/dns to the router. The router which has two NICs provides dhcp/dns to the client which has no access to the ISP.

Is it possible to use Tart to setup 2 or 3 vms that emulate this network?

Thanks,

**Comment by edigaryev** [comment]
Do I understand correctly that you want to run a router on a Linux-based Tart VM, and make sure that clients (also Linux-based Tart VMs) only access ISP through that router?

**Comment by DrGo** [comment]
Correct. I would like to simulate as faithfully as possible the kind of common home network situations where a router isolates machines on local networks (iptables with NAT) and serves dhcp (is-dhcp-server) and dns (unbound) while the router itself gets dhcp-assigned address from an ISP router ( could be the host machine or another vm)

Thanks

**Comment by edigaryev** [comment]
This could be done fully on host using the [`VZFileHandleNetworkDeviceAttachment`](https://developer.apple.com/documentation/virtualization/vzfilehandlenetworkdeviceattachment), which we actually use to let the [Softnet](https://github.com/cirruslabs/softnet) filter Tart VM's network traffic.

However, given the daemon-less nature of Tart, even if we'll have a host-only solution for this at some point, it'll likely require a separate daemon running on the system to orchestrate the networking and take care of dealing the file descriptors to corresponding VMs and routing the traffic.

For now the easiest way to have a setup like you want is probably [setting up VLANs on macOS](https://support.apple.com/en-am/guide/mac-help/mh15134/mac) (requires Ethernet interface) and using the created `vlan[0-9]+` interfaces as an argument to `--net-bridged`.

Afterwards, you can fully handle the networking on your switch/router by creating virtual VLAN interfaces and joining them together, and it should be much faster than the software-only networking.

**Comment by DrGo** [comment]
great.. thanks!
