### ISSUE TITLE
no IP address found for Ubuntu VM

### ISSUE THREAD

**Issue by barkingfoodog** [cirruslabs/tart#912]
I'm running tart 2.18.4 on macOS Sequoia 15.0. Tart works fine with a macOS image, and I'm trying to get an Ubuntu VM going for the first time.

I followed the basic steps from https://tart.run/quick-start/:
```
tart clone ghcr.io/cirruslabs/ubuntu:latest ubuntu
tart set ubuntu --disk-size 50
tart run ubuntu
```
The VM downloads, boots up, and I can log into through the tart GUI. However, I'm unable to get the VM IP using `tart ip ubuntu`. Instead I get:
```
no IP address found
```
I found #632 and tried the workaround from #657 but that doesn't help. After clearing `/var/db/dhcpd_leases` and restarting the VM I get output that looks legit in `/var/db/dhcpd_leases`:
```
{
	name=ubuntu
	ip_address=192.168.64.2
	hw_address=ff,f1:f5:dd:7f:0:2:0:0:ab:11:b5:58:a4:8e:38:af:82:b9
	identifier=ff,f1:f5:dd:7f:0:2:0:0:ab:11:b5:58:a4:8e:38:af:82:b9
	lease=0x66fa772c
}
```
This matches the IP inside the VM (confirmed using `ifconfig`).

I have an OpenVPN Connect VPN running, but disabling it doesn't seem to make any difference. I don't have any issues getting the IP address from a macOS VM running under tart.

Any compatibility issues with macOS 15 or other troubleshooting ideas for how to get `tart ip ubuntu` returning the VM's IP address?

**Comment by edigaryev** [comment]
Looks like a bug in the macOS DHCP server:

<img width="1187" alt="Screenshot 2024-09-30 at 14 28 41" src="https://github.com/user-attachments/assets/31cc8708-d9d3-4fea-8329-62d078b46e09">

It uses the client ID (which is an opaque value) not just in the `identifier=` field, but also in `hw_address=` field, which should only contain MAC address.

I've created https://github.com/cirruslabs/linux-image-templates/pull/38 to address this in our Linux VM images.

**Comment by barkingfoodog** [comment]
Thank you! I'll watch for the next Linux VM build and confirm the fix before closing this.

**Comment by barkingfoodog** [comment]
@edigaryev I saw new builds come through a couple days ago at https://github.com/cirruslabs/linux-image-templates/pkgs/container/ubuntu. I pulled a fresh copy of the 22.04 image and I'm still not getting an IP from `tart ip ubuntu`.

Should those images have the fix from https://github.com/cirruslabs/linux-image-templates/pull/38?

**Comment by edigaryev** [comment]
@barkingfoodog my bad, I was testing the fix on the initial boot, which used the `network-config` provided to the Cloud Init.

I've created https://github.com/cirruslabs/linux-image-templates/pull/39 to fix this and will initiate a re-build of base images once it gets merged 🙌

**Comment by edigaryev** [comment]
Should work now, tested with the latest versions of:

* `ghcr.io/cirruslabs/ubuntu:latest`
* `ghcr.io/cirruslabs/ubuntu:24.04`
* `ghcr.io/cirruslabs/debian:latest`
* `ghcr.io/cirruslabs/fedora:latest` (AFAIR this one worked before the fix)

**Comment by barkingfoodog** [comment]
@edigaryev I can confirm this works now with `ghcr.io/cirruslabs/ubuntu:latest` using Tart 2.18.4 on macOS Sequoia 15.0.1. Thank you!

**Comment by GregOriol** [comment]
Thank you for documenting this: it helped me with https://github.com/utmapp/UTM/issues/3294
