### ISSUE TITLE
Tart Push to GitLab Registry Failing

### ISSUE THREAD

**Issue by yangyi625** [cirruslabs/tart#914]
- System Information
  - Tart version: 2.18.4
  - Tart version that works: 2.14.0
  - Operating System: macOS 14.5
  - Hardware: Apple M1
  - GitLab version: [v16.11.10](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v16.11.10)

- Problem Description
  - I'm encountering an issue when attempting to push a Tart VM image to my GitLab registry. The push operation consistently fails with Tart version 2.18.4, whereas it works fine with the older version 2.14.0.

![image](https://github.com/user-attachments/assets/c04c6cca-aca6-42cc-8514-82404117c308)

**Comment by edigaryev** [comment]
I've managed to successfully push a cloned `ghcr.io/cirruslabs/ubuntu@sha256:7809213cbd1847a066e7f2589862f417bec2bb277438154e78e65f3a8e6394ea` VM image to GitLab Enterprise Edition 17.5.0-pre (the one that's currently runs on gitlab.com).

Could you please try pushing the same image to your GitLab server using your own credentials (and not a temporary CI ones)?

**Comment by tvtamas** [comment]
Hi,

I'm getting the same error as @yangyi625:

```
pushing config...
pushing disk... this will take a while...
21%
Error: cancelled
Attempting to re-try...
Error: cancelled
Attempting to re-try...
Error: cancelled
Attempting to re-try...
Error: AuthFailed(why: "received unexpected HTTP status code 400 while retrieving an authentication token", details: "Bad Request")
```
Using Tart `2.18.5`, self-hosted GitLab `v17.4.1` and GitLab's fork of the registry version: `v4.9.0-gitlab`.

The push is done by using a Personal Access Token still valid for a couple of months.

After retrying the command several tries the upload percentage does increase.

**Comment by yangyi625** [comment]
Hi @edigaryev ,

Using a personal token works fine, but I still prefer to use a CI token.

I tried using Mitmproxy to see which part was causing the error. The results are as follows:

![all request](https://github.com/user-attachments/assets/65b6e770-22f6-4c21-8ae2-7e5ec082a6b1)

It looks more like it's getting a 401 error during upload. The response is as follows:

![upload request](https://github.com/user-attachments/assets/3b3ca93d-0216-4fba-a84b-7e5f52b95196)

I can't quite understand why I'm encountering an authentication issue here
