### ISSUE TITLE
tart run : not working on my Sequoia 15.1

### ISSUE THREAD

**Issue by JgP35** [cirruslabs/tart#942]
Hello

Since I have Sequoia 15.1 tart no longuer work.

After command 👍 
tart run ubuntu for instance, nothing happen even a long wait.

Regards

**Comment by edigaryev** [comment]
Does Tart icon appear in dock when you invoke `tart run`?

Could be related to https://github.com/cirruslabs/tart/issues/928.

**Comment by JgP35** [comment]
Hello
Thanks for answer @edigaryev. I did a real mistake when installing tart on new mac. sorry for this issue.

Regards
