### ISSUE TITLE
`tart pull` unreliable, way slower than `skopeo`

### ISSUE THREAD

**Issue by andrewhamon** [cirruslabs/tart#963]
Hello again. I know I am always complaining about push/pull speed and reliability.

### Background

At Discord, we push and pull pretty large images (~40GB, though sometimes ~60GB if we are in the middle of an Xcode upgrade or something).

Quite often I see `tart push`/`tart pull` encounter multiple errors and eventually die completely.

When it doesn't die completely, it is always far far slower than I would expect it to be. For example, here was a recent session:

```
time tart pull us-docker.pkg.dev/discord-development/gcr.io/discord_ci/macos/images/tart/base:main-2024_11_08.20_46_47
pulling us-docker.pkg.dev/discord-development/gcr.io/discord_ci/macos/images/tart/base:main-2024_11_08.20_46_47...
pulling manifest...
pulling disk (42.0 GB compressed)...
34%
Error: The network connection was lost.
Attempting to re-try...
pulling disk (42.0 GB compressed)...
32%
Error: The network connection was lost.
Attempting to re-try...
pulling disk (42.0 GB compressed)...
32%
Error: The network connection was lost.
Attempting to re-try...
pulling disk (42.0 GB compressed)...
32%
Error: The network connection was lost.
Attempting to re-try...
pulling disk (42.0 GB compressed)...
32%
Error: The network connection was lost.
Attempting to re-try...
Error: The network connection was lost.
tart pull   59.04s user 79.39s system 59% cpu 3:52.95 total
```

At the time of this writing, I can not get tart to succeed on a pull. 

### Meanwhile, [skopeo](https://github.com/containers/skopeo)

For the longest time, I've been blaming google artifact registry. But today I decided to see how fast an image pull is using skopeo.

```
time skopeo --insecure-policy copy docker://us-docker.pkg.dev/discord-development/gcr.io/discord_ci/macos/images/tart/base:main-2024_11_08.20_46_47 dir:./tart-image
```

Skopeo pulls the exact same image, to the same disk, in about 90 seconds. **That is around 3700Mbps**. This is at least an order of magnitude faster than tart when tart actually succeeds.

I know this isn't quite an apples-to-apples comparison, since tart also has to re-assemble the final disk image. But I think there is something fundamentally broken about how tart pulls images (particularly because of the reliability issues, which I can not replicate with skopeo even after numerous reruns).

### Testing details
tart version: `2.21.0` - precompiled bin from github release
test machine: AWS `mac2-m2.metal`. `TART_HOME` set to the internal SSD to remove EBS bottlenecks.
macOS version: `14.7`

**Comment by edigaryev** [comment]
Hello Andy 👋

The `tart pull` is expected to be slower than `skopeo`. While `skopeo` only fetches the container image, `tart pull` also performs LZ4 decompression of the layers and hole punching, to yield a sparse file on disk after pulling.

However, I think we could look into improving the UX of retries, and probably support HTTP `Range:` requests to avoid re-fetching the part of the failed layer that we already have locally.

**Comment by andrewhamon** [comment]
> also performs LZ4 decompression of the layers and hole punching

lz4 is supposed to be quite a fast algorithm though. It should be able to keep up with the network (note: tart frequently does not even saturate a gigabit connection), or at the very least it should not cause such a massive performance loss.

>  by not throwing so many scary errors

I actually am interested in the opposite - I want more detailed logs and error messages. `Error: The network connection was lost.` feels pretty generic and I wonder if some useful context is being discarded.

Detailed logging on a per-layer basis would be very helpful to better understand exactly where the bottleneck lies.

**Comment by andrewhamon** [comment]
As another point of comparison, I can import and export tart images very quickly:

```
time tart export us-docker.pkg.dev/discord-development/gcr.io/discord_ci/macos/images/tart/base:main-2024_09_16.22_57_46 exported.tvm
exporting...
tart export  exported.tvm  528.25s user 27.34s system 811% cpu 1:08.50 total

du -h exported.tvm
 40G    exported.tvm

time tart import exported.tvm my-export
importing...
tart import exported.tvm my-export  127.96s user 17.85s system 194% cpu 1:14.92 total
```

So I feel like `tart pull` should be, at worst, about 1 minute slower than Skopeo.

**Comment by andrewhamon** [comment]
I'll give the new release a try and see how things perform :)

**Comment by edigaryev** [comment]
Please checkout the [latest `2.22.4` release](https://github.com/cirruslabs/tart/releases/tag/2.22.4), it should improve both the speed and the reliability.
