### ISSUE TITLE
x86 Virtualization on Mac ARM 

### ISSUE THREAD

**Issue by gabemeola** [cirruslabs/tart#964]
Apologies for asking here, I couldn't find a better forum.

Is there a recommended way to run a linux (ubuntu) image with x86 arch on an M series Mac? I was able to run an arm based linux vm and mount rosetta to run one off workloads but this isn't quite the same as changing the entire OS's arch.

Thanks!

**Comment by james-rant** [comment]
You'll probably want an x86 emulator such as QEMU instead of native virtualisation.
