### ISSUE TITLE
Can tart support port mapping?

### ISSUE THREAD

**Issue by zzzworm** [cirruslabs/tart#972]
Because Apple's virtualization framework does not support the bridge network mode, but we need to provide services in the virtual machine in NAT mode to the outside world. Can it support port mapping? Similar to Docker's port mapping.

**Comment by edigaryev** [comment]
> Because Apple's virtualization framework does not support the bridge network mode

Virtualization.Framework [does support bridged networking](https://developer.apple.com/documentation/virtualization/vzbridgednetworkdeviceattachment).

In Tart, it can be enabled by passing e.g. `--net-bridged=en0` to `tart run`.
