### ISSUE TITLE
set random-serial causes Monterey VM to not start

### ISSUE THREAD

**Issue by mrpepik** [cirruslabs/tart#977]
Hi everyone,

I am new to tart, but am very interested in using it to assist our cicd builds.

Setup:
M4 Mac Pro Laptop
Sequoia 15.2
Tart version 2.22.0

I am able to import a new VM from an export or from an IPSW file and run it with no problems.  I am also able to clone that VM to a new VM and it boots without issue.  However when I run the `set --random-serial` to the new VM, the VM that I ran this command against is no longer able to boot.  In noticed that in the `config.json`, the `ecid` changed from this command.  I manually reset the `ecid` variable back to the original setting and the VM was able to boot again, I did have to sign in to mount the disk, but it did start up.

This is affecting any OCI MacOS VM I download from the `ghcr.io` repository.

I am able to move forward without resetting the serial, but wanted to report it here.  If you need more information, please let me know.

Thanks
Joe

**Comment by edigaryev** [comment]
Hello Joe 👋 

Could you please post the exact `tart` commands sequence you're using?

Starting from pulling the image and ending with `tart run` and its arguments.

This should help with reproducing the issue you're facing.

**Comment by mrpepik** [comment]
Hi Nikolay,

To start with, I followed the quick start guide:

```
brew install cirruslabs/cli/tart
tart clone ghcr.io/cirruslabs/macos-monterey-xcode:latest monterey-xcode
tart run monterey-xcode
```
The `tart run` command just produced a blank tart window and `tart ip monterey-xcode` even 5 minutes later did not return an IP.

I then tested with pulling the vanilla version:
```
tart clone ghcr.io/cirruslabs/macos-monterey-vanilla:latest monterey-van
tart run monterey-van
```

With the same results.

I then removed the brew install, and downloaded the tar.gz from Github and put it into my /Applications directory.  I got the same results, a blank tart console window with the VM not booting.

From there, I downloaded an IPSW to a M1 laptop I have and installed the tart app there.  After it downloaded, I was able to build a new tart VM.  After initial install and booting, I then exported the VM to a flat file, copied it to my M4 laptop.  Where I ran the following commands:

```
/Applications/tart.app/Contents/MacOS/tart import montm1.export montm1
```
I ran a list to make sure it was there.  Then I started the VM 2 times to ensure that it booted and I get a console so I could access the VM.  This worked.  I then cloned that VM to a new instance:
```
/Applications/tart.app/Contents/MacOS/tart clone montm1 b1
/Applications/tart.app/Contents/MacOS/tart run b1
```
The newly cloned VM ran fine.

I wasn't sure if I needed to change the Mac address or serial, I had seen where it was suggested for some people who could not get a console window.  So I then ran `/Applications/tart.app/Contents/MacOS/tart set b1 --random-mac --random-serial`.  After  executing the set command, I was no longer able to start the VM.

To test, I cloned the imported VM several times, and ran the set commands by themselves.  I found that the `set --random-serial` is that caused the VM to not find the disk or start.

I did review the config.json files and found that the `ecid` is changing when I run that command which I assume is associated to identifying and accessing the disk.img file.  But I also found that in a clone, the Mac address is dynamically updated, so I do not need to run the set command for setting a random mac.

I hope the process I followed is clear here.  I did not test on my M1 to see I have the same issue.

Hope this helps.

Joe

**Comment by edigaryev** [comment]
@mrpepik from the description of the steps you've performed, it seems that there are two separate issues:

1. VM booting delay (could be due to I/O) or some incompatibility with the Monterey VMs on newer macOS versions/processors
1. `tart set --random-serial` makes macOS 12 (Monterey) VMs unbootable

Regarding, 1, I cannot reproduce this, can you try pulling, cloning and running a macOS 14 (Sequoia) VM instead?

```
tart pull ghcr.io/cirruslabs/macos-sequoia-base:latest
tart clone ghcr.io/cirruslabs/macos-sequoia-base:latest sequoia
tart run sequoia
```

Please wait at least 30-60 seconds.

Regarding 2, I can reproduce this, and it seems that macOS 12 (Monterey) VMs probably just don't support that functionality because they've been [long time EOL](https://en.wikipedia.org/wiki/MacOS#Timeline_of_releases).

**Comment by mrpepik** [comment]
I am pulling Sequoia now.  

That makes sense about Monterey not supporting a serial id change.

I will report back on testing a clone of Sequoia on M4 after it downloads.

**Comment by mrpepik** [comment]
I pulled and tested with Sonoma and it booted just fine, even with a `set --random-serial` being added after booting the first time.  

So the issue I was seeing, I believe was strictly with the Monterey version of MacOS.

Thank you for all of your help.
